### ISSUE TITLE
Bug: Videoplayer lässt sich nicht abspielen

### ISSUE THREAD

**Issue by derLesh** [pietsmietde/Bugs#1]
Da seit meinem Reddit Post immer noch das Problem besteht, hier das ganze nochmal als Issue

**Beschreibe den Fehler**
Mit dem neuen Update kommt ich nicht über das Intro hinaus. Ich muss auf den Kopfhörer im Player klicken und von "Soundhandler" auf "main" wechseln. Auf Main gibt es keinen Sound also muss man wieder zurück wechseln. Ein paar Sekunden oder vielleicht auch 1 bis 2 Minuten kann man ungestört gucken, bis sich dann wieder der Player aufhängt und man die selben Schritte wie zum Anfang durchführen muss.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu irgendeinem Pietsmiet Video
2. Klicke auf "Play"
3. Nach wenigen Sekunden, wenn das Video selbst pausiert, auf den Kopfhörer klicken
4. Auf "Main" wechseln
5. Auf "Soundhandler" wechseln

**Erwartetes Verhalten**
Der Player spielt das Video wie gewohnt ab und bleibt nicht hängen

**Screenshots**
![image](https://user-images.githubusercontent.com/11671272/52477647-fb296080-2ba2-11e9-942f-ddf16368b65e.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10
 - Browser: Chrome, Edge
 - Browser-Version: Chrome 72.0.3626.96, Edge 44.17763.1.0

**Weitere Informationen**
Ich hab die alternative Quelle ausprobiert - selbes Problem
Ich habe meinen Adblocker aktiviert und deaktiviert - selbes Problem
Ich habe die Qualität geändert - selbes Problem

**Comment by YoKoGFX** [comment]
Tritt auch bei folgender Konfiguration auf:
* Betriebssystem: MacOS 10.14.3 (18D109)
* Browser: Safari
* Browser-Version: Safari, Version 12.0.3 (14606.4.5)

**Comment by romanzipp** [comment]
Ich bin mir leider nicht sicher, das mit "Soundhandler" oder dem Kopfhörer-Icon gemeint ist. Bei unseren Tests auf mehreren Browsern ist sowas noch nicht passiert.
Hast du eine spezielle Audiokonfiguration?
Es würde auch helfen, wenn wir ein Video von dem ganzen Ablauf bekommen könnten.

**Comment by YoKoGFX** [comment]
@romanzipp Er meint den "Audio Track":
<img width="209" alt="bildschirmfoto 2019-02-10 um 13 04 08" src="https://user-images.githubusercontent.com/18743976/52533448-60608b80-2d34-11e9-9ac4-9f53ca871979.png">

Wenn Ihr das nicht fixen könnt kann ich auch einen Bug Report bei Apple öffnen, die Fixen sowas relativ schnell. Ich habe vor ein paar Monaten schon mal einen auf gemacht, weil Eure Website immer den Mac total langsam gemacht hat, wurde innerhalb von ein paar Wochen gefixt.

**Comment by derLesh** [comment]
Ja genau ich mein den "Audio Track"
Und irgendwelche Soundeinstellungen haben ich auch nicht vorgenommen. 

Video vom ganzen Ablauf:
https://streamable.com/z2j49

**Comment by derLesh** [comment]
Ich habe gerade etwas interessantes herausgefunden. 
Habe mir gerade eben mal Firefox Nightly runtergeladen, um weitere Browser zu testen. Dabei ist mir aufgefallen, dass auch da das Video gar nicht erst startet. Doch über das Kontextmenü kann ich auf "Abspielen" drücken und das Video läuft ohne Probleme. Nur sehe ich durchgehend einen Ladebalken

https://streamable.com/tfzs4

**Comment by romanzipp** [comment]
@derLesh @YoKoGFX könnt ihr mir sagen, auf welcher Sprache ihr Browser & OS habt? Leider kann ich die Audiotrackauswahl nicht triggern

**Comment by YoKoGFX** [comment]
@romanzipp Sprache ist bei mir auf "Deutsch" eingestellt.

**Comment by derLesh** [comment]
Genau wie @YoKoGFX steht mein Browser sowie OS auf Deutsch

**Comment by YoKoGFX** [comment]
Ich habe mal einen Radar bei Apple erstellt!

**Comment by YoKoGFX** [comment]
@romanzipp Ihr solltet auch die Pakete, von dem Video player (sollte MPEG-Dash sein) auf 2 MB oder so aufteilen. Denn Ihr habt dadurch aktuell unglaublich viele unnötige Requests!

**Comment by YoKoGFX** [comment]
@romanzipp  Wenn man das Video auf "main" stellt, kommt dieser Fehler. Dann spielt es aber ab. Nur halt ohne ton. Bitte schaut mal nach nem fix, denn es ist wirklich scheiße so …
<img width="1440" alt="Bildschirmfoto 2019-03-17 um 16 37 43" src="https://user-images.githubusercontent.com/18743976/54493683-0f175f00-48d3-11e9-9550-1fa8882ae4b4.png">

**Comment by romanzipp** [comment]
Wir haben bereits eine Lösung für die Probleme mit dem aktuellen Player in der Pipeline. Ich rechne damit, dass es ist den nächsten Tagen kommen wird.

**Comment by derLesh** [comment]
Mit dem neusten Player wurde das Problem behoben. Für mich jedenfalls

**Comment by YoKoGFX** [comment]
Ja, neuer Player hat das Problem gefixt. Ihr solltet nur mal schauen, wie man PiP in Safari für den neuen Player aktivieren kann. Dann wäre ich super happy :)

**Comment by derLesh** [comment]
Selbes würde ich mir natürlich für Chrome auch wünschen :D 

Und dass sich das Video nicht den Vollbildschirmmodus geht wenn man rechtsklickt auf den Player macht
