### ISSUE TITLE
Bug: Testseite

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#10]
**Beschreibe den Fehler**
Es wurde anscheinend vergessen eine Testseite zu löschen.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/news/allgemein/1478-testseite

**Erwartetes Verhalten**
Sollte nicht existieren.

**Comment by romanzipp** [comment]
Testseite wurde entfernt
