### ISSUE TITLE
Bug: Safari Probleme bei Videowiedergabe

### ISSUE THREAD

**Issue by Hackalife** [PietSmietde/Bugs#104]
**Beschreibe den Fehler**
In Safari ist es nicht moeglich Videos abzuspielen.
Der aktuell einzige Umweg, den ich finde, ist via developer tools, die seite simuliert mit einem ipad aufzurufen, dort spielen die Videos normal ab
**Reproduktion**

Versuch ein beliebiges Viedo in Safari zu starten.
Lange ladezeiten, oft nur Wiedergabe der ersten sekunden

**Erwartetes Verhalten**

naja, das video sollte einfach abspielen ?

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Mac OS 10.14.6
- Browser: Safari 
 - Browser-Version: 12.1.2 (14607.3.9)

**Comment by romanzipp** [comment]
Spielen die Videos auf niedrigeren Qualitätsstufen ab?
Ist dein Internet schnell genug, um hochauflösende Videos flüssig abzuspielen?
Hast du irgendwelche Erweiterungen installiert, die das Abspielen verhindern könnten?

**Comment by Hackalife** [comment]
Internet ist schnell genug, 1 gigabit in FFM.
keine erweiterungen installiert.
andere videos spielen auch mit 4k aufloesung fluessig.

**Comment by romanzipp** [comment]
Gab es mittlerweile ein Update, wodurch die Fehler behoben werden konnten? Kann leider nichts reproduzieren.
