### ISSUE TITLE
Bug: Clips gemuted in Firefox, wenn in neuem Tab geöffnet

### ISSUE THREAD

**Issue by Y4nnickr** [PietSmietde/Bugs#105]
**Beschreibe den Fehler**
Eine klare und knappe Beschreibung, um welchen Fehler es sich handelt.
Wenn ich in Firefox Clips in einem neuen Tab öffne, ist der Player immer gemuted.
Es spielt dabei keine Rolle, ob der Player zuvor bereits stummgestellt wwurde oder nicht.
Bei Öffnen des Clips im gleichen Tab wird der Ton wie gewollt abgespielt.
**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu '....'
2. Klicke auf '....'
1)Ansicht aller Clips öffnen
2)Clip in neuem Tab öffnen (egal ob per Rechtsklick->Link in neuem Tab öffnen oder Klick mit Mausrad)

**Erwartetes Verhalten**
Eine Beschreibung des zu erwartenden Verhaltens / Ergebnisses.

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: [z.B. Windows] Windows 10
 - Browser: [z.B. Chrome, Safari] Firefox
 - Browser-Version: [z.B. 22] 68.0.2 (64-Bit)

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: [z.B. iPhone6]
 - Betriebssystem: [z.B. iOS8.1]
 - Browser: [z.B. stock browser, Safari]
 - Browser-Version: [z.B. 22]

**Weitere Informationen**
Weiter Informationen über das Problem, wenn vorhanden.

**Comment by NoTeefy** [comment]
Ursache liegt denke ich an dem hier: https://hacks.mozilla.org/2019/02/firefox-66-to-block-automatically-playing-audible-video-and-audio/
Das ist ein normales Verhalten bei Firefox seit der Version 66.0

**Comment by romanzipp** [comment]
Das ist das erwartete Verhalten, welches durch die Autoplay Policies in verschiedenen Browsern umgesetzt wird. Wenn du diese Richtlinien deaktivieren möchtest, hast du - wie @NoTeefy erwähnt hat, dazu die Möglichkeit in den Webseiteneinstellungen deines Browsers. Gleiches trifft auch für Chrome zu.
