### ISSUE TITLE
Bug: Videos nicht abspielbar unter macOS

### ISSUE THREAD

**Issue by Erik4456** [PietSmietde/Bugs#106]
**Beschreibe den Fehler**
Videos lassen sich nicht mehr abspielen (seit Pietsmiet Portal 2.0)

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Klicke auf das Video(thumbnail) 

**Erwartetes Verhalten**
Die Seite wird geladen, jedoch funktioniert der Player nicht. "Something went wrong"
Die Fehlermeldung "TypeError: entryTypes contained only unsupported types" erscheint am unteren linken Bildschirmrand.

**Screenshots**

![Ohne Titel](https://user-images.githubusercontent.com/54914038/64289587-c7f65680-cf64-11e9-9d94-04e294824902.jpg)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Mac OS X El Capitan
 - Browser: Safari
 - Browser-Version: 11.1.2

**Weitere Informationen**
Adobe Flash Player ist auf aktuellster Version vorhanden. Bis pietsmiet.de neues Design bekam (Ende August 2019) lief alles hervorragend. Jetzt lassen sich keine Videos mehr abspielen.

**Comment by romanzipp** [comment]
Duplicate of #104
