### ISSUE TITLE
Bug: Seitliche Navbar öffnet sich nicht 

### ISSUE THREAD

**Issue by deejaypro** [PietSmietde/Bugs#108]
**Beschreibe den Fehler**
Die Seitliche Navbar öffnet sich nicht, wenn man vorher die Webseite in der Normalen Darstellung geöffnet hatte (Navbar oben vollständig sichtbar) und das Fenster dann resized, dass der Navbar-Toggler (die drei Striche) zusehen ist.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Webseite in einen Browserfenster öffnen, welches die Navbar vollständig oben anzeigt.
2. Webseite resizen, sodass diese in die Mobile Ansicht überspringt.
Will man nun die Seitliche Navbar über den Button rechts oben öffnen, wird die Webseite nur dunkler und es öffnet sich keine Navbar.

**Erwartetes Verhalten**
Seitliche Navbar öffnet sich.

**Screenshots**
![pietsmiet](https://user-images.githubusercontent.com/18632159/64651067-e6ef5f80-d420-11e9-832c-6ce2c2302a58.PNG)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 1803
 - Browser: Chrome, Edge, Firefox
 - Browser-Version: Chrome (77.0.3865.75), Edge (42.17134.1.0), Firefox (69.0)

**Weitere Informationen**
Öffnet man die Webseite direkt im mobilen Modus, funktioniert alles wie gewollt. Sprich man kann das Fenster resizen wie man will und die Navbar öffnet sich seitlich oder ist oben zu sehen.

**Comment by romanzipp** [comment]
Das ist tatsächlich erwartetes Verhalten. Die Sidebar wird nur gerendert, wenn zur Script Execution der Viewport des Browsers einem Mobilgerät entspricht.
