### ISSUE TITLE
Feature: Beschreibung für PietStream Archiv

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#11]
**Beschreibe das Feature**
Auf der Seite: https://www.pietsmiet.de/videos/channels fehlt eine Beschreibung für den Kanal " PietStream Archiv".  Hier müsste etwas wie "Unsere bisherigen Streams" eingefügt werden.

**Gibt es Alternativen?**
Ja, es so lassen und damit bei allen "Kanälen" eine Beschreibung haben, außer bei "PietStream Archiv"

**Comment by romanzipp** [comment]
Beschreibung wurde ergänzt
