### ISSUE TITLE
Bug: Player wird nicht mehr angezeigt.

### ISSUE THREAD

**Issue by DerMarsl** [PietSmietde/Bugs#110]
**Beschreibe den Fehler**

Der Player wird seit dem 10.09.2019 nicht mehr angezeigt, egal ob Video oder Podcast. Auf dem Handy tritt dieses Problem nicht auf. Bild bzw Kasten in dem das Video abgespielt werden soll ist nicht vorhanden. Kommentare, Likes, Werbung, Tags, sogar die Button zum Teilen und Einstellen sind vorhanden.   

**Screenshots**
![IMG_20190913_170006](https://user-images.githubusercontent.com/55286330/64873169-d15c7e80-d648-11e9-80c1-91d2d79e0045.jpg)

**Desktop**
 - Betriebssystem: Windows 10  Version: 1903
 - Browser: Chrome
 - Browser-Version: 77.0.3865.75

**Comment by DerMarsl** [comment]
![IMG_20190913_162640](https://user-images.githubusercontent.com/55286330/64872863-3d8ab280-d648-11e9-8bb8-ab10cda4f88e.jpg)

**Comment by DerMarsl** [comment]
![IMG_20190913_170006](https://user-images.githubusercontent.com/55286330/64872941-64e17f80-d648-11e9-901d-35d948bd9834.jpg)

Das Bild muss sich also auf dem Rechner befinden und nicht nur auf dem Handy. Dann funktioniert drag and drop natürlich auch ^^

**Comment by romanzipp** [comment]
Kannst du bitte folgendes probieren:

- Erweiterungen deaktivieren
- Die Seite im Inkognito-Fenster öffnen
- Cache löschen (**chrome://settings/clearBrowserData** in die Adresszeile kopieren)

![2019-09-13_17-10-48](https://user-images.githubusercontent.com/11266773/64873504-81ca8280-d649-11e9-81a1-d9856478086c.png)

**Comment by DerMarsl** [comment]
Danke für die schnelle Antwort. Cache löschen hat schon geholfen, manchmal kann es so einfach sein. 
Ich danke dir!
