### ISSUE TITLE
Bug: Login mit Twitter

### ISSUE THREAD

**Issue by Pitstab** [PietSmietde/Bugs#111]
**Beschreibe den Fehler**
Wenn man versucht sich mit Twitter oder Twitch anzumelden auf der Pietsmiet.de dann steht unten Link auf dem Bildschirm "Invalid Data Recieved".

**Reproduktion**
1. Navigiere zu "Mit Twitter" oder "Mit Twitch einloggen"
2. Klicke dann auf den jeweiligen Button.

**Erwartetes Verhalten**
Dann sollte man die App (Twitter) Autorisieren und dann kommt unten Links ein Weiß auf Roter Text der sagt: "Invalid data received from Twitter"
Bei Twitch wird ein Zwei Zeilen Code angezeigt. (Siehe Bild)

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 (1903)
 - Browser: Mozilla Firefox
 - Browser-Version: 69.0 (Quantum)

**Smartphone (bitte die Informationen vervollständigen):**
Beim Smartphone (Honor Play) stürzt der Browser nach versuch sich mit Social Media einzuloggen ab.
Browser: Mozilla Firefox (Ver: 68.1.1)

Und Entschuldigung Roman das ich das einfach so abgesendet habe.
Ich bin zum erstem mal auf GitHub unterwegs.

![Screenshot_2019-09-14 https id twitch tv](https://user-images.githubusercontent.com/55312597/64905825-e0414080-d6dd-11e9-99d2-b246eb4582eb.png)

**Comment by romanzipp** [comment]
Duplicate of #85
