### ISSUE TITLE
Bug: Falsches Feld bei der Eingabe der PLZ (Subscribe-Vorgang)

### ISSUE THREAD

**Issue by HerrDepence** [PietSmietde/Bugs#113]
**Beschreibe den Fehler**
PLZ-Feld lässt keine freie Eingabe zu

**Reproduktion**
Subscribe-Vorgang durchführen und bei der Eingabe der Daten versuchen seine PLZ einzugeben

**Erwartetes Verhalten**
Das PLZ-Feld sollte die freie Eingabe von 5 Zahlen zulassen

**Screenshots**
![image](https://user-images.githubusercontent.com/7407580/64907205-a2e5ae80-d6ef-11e9-9732-ca819caa5656.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Chrome
 - Browser-Version: 76

**Comment by Gameniti** [comment]
Kann ich so nicht reproduzieren. Das einzige was man ändern könnte wäre die Erlaubnis Eingabe von max 5 Ziffern im positiven Bereich, (Im moment kann man so viele Zahlen eingeben wie man möchte und auch im negativen Bereich)

**Comment by HerrDepence** [comment]
Ich habe es jetzt nochmal probiert und jetzt tritt der Fehler nicht mehr auf. Ich weiß nicht was da bei mir nicht ordentlich funktionierte...
