### ISSUE TITLE
Feature: Teile der Entwicklung Open Source gestalten

### ISSUE THREAD

**Issue by Daylien** [PietSmietde/Bugs#114]
**Erstmal ein dickes Danke, für eure tolle Arbeit.**

Wir als Community können euch auch ein wenig Arbeit abnehmen, indem wir uns auch an der Entwicklung beteiligen.

Wie wäre es, kleinere Komponenten der Seite als Open-Source-Projekte zu gestalten. Ihr benutzt im Moment Laravel als (Backend) Framework und Vue.JS für euer Frontend. 
Wieso nicht Frontend relevante Sachen in Repos packen und die Community hilft euch dabei, Features zu implementieren oder Bugs zu fixen. 
*Logisch ist wohl, das ihr keine Geschäftslogik von eurem Backend veröffentlichen (wollt) könnt.*

Es wäre doch für uns alle eine Sache, wo von wir alle Profitieren könnten. Es gibt sicher einige in der Community (inklusive mir) die Lust hätten einen Beitrag für euch zu leisten.

Wir können euch außerdem bei dem Devblog unterstützen, Release notes schreiben, Features tracken etc.

Wie bereits erwähnt ist dies ein Vorschlag und ich würde mich über eine mögliche Antwort sehr freuen. Vielleicht wollen einige hier auch noch ein kleines Feedback geben.

**Comment by MisterMarlu** [comment]
Ich liebe Laravel & VueJS und würde mich da anschließen.
