### ISSUE TITLE
Bug: Werbung auf PS.de trotz PS.de Ultra

### ISSUE THREAD

**Issue by phoenix2210** [PietSmietde/Bugs#115]
**Beschreibe den Fehler**
Ich habe ein laufendes PS.de Ultra Abo und sehe trotzdem Werbung in den Videos

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. PS.de öffnen (eingeloggt sein)
2. Video starten

**Erwartetes Verhalten**
Werbung deaktivieren (Werbefrei Button ist unter dem Video zu sehen)

**Screenshots**
https://imgur.com/a/0csKoWH

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Win 10 Pro
 - Browser: Firefox
 - Browser-Version: 69 (64-bit)

**Weitere Informationen**
/

**Comment by romanzipp** [comment]
Bitte probiere folgendes:

- Seite aktualisieren
- Neu einloggen
- In einem anderen Browser neu einloggen

**Comment by phoenix2210** [comment]
Lief jetzt schon, sry für die vorschnelle Nachricht
