### ISSUE TITLE
Feature: Pietsmiet.de als Progressive Web App

### ISSUE THREAD

**Issue by ghost** [PietSmietde/Bugs#118]
Eventuell habt ihr ja selbst schon drüber nachgedacht aber die Pietsmiet.de als PWA würde bestimmt viele neue Leute öfter auf eure Seite führen und noch dazu könnt ihr eure eigenen Push Notifications verschicken wenn Videos online gehen und müsst nicht auf Youtubes Glockenzeug vertrauen.

Nur als Idee ;D

**Comment by romanzipp** [comment]
Die Seite ist ja bereits eine SPA, der Sprung auf PWA ist natürlich nicht sehr groß.

Mit der Thematik muss ich mich speziell auseinandersetzen, im ersten Anlauf ist das ganze recht komplex. Also.. auf jeden Fall geplant!
