### ISSUE TITLE
Feature: Verbesserte Navbar (Mobile)

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#12]
**Beschreibe das Feature**
Aktuell ist die Navbar auf dem Handy nicht horizontal zentriert. Es ist ein `padding-top` bei dem Hamburger-Menü und dem Text gesetzt. Dies sollte entfernt werden und den Text (Aktuell) "Viggo - das Buch zum Mord jetzt vorbestellen" in einen separaten `div` unter der Navbar gesetzt werden. Für ein moderneres Design sollte wahrscheinlich auch  der Hintergrund vom Hamburger-Menü entfernt werden.

**Gibt es Alternativen?**
Man könnte es auch unter das neueste Video setzen.

**Screenshot**
![navbar3](https://user-images.githubusercontent.com/18743976/52532605-491ba100-2d28-11e9-83d1-688f50402b22.PNG)

**Comment by romanzipp** [comment]
Ist so umgesetzt, demnächst dann gepatcht
