### ISSUE TITLE
Enhancemant: Beliebige Beträge (>1,49€) für Pietsmiet.de Ultra angeben.

### ISSUE THREAD

**Issue by yannic-b** [PietSmietde/Bugs#123]
Lasst uns beliebige Werte über 1,49€ eingeben, damit man auch die Möglichkeit hat ',49' als Kommazahl zu vermeiden oder man auch minimal den Standardbetrag erhöhen kann (2€).

Das mag jetzt eine persönliche Präferenz sein, aber ich bezahle 10x lieber 2,50 als 2,49.

**Comment by romanzipp** [comment]
Das ist eine Businessentscheidung, deshalb würde ich den Vorschlag vorerst schließen und es intern besprechen. Danke für den Impuls!
