### ISSUE TITLE
Bug: Navigation Sidebar erscheint nicht beim Verkleinern des Browserfensters.

### ISSUE THREAD

**Issue by flohuemer** [PietSmietde/Bugs#125]
**Beschreibe den Fehler**
Wird die Seite mit einem Browserfenster dessen Breite größer als 1024px ist aufgerufen und danach verkleinert, so wird die Navigation Sidebar auf der rechten Seite nicht angezeigt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'https://www.pietsmiet.de/' mit einem Browserfenster breiter als 1024px.
2. Verkleinere das Browserfenster auf eine Breite kleiner als 1024px.
3. Klicke auf das Menü Icon in der rechten oberen Ecke.

**Erwartetes Verhalten**
Die Navigation Sidebar öffnet sich nach dem verkleinern des Fensters.

**Desktop:**
 - Betriebssystem: Windows 10 1903
 - Browser: Microsoft Edge Chromium
 - Browser-Version: 78.0.268.3 dev

**Comment by romanzipp** [comment]
Duplicate of #108
