### ISSUE TITLE
Feature: 2FA Sicherheitsschlüssel Unterstützung

### ISSUE THREAD

**Issue by TitusKirch** [PietSmietde/Bugs#126]
**Beschreibe das Feature**
Zusätzlich zu TOTP, wäre es schön, wenn Sicherheitsschlüssel (z.B. Yubikeys) bei der 2FA unterstütz werden.

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Es löst das "Problem", dass 2FA derzeit nur für Leute die TOTP nutzen verfügbar ist.

**Comment by romanzipp** [comment]
Dafür sehe ich momentan keinen Bedarf
