### ISSUE TITLE
Feature: Eigene Kommentare zuerst anzeigen

### ISSUE THREAD

**Issue by ArianMoser** [PietSmietde/Bugs#128]
**Beschreibe das Feature**
Beim Kommentar schreiben auf der Pietsmiet.de ist mir aufgefallen, dass eigene Kommentare nicht als Erstes in der Kommentar-Sektion angezeigt werden. Hier fände ich es intuitiver, wenn eigene Kommentare oder auch Kommentare, welche man kommentiert hat, am Anfang der Kommentar-Sektion angezeigt werden würde. Des Weiteren fände ich es noch gut, wenn es die Möglichkeit gäbe, eigene Kommentare im Nachhinein zu bearbeiten.

**Kurzbeschreibung**
- Eigene Kommentare am Anfang der Kommentar-Sektion
- Beantwortete Kommentare auch zu Beginn
- Kommentare bearbeitbar machen

**Comment by romanzipp** [comment]
Danke für den Vorschlag. Das Feature ist umgesetzt und wird demnächst gepatcht!
