### ISSUE TITLE
Bug: Nicht laden der Website nach dem Öffnen eines Videos, Newspage, etc.

### ISSUE THREAD

**Issue by MaggiMagie** [PietSmietde/Bugs#129]
**Beschreibung des Fehlers**
Manchmal passiert es, dass die Seiten bzw der Seiten Inhalt nicht Läd. Vorallem wenn man mehrere aufeinmal Tabs läd. Kann natürlich sein, dass das zur Spam-Verminderung ist. ^^

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'https://www.pietsmiet.de/videos'
2. Klicke auf 'beliebege Anzahl von Videos' (New Tab)

Passiert auch wenn man die Videos normal öffnet. aber am öftesten passiert der Bug wenn man >3 videos hintereinaner öffnet.

**Desktop
 - Betriebssystem: [Windows]
 - Browser: [Chrome]
- Version: 77.0.3865.75

**Smartphone
 - Gerät: [Xiaomi MiPhone 6]
 - Betriebssystem: [z.B. Android Oreo]
 - Browser: [Chrome, Opera]
 - Version: 77.0.3865.73

**Comment by romanzipp** [comment]
Ja, wir haben ein s.g. Rate-Limit drin, sodass nur eine bestimmt Anzahl an Anfragen pro Zeitfenster gemacht werden dürfen. Das Limit sollte bei normaler Nutzung nicht erreicht werden.
Sollte es aber dennoch passieren, habe ich eine Fehlermeldung hinzugefügt, die darüber Auskunft gibt.
