### ISSUE TITLE
Feature: Alte Upload-Pläne nicht im Newsfeed anzeigen

### ISSUE THREAD

**Issue by Yekt** [PietSmietde/Bugs#131]
**Beschreibe das Feature**
Nichts ist älter als ein Upload-Plan von gestern.
Es wäre sinnvoll im Newsfeed, der auf der rechten Seite der Website angezeigt wird, immer nur **ausschließlich** den aktuellsten Upload-Plan (aka. den von Heute) anzeigen zu lassen.
Die restlichen 4 "News-Slots" sollten mit den aktuellsten Artikeln gefüllt werden.

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Aktuell sind immer 4 oder sogar 5 der Slots mit Upload-Plänen gefüllt. Damit gehen die Artikel, die ihr für die Pietsmiet.de schreibt, ein bisschen verloren. Was natürlich äußerst schade ist.

**Comment by MartinV96** [comment]
+1
