### ISSUE TITLE
Bug: Schreibfehler beim ´Vorschlag einreichen´-Button

### ISSUE THREAD

**Issue by alinaLOL** [PietSmietde/Bugs#132]
**Beschreibe den Fehler**
Anstatt Vorschlag einreichen steht auf dem Button Vorchlag einreichen, just a typo

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu '...'
2. Klicke auf '....'

**Erwartetes Verhalten**
bitte korigieren

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10
 - Browser:  Chrome
 - Browser-Version: idk

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: [z.B. iPhone6]
 - Betriebssystem: [z.B. iOS8.1]
 - Browser: [z.B. stock browser, Safari]
 - Browser-Version: [z.B. 22]

**Weitere Informationen**
Weiter Informationen über das Problem, wenn vorhanden.

**Comment by flohuemer** [comment]
Duplicate of #116
