### ISSUE TITLE
Feature: Längere Abos / Weniger Gebühren für euch

### ISSUE THREAD

**Issue by dayvoo** [PietSmietde/Bugs#133]
(Übernommen aus den Youtube Kommentaren)

Es wäre eine Idee 3/6/12 monatige Abos anzubieten (falls rentabel mit einem kleinen % Rabatt für den Nutzer).

Der Nutzer würde ein wenig sparen durch den Rabatt & ihr würdet ein wenig an PayPal Gebühren einsparen da dann etwas größere Summen überwiesen werden => Win-Win-Situation

**Comment by romanzipp** [comment]
Diese Möglichkeit haben wir intern natürlich diskutiert, aber uns für die monatliche Laufzeit entschieden.
