### ISSUE TITLE
Bug: Keine Eingabefelder zum Registrieren

### ISSUE THREAD

**Issue by Argon42043** [PietSmietde/Bugs#134]
**Beschreibe den Fehler**
Wenn ich mich auf dem Handy bei pietsmiet.de registrieren möchte werden mir keine Eingabefelder angezeigt. Screenshot beigelegt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'Menü'
2. Klicke auf 'Registrieren'

**Erwartetes Verhalten**
Dass die Eingabefelder für die Daten angezeigt werden.

**Screenshots**
![Pietsmiet_de registrieren fehler](https://user-images.githubusercontent.com/55322980/64910021-fd443680-d712-11e9-8123-a3befaa13d9b.jpeg)

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: Samsung Galaxy A8 (2018)
 - Betriebssystem: Android 9
 - Browser: Chrome
 - Browser-Version: 77.0.3865.73

**Weitere Informationen**
Als ich die Seite ca. 10 min. später neu geladen habe wurden die Eingabefelder ordnungsgemäß angezeigt

**Comment by romanzipp** [comment]
Ist der Fehler reproduzierbar? Scheint, als wärst du in einer ungünstigen Sekunde auf der Seite gewesen, als gerade ein Patch eingespielt wurde.

**Comment by Argon42043** [comment]
Ich habs ein paar mal probiert den Fehler zu reproduzieren aber es geht
nicht mehr. Jetzt funktioniert alles wieder so wie es soll.
Trotzdem Danke für den Support.

Roman Zipp <notifications@github.com> schrieb am Sa., 14. Sep. 2019, 21:53:
