### ISSUE TITLE
Bug: 2-Faktor Authentifizierung

### ISSUE THREAD

**Issue by BL4M3R** [PietSmietde/Bugs#135]
**Beschreibe den Fehler**
Wollte das einrichten mit Google Authenticator, habe dann den Barcode gescannt und auf weiter geklickt, dort stand aber als Fehlermeldung das der Code falsch war. Habe dann den Eintrag in der App gelöscht und wollte zurück gehen auf der Seite, aber die Authentifizierung war dann eingerichtet. Kann jetzt die Authentifizierung nicht mehr löschen und mich nicht mehr einloggen.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Aufs Profil
2. Dann auf 2-Faktor
3. Und dann versuchen es einzurichten

**Erwartetes Verhalten**
Ich habe erwartet das es funktioniert und nachdem es nicht ging, habe ich erwartet das es nicht funktioniert hat oder ich es neu probieren kann.
**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: [Windows 10]
 - Browser: [Chrome]
 - Browser-Version: [Aktuellste]

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: [X]
 - Betriebssystem: [X]
 - Browser: [X]
 - Browser-Version: [X]

**Weitere Informationen**
Weiter Informationen über das Problem, wenn vorhanden.

**Comment by TheRealFlori** [comment]
Same here, 

gleicher Browser, Betriebssystem

**Comment by Zwiebelscheibe** [comment]
Dito, allerdings mit Firefox. In der Authenticator App scheint alles gewöhnlich.

**Comment by romanzipp** [comment]
Der Fehler sollte behoben sein. Jeder, der die 2-Faktor Authentifizierung nicht mehr entfernen kann soll bitte eine Mail an **support@pietsmiet.de** schreiben. Wir klären jeden Fall einzeln.
