### ISSUE TITLE
Feature: Anpassungs-Optionen für Werbung

### ISSUE THREAD

**Issue by teeton** [PietSmietde/Bugs#138]
Auch wenn das ganze natürlich erst einmal negativ für euch ist, würde ich vorschlagen die Werbung durch die Nutzer anpassen zu lassen.

Was ich damit meine:
- Art der angezeigten Werbung bestimmen (Pre-Roll, Mid-Roll, nur Banner, ...)
- Häufigkeit der Werbung bestimmen (bezieht sich auf Video-Ads, am besten einen Regler von 1 bis 10)

Ich für meinen Teil muss zugeben, dass ich auch AdBlock verwende. Das tue ich aber bspw. nicht aufgrund der Banner - welche ich nicht als störend betrachte - sondern wegen der Video-Werbung.
Es nervt einfach, alle 5-10 Minuten die exakt gleiche Werbung immer und immer wieder sehen zu müssen.
Würde ich aber z.B. die Video-Werbung auf eine Pre-Roll begrenzen (oder die Häufigkeit zumindest halbieren), und die Banner weiter normal lassen können, hätte ich keinen Grund den Ad-Block anzuschmeißen.

Ganz ähnlich macht es auch die Animi-Plattform Proxer, und dort hat eben diese Einstellungsmöglichkeit mich auch schon dazu bewegt, ein Leben ohne Ad-Block zu führen :)

Sollte sich PietSmiet.de dann allerdings nicht mehr rechnen, was ja auch verständlich sein kann, lasst es mich bitte erst recht wissen, dann wechsel ich lieber zu YouTube, um euch nicht unnötig zu belasten.

**Comment by romanzipp** [comment]
Das ist eine Businessentscheidung, deshalb würde ich den Vorschlag vorerst schließen und es intern besprechen. Danke für den Impuls!
