### ISSUE TITLE
Schwerwiegender Bug: Fehlerhaftes Feedback zum 2FA Status bei Aktivierung.

### ISSUE THREAD

**Issue by robochef3** [PietSmietde/Bugs#139]
**Beschreibung:**
Ich wollte 2FA aktivieren, scanne den QR Code bzw. gebe das Secret manuell ein, bekomme einen Fehler ("invalid code" oder so Ähnlich, in Rot unten Links) und lösche dann den Eintrag aus dem Google Authenticator.
Kurz darauf wil ich es noch einmal probieren und bekomme angezeigt dass 2FA an ist.

> **Nun steh ich da ohne Recovery Codes oder Secret.**

Der betreffende Account heißt "robochef".
Für alles Weitere bin ich unter 2fa-issue@guhlmann.com zu erreichen.
Danke im Voraus :)

**Reproduktion:**
Versuche 2FA zu Aktivieren. Duh.

**Erwartetes Verhalten:**
Feedback, dass die 2FA nun aktiviert ist.
Inkl. entsprechender Recovery Codes u.ä.

**Screenshots:**
Im Nachhinein ist mir aufgefallen dass ich für jeden Versuch eine "Account-Benachrichtigung" erhalten habe: https://imgur.com/a/MRrOM81

**Desktop:**
 - Betriebssystem: Windows
 - Browser: Chrome
 - Browser-Version: 77.0.3865.75 (Offizieller Build) (64-Bit)

**Weitere Informationen**
Keine (aktivierten) Add-Ons.
Siehe: #135

**Comment by Deister2010** [comment]
Habe den gleichen Fehler auch bei meinem Account.

**Comment by Zwiebelscheibe** [comment]
Selber Fehler bei mir allerdings mit Firefox womit der Browser ausgeschlossen werden kann.

Habe nun herrausgefunden das der Fehler "invalide code" zwar am Bildschirm erscheint, aber die Authentifikation dennoch erfolgreich stattgefunden hat.

Das Problem welches aktuell bei mir Auftritt ist, dass wenn ich mich an meinem Handy einloggen möchte erscheint nun wie erwartet auch die 2FA. Beim Versuch jetzt aber den 6-Stelligen Code einzugeben erscheint jedesmal "2-Faktor Authentifizierung fehlgeschlagen". Bin somit von meinem Account ausgesperrt. 

Da ich an meinem PC noch angemeldet bin, habe ich auch schon versucht die 2FA wieder zu deaktivieren, hierbei bekomm ich die selbe Fehlermeldung "2-Faktor Authentifizierung fehlgeschlagen".

Hier noch ein zweiter Eintrag zu dem selbem Thema https://github.com/PietSmietde/Bugs/issues/139

**Comment by Zwiebelscheibe** [comment]
#135

**Comment by idnovic** [comment]
selber Fehler. 

Auch fehlen recovery keys. Diese werden genutzt falls der 2fa Generator mal nicht zur Hand sein sollte.

**Comment by romanzipp** [comment]
Der Fehler sollte behoben sein. Jeder, der die 2-Faktor Authentifizierung nicht mehr entfernen kann soll bitte eine Mail an **support@pietsmiet.de** schreiben. Wir klären jeden Fall einzeln.
