### ISSUE TITLE
Bug: Kreise vom Toggle der Quelle haben eine Animation

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#14]
**Beschreibe den Fehler**
Wenn man das `modal` von der `Quelle` ausblendet, sieht man wie die Kreise vom Toggle eine Animation haben.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/videos/pietsmiet-tv/51394-quicky-react-3
2. Klicke auf `Quelle`
3. Klicke irgendwo hin, um das Fenster auszublenden.

**Erwartetes Verhalten**
Sollte keine Animation haben, wenn man es ausblendet.

**Desktop (bitte die Informationen vervollständigen):**
* Betriebssystem: MacOS 10.14.3 (18D109)
* Browser: Safari
* Browser-Version: Version 12.0.3 (14606.4.5)

**Comment by derLesh** [comment]
Ich denke mal die Lösung liegt in einer einzigen Zeile:
https://www.pietsmiet.de/css/app.css?id=438a95c37ed95861e5e2

``` 
.switch label:before {
    position: absolute;
    top: 0;
    bottom: 0;
    width: 1.5rem;
    margin-left: -.25rem;
    right: 50%;
    content: "";
    transition: all .2s ease-in;
}
```

Damit diese Animation nicht mehr vorkommt muss einfach nur ` transition: all .2s ease-in; ` entfernt werden.

**Comment by romanzipp** [comment]
Entfernt habe ich die Zeile nicht, aber den selector der transition auf die Elementposition anstatt alle Eigenschaften reduziert.
Wird demnächst gepatcht.
