### ISSUE TITLE
Bug: Up/Downvote Button

### ISSUE THREAD

**Issue by Helios2110PS** [PietSmietde/Bugs#140]
**Beschreibe den Fehler**
Wenn man beim Abstimmen zwischen Up- und Downvote wechselt, passen die Zahlen nicht mehr

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Auf den Community-Tab gehen und dann auf Vorschläge
2. einen beliebigen Kommentar up-, down und wieder upvoten

**Erwartetes Verhalten**
Die Zahl nach dem ersten Upvote stimmt nicht mit der Zahl nach dem erneuten Upvote überein (Bsp: einen Vorschlag mit 80 Upvotes; nach dem Upvote: 81; nach dem Downvote: 79; nach dem Upvote: 83)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Firefox Quantum
 - Browser-Version: 69.0 (32-Bit)

**Weitere Informationen**
Weiter Informationen über das Problem, wenn vorhanden.

**Comment by romanzipp** [comment]
Duplicate of #122
