### ISSUE TITLE
Fehlerhafte Verlinkung: Unterhalb des Vorschlag-Titels

### ISSUE THREAD

**Issue by wurffl** [PietSmietde/Bugs#141]
**Beschreibung**
In der Übersicht eines Vorschlages verlinkt "Vorschläge" unterhalb des Vorschlag-Titels auf 'https://www.pietsmiet.de/community/ultras'

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'Community'
2. Klicke auf 'Vorschläge'
3. Klicke auf einen Vorschlag
4. Klicke auf 'Vorschläge' unterhalb des Vorschlag-Titels

**Erwartetes Verhalten**
Die Seite 'https://www.pietsmiet.de/community/suggestions' sollte aufgerufen werden

**Screenshots**
https://i.imgur.com/Qkd5hDR.jpg

**Desktop:**
 - Betriebssystem: Windows 10
 - Browser: Opera
 - Browser-Version: 63.0.3368.71

**Comment by romanzipp** [comment]
Danke für die Meldung. Ist im nächsten Patch gefixt.
