### ISSUE TITLE
Bug: Bestätigungs Mail wird nicht gesendet

### ISSUE THREAD

**Issue by TheRealSchmello** [PietSmietde/Bugs#142]
Die Bestätigungs Mail wird nicht gesendet, egal wie oft man drauf klickt.
Auch im Spam o.ä. nichts vorhanden. Bitte um Hilfe, kann mich nicht verifizieren...
Somit leider auch nicht Supporten...

 Neue Bestätigungs Mail senden im Abschnitt Einstellungen o.ä.
**Erwartetes Verhalten**
Eine Beschreibung des zu erwartenden Verhaltens / Ergebnisses.

Lapi mit Firefox, Win 10 glaube ich.

Huawei P20 Pro 
Chrome

Kann mich bis das Problem behoben ist leider nicht Final anmelden und die Seite nutzen.

Vielen Dank im vorraus für die Hilfe :)

**Comment by masltopf** [comment]
same here, würde sehr gerne ein Abo abschließen. Werde aber daran gehindert, da mein Account plötzlich nicht mehr bestätigt ist und beim Klick auf erneut senden nichts passiert.
