### ISSUE TITLE
Bug: Abo kündigen / verlängern erfolgreich, trotzdem Fehler

### ISSUE THREAD

**Issue by dayvoo** [PietSmietde/Bugs#143]
Wenn ich das Abo verlängern / kündigen möchte bekomme ich in beiden Fällen eine Fehlermeldung vom Server (500 Error), aber wenn ich die Seite aktualisiere wurde das Abo trotzdem erfolgreich verlängert / gekündigt.

Bei #139 liegt das selbe Problem vor, nur bei der 2FA. Dieses Problem kann ich so bestätigen, ich bekomme die selbe Fehlermeldung dort ebenfalls.

Fehlermeldung von der Netzwerkanalyse:
_500 Internal Server Error_
```
{
    "message": "Server Error",
    "success": false
}
```

**Desktop:**
- Betriebssystem: Windows
- Browser: Firefox
- Browser-Version: 69.0 (64 Bit)

**Comment by romanzipp** [comment]
Fehler sollte behoben sein
