### ISSUE TITLE
Bug: Dark Mode und 2FA Einrichtung vertragen sich nicht

### ISSUE THREAD

**Issue by dayvoo** [PietSmietde/Bugs#144]
Wenn man den Dark Mode aktiviert hat und 2FA einrichten möchte, funktioniert das Scannen des QR Codes (zumindest bei meiner Monitor <-> Smartphone Kamera Kombination) nicht.

**Mögliche Lösung**
Ein weißer 3px Rahmen um den QR Code (193,95px * 193,95px) hat bei mir das Problem gelöst.
`border: 3px solid #fff;`

**Desktop**
 - Betriebssystem: Windows
 - Browser: Firefox
 - Browser-Version: 69.0 (64 Bit)

**Comment by romanzipp** [comment]
Danke für die Meldung. Ist im nächsten Patch behoben.
