### ISSUE TITLE
Bug: Link zur Shopseite von Stühlen nicht gefunden

### ISSUE THREAD

**Issue by Bufkin** [PietSmietde/Bugs#145]
Der Link zum Shop für Stühle funktioniert nicht. 

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu Menü 
2. Klicke auf Stühle 

**Erwartetes Verhalten**
Weiterleitung zum Shop. 

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: OnePlus 3T
 - Betriebssystem: LineageOS 16
 - Browser: Firefox Nightly
 - Browser-Version: 68.2a1

**Comment by romanzipp** [comment]
Ist im nächsten Patch gefixt
