### ISSUE TITLE
Bug: Anzeige zum Fortfahren von Videos im Dark Mode unerkennbar

### ISSUE THREAD

**Issue by wurffl** [PietSmietde/Bugs#147]
**Beschreibe den Fehler**
Die Farbe des Hintergrundfeldes und des Textes der Frage ob man das Video ab dem Zeitpunkt weiter sehen möchte bei dem man aufgehört hat ist die gleiche.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Klicke auf ein Video das du bereits angefangen hattest
2. Navigiere zu dem Feld unterhalb des Videos

**Erwartetes Verhalten**
Die Hintergrundfarbe des Textfeldes sollte dunkel sein.

**Screenshots**
https://i.imgur.com/JmILUJV.jpg

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Opera
 - Browser-Version: 63.0.3368.88

**Comment by romanzipp** [comment]
Danke für die Meldung. Ist im nächsten Patch behoben
