### ISSUE TITLE
Bug: Email Versendung

### ISSUE THREAD

**Issue by wrngwrld** [PietSmietde/Bugs#149]
**Beschreibe den Fehler**
Bei der Email Verifikation wird keine Email versendet

**Reproduktion**
Bei den Profileinstellungen auf hier eine neue Bestätigung anfordern klicken passiert nichts

**Erwartetes Verhalten**
Eine Email wird versendet

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.

**Comment by romanzipp** [comment]
Duplicate of #142
