### ISSUE TITLE
Bug: Scrollen über Video-Player verändert lautstarke

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#15]
**Beschreibe den Fehler**
Wenn man über den Video-Player scrollt, dann verändert sich die Lautstärke. Dies hat zur Folge, dass wenn man mit dem Mauszeiger durch Zufall auf den Player zeigt, während man scrollt, gefühlt taub wird. :D

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu irgendeinem Video
2. Scrolle über das Video

**Erwartetes Verhalten**
Lautstärke und Scroll-Verhalten sollte unverändert sein.

**Desktop (bitte die Informationen vervollständigen):**
* Betriebssystem: MacOS 10.14.3 (18D109)
* Browser: Safari
* Browser-Version: Version 12.0.3 (14606.4.5)

**Comment by romanzipp** [comment]
Auch der Fix, ist bereits in der Pipeline. Ich denke die kleinen Fixes werde ich vor dem Review live stellen.
Referenz #9
