### ISSUE TITLE
Bug: Videobild fehlt und Video bricht ab

### ISSUE THREAD

**Issue by AdmAlex** [PietSmietde/Bugs#151]
**Beschreibung**
Ich habe den Anno 1800 Hype! Stream mir angesehen und auf einmal wurde das Bild grau mit "Something went wrong" und einer Blitzwolke. Wahr wohl ein Fehler bei der Datenübertragung. Das seltsame war aber, dass das Video noch ca 2 Minuten weiter lief (aber halt nur der Ton).
Vielleicht war das nur ein kleiner Fehler bei mir, aber nach dem Neuladen ging es immer noch nicht. Beim 2. Neuladen dann auf einmal wieder, aber nach einem kurzen Moment wieder nicht.
Unten steht der Link zu dem Video, welches ich meine.

**Link**
https://www.pietsmiet.de/videos/53086-anno-1800-hype-full-gameplay-v411961666-20190416mp4?channel=44-pietstream

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/15948391/64922626-933e9680-d7d1-11e9-985d-756a6119027b.PNG)

**Desktop**
 - Betriebssystem: Windows 7
 - Browser: Chrome 
 - Browser-Version: 75.0.3770.90

Ich hoffe, dass das euch hilft.

**Comment by dominovox** [comment]
Problem wurde soweit behoben, lag an der Störung.
