### ISSUE TITLE
Social Login geht nicht mehr

### ISSUE THREAD

**Issue by FelixFlex02** [PietSmietde/Bugs#152]
Man kann beim Social Login sich nicht mehr mit Google oder Twitter oder so einloggen. Es steht nur: "Mit dem Login über ein soziales Netzwerk erkennst du die Nutzungsbedingungen und Datenschutzerklärung als gelesen & akzeptiert." Aber man kann gar nichts auswählen.

**Comment by romanzipp** [comment]
Auf welcher Seite ist der Fehler aufgetreten?
Mit welchem Gerät & Browser hast du die Website aufgerufen?

**Comment by FelixFlex02** [comment]
Geht jetzt wieder. Alles gut.
