### ISSUE TITLE
Bug: E-Mail Bestätigung nicht gesendet

### ISSUE THREAD

**Issue by Jeany0104** [PietSmietde/Bugs#153]
Bin mir nicht sicher ob es ein Bug ist, aber ich erhalte keine Mail um meinen acc zu verifizieren.

Habe den Posteingang mehrfach geprüft (auch Spam), Mailadresse stimmt und die Bestätigungsmail habe ich auch mehrfach angefordert. Bisher leider ohne Erfolg.

Ich hoffe, dass ich bald Schnittchen verdienen kann :)

LG von der Ostsee <3

**Comment by romanzipp** [comment]
Duplicate of #142
