### ISSUE TITLE
Bug: Vorschlag einreichen - kein Hinweis bei Nichtanmeldung

### ISSUE THREAD

**Issue by AlienPlayer123** [PietSmietde/Bugs#154]
**Beschreibe den Fehler**
Wenn man einen Vorschlag einreicht und nicht angemeldet ist, bekommt man keinen Hinweis darauf.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Nicht anmelden
2. Vorschlag einreichen

**Erwartetes Verhalten**
Bei Klick auf Vorschlag einreichen passiert eben nichts.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10
 - Browser: Firefox
 - Browser-Version: 69.0

**Comment by romanzipp** [comment]
Danke für die Meldung. Ist im nächsten Patch gefixt.
