### ISSUE TITLE
Bug: Login mit Twitter nicht möglich

### ISSUE THREAD

**Issue by darc007** [PietSmietde/Bugs#155]
Twitter-Login geht nicht. Man wird zwar zur Bestätigung auf Twitter weitergeleitet, jedoch wird nach Abschluss auf pietsmiet.de angezeigt, dass die Daten von Twitter invalide sind.

**Desktop:**
 - Windows 10
 - Chrome
 -Version 76

**Comment by manuel-st** [comment]
Duplikat: #152

**Comment by romanzipp** [comment]
Duplicate of #85
