### ISSUE TITLE
Bug: Footer überlappt Cookie-Meldung

### ISSUE THREAD

**Issue by manuel-st** [PietSmietde/Bugs#156]
**Beschreibe den Fehler**
Die Wolkenform (der footer-separator) überlappt die Cookie-Meldung.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. pietsmiet.de aufrufen
2. Runterscrollen

**Erwartetes Verhalten**
Die Cookie-Benachrichtigung überdeckt den Footer

**Screenshots**
![0000](https://user-images.githubusercontent.com/36520836/64939028-232b2180-d860-11e9-9121-b0453f727c3c.png)

**Desktop**
 - Betriebssystem: Ubuntu
 - Browser: Firefox
 - Browser-Version: 69.0

**Comment by romanzipp** [comment]
Ist im nächsten Patch gefixt
