### ISSUE TITLE
Feature: "Neu laden" Button von unten nach oben verschieben

### ISSUE THREAD

**Issue by derLesh** [pietsmietde/Bugs#16]
**Beschreibe das Feature**
Den "Neu laden" Button von den Kommentaren von unten nach oben verschieben

**Weitere Informationen**
Durch die neue Platzierung muss man nicht immer nach unten scrollen, damit man nur die Kommentare aktualisieren kann

**Comment by romanzipp** [comment]
Umgesetzt, demnächst verfügbar
