### ISSUE TITLE
Bug:  Login Fenster

### ISSUE THREAD

**Issue by MoritzJDR** [PietSmietde/Bugs#160]
**Beschreibe den Fehler**
Beim Loginfenster fehlen sämtliche Eingabefelder für z.B. Passwort bis man die Seite 3x neu geladen hat, dann gehts

**Reproduktion**
Auf Login drücken via Kommentarfunktion

**Erwartetes Verhalten**
Dass man sich normal Einloggen kann

**Screenshots**
![Piets](https://user-images.githubusercontent.com/52359517/64970890-fe0dd180-d8a6-11e9-8214-ea12267b18fd.jpg)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Win10 64Bit Pro
 - Browser: Firefox 
 - Browser-Version: 69.0 (64-Bit)

**Weitere Informationen**
Nach wiederholtem F5 (Neuladen) gehts irgendwann wieder, tritt aber seit 2 Tagen öfters auf, daher der Report

**Comment by romanzipp** [comment]
Habe den Fehler gefunden, wird zeitnah behoben

**Comment by romanzipp** [comment]
See also #160
