### ISSUE TITLE
Feature:  Ultras Sotierung

### ISSUE THREAD

**Issue by Meikel184** [PietSmietde/Bugs#162]
**Beschreibe das Feature**
Einfach das die Ultra liste sotiert ist nach den alphabet und mann villeicht auch dann bestimmte users suchen kann ist etwas kleines aber feines :)

**Comment by romanzipp** [comment]
Wir haben aktuell eine interne Sortierung, die wir so beibehalten möchten. Trotzdem danke für die Anmerkung
