### ISSUE TITLE
Feature: Benutzerfreundlichkeit vom „Du folgst“ Tab

### ISSUE THREAD

**Issue by leonard2901** [PietSmietde/Bugs#168]
**Beschreibung**
Es wäre meiner Ansicht nach hilfreich, wenn der (leere)„Du Folgst“ Bereich einen Hilfetext bekommen würde, der beschreibt, wie man dort etwas angezeigt bekommt.
Mir war zunächst nicht klar, dass die Videos auf der Webseite auch in verschiedene Kanäle unterteilt sind und man diese separat abonnieren kann. Oder dass man auch einzelnen Playlists, Personen etc. folgen kann.
Hier ein Vorschlag wie ich mir das vorstellen könnte. „Kanäle“ könnte dann z.B. auf die Kanalübersicht verlinken.

![IMG_0263](https://user-images.githubusercontent.com/25386154/65040642-2522dc80-d955-11e9-9433-f58627f02a03.jpeg)

Zudem ist die Benennung des Bereiches nicht ganz konsistent. Wenn man auf das Burgermenü klickt, hat der Butten für den Bereich den Titel „Abo-Box“. Hier könnte man sich eventuell für eine einheitliche Benennung entscheiden.

![IMG_0264](https://user-images.githubusercontent.com/25386154/65040643-2522dc80-d955-11e9-8b25-a0e2efd0f584.jpeg)

**Comment by romanzipp** [comment]
Danke für die Meldung. Beide Sachen wurden behoben
