### ISSUE TITLE
Feature: Chromecast Support für den Video Player

### ISSUE THREAD

**Issue by AntiGuide** [PietSmietde/Bugs#169]
Es wäre schön die Möglichkeit zu haben Videos der PietSmiet.de auf dem Chromecast schauen zu können.

Alternativ könnte man das ganze erst mit dem Release der App abbilden und die dann zu casten voraussetzen. Gerade falls diese aber als WebApp geplant ist, müsste man sich sowieso die selben Gedanken machen.

Da ihr ja soweit ich weiß PlayKit JS verwendet könntet ihr ja das passende [Plugin](https://github.com/kaltura/playkit-js-cast-sender) verwenden und hättet damit (hoffentlich) kaum Arbeit.

Vielen Dank für die gute Arbeit bisher!

**Comment by romanzipp** [comment]
Wir haben Chromecast Integration schon auf dem Schirm und arbeiten daran. Leider ist es nicht einfach das Plugin, was uns fehlt, sondern tiefere Probleme, die schwer zu debuggen sind.

Wann die Integration funktionerend ausgerollt wird, können wir daher nicht sagen - auch wenn wir es gerne wollen.

**Comment by romanzipp** [comment]
Wenn du möchtest, kannst du mich zu der Thematik gerne auf Discord anschreiben: **HerrAusragend#0001**

**Comment by AntiGuide** [comment]
Ich fürchte ich könnte da wenig helfen. Ich bin fast ausschließlich C# Dev. Aber wenn ihr dran seid ist das doch schonmal ein super Anfang! Es wäre halt sau komfortabel, für die Funktion keine extra App verwenden zu müssen. Danke für eure Arbeit! :slightly_smiling_face:
