### ISSUE TITLE
Bug: Werbung trotz Snob Abo 

### ISSUE THREAD

**Issue by TheRealSchmello** [PietSmietde/Bugs#171]
Es gibt trotz allem Werbung, in Form von zb Bannern auf der Seite.
Aktives Snob Abo natürlich vorhanden.

Problem trat auf Win 8.1, Firefox

**Comment by romanzipp** [comment]
Ich sehe, du hast den Issue geschlossen. Was hat das Problem bei dir behoben?

**Comment by TheRealSchmello** [comment]
Komischerweise, eine erneute Aktualisierung der Seite, die aber zuvor schon mehrmals durchgeführt wurde.

War dann auf einmal nach erstellen des Tickets hier weg.

**Comment by dayvoo** [comment]
Ich denke es wäre hier interessant zu wissen, ob es eventuell an der Rückmeldezeit von dem Zahlungsanbieter liegt.

Soweit ich mich erinnern kann war das bei mir so, dass es 5-10 Minuten gedauert hat bis die PayPal Zahlung richtig angekommen ist und das Abo bei mir gesetzt wurde. Da ich aber eh einen Adblocker habe, kann ich da keine Rückmeldung zur Werbung geben - sorry :D
