### ISSUE TITLE
Bug: Werbung verdeckt Menü und andere Elemente

### ISSUE THREAD

**Issue by Gregorie** [PietSmietde/Bugs#173]
**Beschreibe den Fehler**
Werbung überdeckt Menü und Header.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/following
2. Scrolle zur Werbung
3. Klicke auf Menü

**Erwartetes Verhalten**
Werbung im Hintergrund/nicht über Menü ....

**Screenshots**
![Screenshot_20190918-185429_Chrome](https://user-images.githubusercontent.com/5672294/65169714-65fb1e00-da47-11e9-9015-ec0f3938ec81.jpg)
![Screenshot_20190918-185421_Chrome](https://user-images.githubusercontent.com/5672294/65169715-6693b480-da47-11e9-8452-53d1959f8a3e.jpg)

**Smartphone:**
 - Gerät: Samsung Galaxy S8
 - Betriebssystem: Android 9.0
 - Browser: Chrome
 - Browser-Version: 76.0.3809.132
 - Auflösung: 1480x720

**Comment by Gregorie** [comment]
Hängt auch mit der Werbung zusammen. Habe jetzt eine andere, die nicht zur beschriebenen Überlappung führt

**Comment by R3CK3RTH** [comment]
Bei mir tritt der Bug auch auf, aber nur auf der Startseite. Auf allen anderen setzen tritt der Bug nicht auf, auch nicht bei gleicher Werbung.

**Comment by burny88** [comment]
Gleicher Fehler direkt auf der Startseite
