### ISSUE TITLE
Feature: Später ansehen

### ISSUE THREAD

**Issue by AntiGuide** [PietSmietde/Bugs#175]
## Feature-Beschreibung
Es wäre klasse eine Möglichkeit zu haben sich wie bei YouTube eine kleine private Playlist zusammen stellen zu können.

## Szenario
Ich gehe häufig durch meine YouTube Videos und markiere mir alles was ich sehen möchte. Dann sortiere ich mir das ganze und schaue es von vorne nach hinten durch. Was ich nicht schaffe bleibt in der Liste und wird an einem anderen Tag geschaut. Die Möglichkeit zu haben das auf der PietSmiet.de tun zu können würde mir die tägliche Nutzung versüßen ;)

## Lösungsvorschlag UI
Gelöst werden könnte es ähnlich zu YouTube mit einem Symbol das am Thumbnail heftet, über ein Hamburger-/Kontextmenü oder im Videoscreen.
<details><summary><b>Beispiele</b></summary>

![grafik](https://user-images.githubusercontent.com/22414734/65263770-8b525f80-db0d-11e9-92ec-6f2af6b4582c.png)
![grafik](https://user-images.githubusercontent.com/22414734/65263909-d0769180-db0d-11e9-9492-7da4818945a5.png)
![grafik](https://user-images.githubusercontent.com/22414734/65264031-0d428880-db0e-11e9-8eef-d608bafdf1c7.png)
</details>

**Comment by romanzipp** [comment]
Feature ist live
