### ISSUE TITLE
Feature: Maus verschwindet im Vollbild

### ISSUE THREAD

**Issue by ambosss** [PietSmietde/Bugs#177]
**Beschreibe das Feature**
Der Mauszeiger verschwindet im Vollbild zusammen mit der Menüleiste.

**Gibt es Alternativen?**
Nein da die Maus beim Videos schauen nervt.

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Nicht Vorhanden

**Weitere Informationen**
Nicht Vorhanden

**Comment by romanzipp** [comment]
Duplicate of #150
