### ISSUE TITLE
Bug: Safari 13 spielt keine Videos mehr ab

### ISSUE THREAD

**Issue by dkeu** [PietSmietde/Bugs#178]
Nach dem Update auf Safari 13, werden die Videos nicht mehr gestartet. Am iPhone funktioniert es, aber am MacBook laden die Videos nicht mehr.

Pure Safari, ohne irgendwelche Addons oder ähnliches.

**Comment by dkeu** [comment]
Hat Samstag/Sonntag nicht funktioniert, heute funktioniert es wieder.

Wenn ich das richtig gesehen habe, hat das CDN nicht geantwortet. Es wurde alle zwei Sekunde eine neue Anfrage gestellt, die aber nie ausgeliefert wurde und somit startete weder Video, noch Werbung, weil es im Anfrage-Loop festhing. Vielleicht war sogar die Werbung schuld, weil die fehlende Auslieferung den Ladevorgang vom Video geblockt hat. So genau habe ich mir das nicht angesehen.

Jedenfalls scheint, wenn ihr nicht heimlich daran gearbeitet habt, nicht das Update auf Safari 13 Schuld gewesen zu sein. Heute läuft es nämlich wieder.

**Comment by romanzipp** [comment]
Habe es eben auch nochmal mit der neusten Safari Version testen lassen und es scheint zu funktionieren. Möglicherweise wirklich ein vorübergehendes Netzwerkproblem
