### ISSUE TITLE
Bug: Video nicht verfügbar

### ISSUE THREAD

**Issue by dkeu** [PietSmietde/Bugs#179]
Video: 
https://www.pietsmiet.de/videos/25130-for-the-king-6?playlist=863-for-the-king

Player gibt Error aus:
»Something went wrong«

**Comment by dkeu** [comment]
Jep. Scheint nur was mit der Verlinkung oder Datei nicht zu stimmen.

**Comment by romanzipp** [comment]
Danke für die Meldung, eine Videodatei war korrupt. Das Video wurde neu gerendert und funktioniert jetzt wieder.
