### ISSUE TITLE
Bug: Videos werden nicht abgespielt

### ISSUE THREAD

**Issue by FlorianHa** [pietsmietde/Bugs#18]
Seitdem der Player gewechselt wurde, kann ich kein Video mehr ohne Probleme abspielen.

Erst nach mehrmaligen Wechseln von der Standard Quelle zur alternativen Quelle lässt sich das Video starten.
Es macht dabei keinen Unterschied, auf welcher Einstellung der Schalter für "Quelle" beim ersten Aufrufen der Seite ist.

 - Betriebssystem: Windows
 - Browser: Firefox

**Comment by YoKoGFX** [comment]
@FlorianHa könntest du mal schauen ob es das Problem von #1 ist ?
