### ISSUE TITLE
Bug: Video verschwindet nach Klick auf den "play" Button

### ISSUE THREAD

**Issue by Spitter88** [PietSmietde/Bugs#180]
**Beschreibe den Fehler**
Sobald ich auf das Video klicke läd es kurz und dann verschindet das Video. Sound des Videos ist allerdings zu hören. Auch wenn ich schnell auf Fullscreen klicke sagt er mir "Pietsmiet.de befindet sich im Vollbildmodus" dabei sehe ich eure Website, jedoch nicht das Video und Sound des Videos ist dort ebenfalls wieder zu hören. Somit keine Chance das Video uncut zu sehen. Ist übrigens bei allen anderen Videos auf dieser Website ebenfalls.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Pietsmiet.de über den "Uncut"-Link in der Videobescheibung (101 % League of Legends Tryhard Gameplay) öffnen.
2. Klicke auf play.
3. Warten bis nach 2-3 Sekunden des ladens das Bild verschindet jedoch Ton zu hören ist.

**Erwartetes Verhalten**
Ein Video, welches ich ohne verschwinden oder flackern, gucken kann.

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.
Screenshots gibt es hier nicht da man ja das Video welches mit angezeigt werden soll (nach dem Klick auf den play Button) leider nicht sieht ;)
Anbei trotzdem ein Screenshot wie es aussieht wenn das Video grade abgespielt wird
![Unbenannt](https://user-images.githubusercontent.com/55767577/65553020-32783200-df26-11e9-8eff-c3494e9240a0.PNG)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 Pro
 - Browser: Mozilla Firefox
 - Browser-Version: 69.0.1 (64-Bit)

**Smartphone (bitte die Informationen vervollständigen):**
Wurde über das Handy nicht getestet. Schaue Pietsmiet über den PC.

**Weitere Informationen**
Keine weiteren Informationen

**Comment by jobilili** [comment]
Hallo,

dem oben beschrieben Problem habe ich nichts beizufügen. Dazu kann ich sagen, dass es wohl für alle Videos gilt. Auch macht es keinen Unterschied der Werbung entsprechend. Schon die Werbung wird sofort unsichtbar und es ist nur noch der Ton zu hören.

Das Problem tritt bei mir das erste Mal auf.


Lol... während ich den Kommentar geschrieben habe, ist das Problem verschwunden. Sowohl auf dem Handy, wie auf dem PC geht alles wieder einwandfrei.

Lg

**Comment by romanzipp** [comment]
Ich konnte das Problem reproduzieren und habe vorerst einen Hotfix reingehauen. Werden wir uns morgen genauer ansehen :)
