### ISSUE TITLE
Bug: Öffnen im Neuen Tab = nicht mehr angemeldet

### ISSUE THREAD

**Issue by StruppiSZ** [PietSmietde/Bugs#181]
**Beschreibe den Fehler**
Öffnen von Video im neuem Tab = nicht mehr angemeldet auf der Pietsmiet.de.

**Reproduktion**
Geh in Browser (Firefox) und melde dich auf Pietsmiet.de an (login) 
geh auf Videos - öffne ein Video über "mittlere Maustaste" in einem neuen Tab

**Erwartetes Verhalten**
Jetzt ist man im Neuen Tab nicht mehr angemedet

**Desktop (bitte die Informationen vervollständigen):**
 - Windows 10
 -  Chrome, Firefox
 - k.p., 69.0.1

**Comment by romanzipp** [comment]
Ich kann den Fehler nicht reproduzieren. Höchstwahrscheinlich hat es was mit den Datenschutz/Sicherheitseinstellungen zu tun, welche das Speichern der Anmeldeinformationen im s.g. "localStorage" des Browsers verhindern.
