### ISSUE TITLE
Feature: Videoqualität merken

### ISSUE THREAD

**Issue by dkeu** [PietSmietde/Bugs#182]
Im Safari 13, ohne Addons, merkt sich der Player keinerlei Einstellungen. Ich schaue Videos immer auf »480p«, wegen Datenvolumen und weil ich Ladezeit vor Qualität bevorzuge. Player merkt es sich allerdings nicht, wählt also jedes Mal »Auto« und somit jedes Mal »720p«, was halt echt nervig ist und am Anfang immer mehr Daten lädt als notwendig.

Wäre schön, wenn man das entsprechend ändern könnte.

**Comment by wbmp** [comment]
Würde mich ebenfalls über ein solches Feature freuen. Bei mir ist's nur der umgekehrte Grund: Ich würde gerne die Videos immer in bestmöglicher Qualität schauen, unabhängig von der Verbindungsgeschwindigkeit. :)

**Comment by idnovic** [comment]
Das klingt nach einem guten Nutzen für Cookies. Der Nutzer müsste es so nur ein mal pro Browser einstellen und die Einstellung bleibt dann so lange der Cookie existiert.

**Comment by idnovic** [comment]
Hätte auch den Vorteil, dass das Notebook zu Hause gute Qualität haben könnte während das Handy Datenvolumen spart.

**Comment by romanzipp** [comment]
Die Funktion ist umgesetzt und wir demnächst gepatcht 👍
