### ISSUE TITLE
Bug: Up-/ Downvoten von Vorschlägen ändert nicht die Zahl

### ISSUE THREAD

**Issue by zwibblTV** [PietSmietde/Bugs#183]
Der Titel sagt eigentlich alles: Wenn man Vorschläge Hoch oder Runter voted, dann wird zwar der Pfeil grün, die Zahl ändert sich aber nicht.
Wäre super, wenn man die Änderung in Zukunft sehen könnte, da das Ändern der Zahl den Klick noch einmal bestätigt.

**Comment by romanzipp** [comment]
Ist gefixt, wird demnächst gepatcht
