### ISSUE TITLE
Bug: Nach Snob Abo keine Flüssige 1080p60 Vollbildwiedergabe in Google Chrome

### ISSUE THREAD

**Issue by McMathew** [PietSmietde/Bugs#184]
Hallo,

ich kann seitdem ich das Snob Abo abgeschlossen habe, kann ich keine 1080p60 Videos im Vollbild mehr in Google Chrome genießen. Sobald ich in den Vollbildmodus wechsel funktioniert die Wiedergabe für ein paar Sekunden problemlos, bis dann das Bild und Ton für 2 Sekunden asynchron werden und dann das Video buffern muss und dann sich auch weiter so durchzieht. Es fühlt sich an, als würde meine Internetleitung oder mein PC System für die 1080p60 Wiedergabe nicht stark genug sein, welche aber definitiv aussreichend sind. Sobald ich das Vollbild schließe oder in den Cinemamodus wechsel funktioniert die Wiedergabe problemlos. 

Warum ich davon aussgehe das es mit dem Snob abo zu tun hat:
1) Vorher hatte ich derlei Probleme nicht
2) Wenn ich mich auslogge oder die Werbung wieder anschalte, funktioniert der Vollbild wieder problemlos.

System:
Win 10 1903
Intel I5 @3,50 GHz
AMD Radeon R9 290x
Chrome Version 77.0.3865.90 

Kleiner Workaround: Im aktuelle Firefox läuft das Video mit deaktivierter Werbungbisher problemlos

**Comment by romanzipp** [comment]
Hört sich wirklich komisch an. Macht es einen Unterschied, wenn du zwischen den Wiedergabepresets wechselst?

![2019-09-29_12:56:47](https://user-images.githubusercontent.com/11266773/65831327-aa44b480-e2b8-11e9-9463-a5efa1e477ac.png)

**Comment by McMathew** [comment]
Hab grad mal beides durchprobiert. Bei mir sind nur 1080p60 und 720p60 nicht zu gebrauchen. Alle anderen Auflösungen, von 240-1080p sind sowohl im preset "Beste Qualität" als auch im "Kompatibilität" zu gebrauchen.

**Comment by dominovox** [comment]
Nochmal für mich zum besseren Verständnis:
Im Firefox funktioniert die Vollbild Wiedergabe von einem manuell auf 1080p60 gestellten Video problemlos, im Chrome nicht?
Kannst du bei Chrome bitte mal den Cache löschen, checken ob dein AMD Grafiktreiber aktuell ist und im Taskmanager bei der Videowiedergabe im Tab Leistung bei GPU schauen, wie hoch die "Video Decoding" Auslastung ist?

**Comment by McMathew** [comment]
-Firefox ja, Chrome nein
-Cache gelöscht, Beschleunigung ist aktiv
-Treiber aktuell 
-Decoding bei ca 68-75%

**Comment by dominovox** [comment]
75% bei Chrome und bei Firefox?
Ich z.B. habe auf meinem Laptop von 2018 mit Intel GPU "nur" 25% maximal.

**Comment by McMathew** [comment]
Youtube, Netflix, Amazon prime haben bei mir keine Auslastung vom Video Decode sondern nur von der 3D Anzeige

**Comment by McMathew** [comment]
hardwarebeschleunigung deaktivieren hat geholfen :D. ich denke das snob abo kann damit nichts zu tun haben, weil ich nie mit dieser einstellung rumgespielt habe. war wohl zufall das es auf einmal nicht mehr funktioniert hat, vielleicht wurde ein update für chrome, windows oder meine graka im hintergrund eingespielt. auch hatte es zur folge das der prozess der graka von video encode ( mit annähernd 70 %) zum prozess "3D" verschoben wurde wo ich nur 18 % bekomme
