### ISSUE TITLE
Bug: Reload der Seite über Dropdown nicht möglich

### ISSUE THREAD

**Issue by Jannusch** [PietSmietde/Bugs#186]
**Beschreibe den Fehler**
Die Seite wid nicht neu geladen wenn über das Dropdown menu die selbe Seite ausgewählt wird

**Reproduktion**
1. Auf neuese Videos gehen
2. Noch mal auf neueste Videos gehen, wenn ein neues Video veröffentlicht wurde
3. Feststellen das das neue Video nicht erscheint

**Erwartetes Verhalten**
Die Seite sollte neu laden um neue Inhalte anzuzeigen (neue Videos)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Firefox
 - Browser-Version: 69.0.1

**Comment by BoehmFloh** [comment]
Gilt auch für Linux; Chrome

**Comment by romanzipp** [comment]
Genau genommen handelt es sich dabei nicht um einen Bug. Aktuell habe ich aber noch keine Lösung gefunden, so ein Verhalten einzubauen.

Wie in den Einstellungen zu sehen kann man mit dem `R`-Hotkey die Video/News/Podcastauflistungen neu laden.
