### ISSUE TITLE
Bug: Mit Cloudflare DNS

### ISSUE THREAD

**Issue by dkeu** [PietSmietde/Bugs#187]
Wenn ich mit Cloudflare DNS auf eure Seite zugreifen möchte, laden die Videos nicht. Da man heutzutage eigentlich immer andere DNS-Einträge als die von seinem Provider hat, wäres es schön, wenn das behoben wird.

**Comment by romanzipp** [comment]
Das Szenario kann ich so nicht reproduzieren. Ebenfalls glaube ich nicht, dass es an der DNS Einstellung liegt, da Cloudflare selbst die DNS Dienste für unsere Domains zur Verfügung stellt.

**Comment by dkeu** [comment]
Hast Recht. Da hatte wohl irgendwas im Cache Schluckauf. Alles klar, vergiss es :)
