### ISSUE TITLE
Bug: Video verschwindet

### ISSUE THREAD

**Issue by StruppiSZ** [PietSmietde/Bugs#188]
**Beschreibe den Fehler**
Das Video verschwindet, sobald die Seite komplett mit der Werbung geladen ist.

**Reproduktion**
Firefox 69.0.1 (64-bit) egal ob privates Fenster oder nicht.
Video aufrufen ( egal ob angemeldet oder nicht) 
und sobald die Seite geladen ist und die Werbung sich zuschaltet "rutscht" das Videofenster nach oben "unter" die Werbung und ist nicht mehr zu sehen - ton läuft normal weiter
![Pietsmiet](https://user-images.githubusercontent.com/55780099/66036000-837ebc00-e50c-11e9-8ab4-941395ac2dd7.JPG)

**Desktop (bitte die Informationen vervollständigen):**
 -  Windows 10
 - Firefox
 - 69.0.1

**Comment by dominovox** [comment]
Hi,
welchen Adblock nutzt du und welche Filterlisten sind aktiv?

**Comment by StruppiSZ** [comment]
Hi,
ich habe den "AdBlock ultimate" erst nach dem fehler installiert, um zu sehen ob er die Werbung beeinflusst - der Fehler war vorher schon da (davon abgesehen wird eure Werbung eh nicht durch den blockiert :D). Die Seite neu geladen und so alles hab ich auch schon.
Jetzt habe ich es nochmal versucht und die Videos laufen - das selbe problem hatte ich Montag auch schonmal - jetzt hab ich auhc einfach gewartet - Browser angelassen und PC ebenso.
Leider kann ich nicht mehr Informationen liefern.

**Comment by dominovox** [comment]
Hast du den Browser Cache gelöscht?

**Comment by StruppiSZ** [comment]
nein ich habe nur die Seite geschlossen und nach ca.1h diese wieder aufgerufen

**Comment by dominovox** [comment]
Oke, wenn es nochmal vorkommt, sag uns bitte bescheid.
