### ISSUE TITLE
Seite "Videos" / "Neuste Videos" lädt nicht

### ISSUE THREAD

**Issue by TheRealFlori** [PietSmietde/Bugs#191]
**Beschreibe den Fehler**
Wenn ich auf den Reiter Videos klicke und dann neueste Videos auswähle dauert das laden über eine Minute. Mit Laden meine ich das blinken der grauen Videoplatzhalter. Danach kommt Keine Videos gefunden :( 

Ich habe vorher jedoch die Suchfunktion oben Rechts genutzt und nach "Überraschung PROFI" gesucht welches in nach 20 Sekunden des Ladens/Suchens abgebrochen habe.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Suche "Überraschung Profi"
2. brich die Suche ab
3. Navigiere zu https://www.pietsmiet.de/videos

**Erwartetes Verhalten**
Suchen abrechen und einfach die neusten Videos anzeigen, da ich ja auf den Reiter geklickt habe

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.
(*Screenshots per Drag & Drop hier einfügen*)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10
 - Browser: Chrome
 - Browser-Version: Version 78.0.3904.34 (Offizieller Build) beta (64-Bit)

**Comment by romanzipp** [comment]
Das liegt momentan an einem Problem mit der Infrastruktur. Wir sind dran
