### ISSUE TITLE
Untermenü wird nicht angezeigt (Firefox)

### ISSUE THREAD

**Issue by JKutscha** [PietSmietde/Bugs#193]
Ist die Webseite im Browser(Firefox) nicht in voller Größe geöffnet und oben links erscheinen die 3 Striche, wird die Webseite lediglich per Klick verdunkelt, aber es erscheinen keine Auswahlmöglichkeiten.
![#1](https://user-images.githubusercontent.com/50097340/66256020-18dab400-e78a-11e9-9f7f-6a59b9b80bec.PNG)
![#2](https://user-images.githubusercontent.com/50097340/66256019-18dab400-e78a-11e9-8421-16aec7848b86.PNG)
Desktop:
 - Betriebssystem: [Windows 10]
 - Browser: [Firefox]
 - Browser-Version: [69.0.1 (64-Bit)]

**Comment by romanzipp** [comment]
Bitte aktualisiere die Seite. Das Menü wird nicht gerendert, wenn sie auch zum Zeitpunkt des Aufrufs nicht gebraucht wird
