### ISSUE TITLE
Seite nicht gefunden

### ISSUE THREAD

**Issue by livedeci** [PietSmietde/Bugs#195]
**Beschreibe den Fehler**
Beim Klick auf den Banner zum Shop (Heiße Klamotten für heiße Schnittchen) öffnet sich ein neuer Tab der wieder den Banner enthält und ansonsten nur "Seite nicht gefunden"

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
Bis jetzt auf jeden Banner der zum Shop führt (Heiße Klamotten für heiße Schnittchen)

**Erwartetes Verhalten**
Umleitung zum Shop? 

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.
(*Screenshots per Drag & Drop hier einfügen*)
![ps_seitenichtgefunden](https://user-images.githubusercontent.com/56216882/66266045-c8159a80-e81f-11e9-81d7-79b7e03b0efa.jpg)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Win10
 - Browser: Chrome
 - Browser-Version: 77.0.3865.90 (Offizieller Build) (64-Bit)

**Comment by dominovox** [comment]
Die Links haben wir fixen lassen, danke!
