### ISSUE TITLE
Tonprobleme durch async 

### ISSUE THREAD

**Issue by Cosnavel** [PietSmietde/Bugs#196]
Asynchroner Ton bei Google Chrome. Ggf gleicher Fehler wie bei #184. 
Bei mir auch mit normaler Wiedergabegeschwindigkeit. Das Problem tritt bei Safari nicht auf.

Chrome Version 77.0.3865.90
Mac 

Ich habe in der Konsole die Fehlermeldung :
kaltura-ovp-player.js?id=c5e147a850fb336d8d28:6 [Error] Category:7 | Code:7003 | kanalytics
n @ kaltura-ovp-player.js?id=c5e147a850fb336d8d28:6

**Comment by romanzipp** [comment]
Duplicate of #189
