### ISSUE TITLE
Benachrichtigungen sind nicht klickbar

### ISSUE THREAD

**Issue by tneumueller** [PietSmietde/Bugs#197]
**Beschreibe das Feature**
Wenn ich eine Benachrichtigung, z.B. zu einer Antwort auf einen Kommentar, erhalte, dann wäre es wünschenswert, wenn ich diese anklicken und damit zum jeweiligen Kommentar gelangen würde.

**Gibt es Alternativen?**
In meinen Augen keine guten

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Nein

**Weitere Informationen**
Keine

**Comment by romanzipp** [comment]
Es sollte in der Benachrichtigung ein Link vorhanden sein, mit dem man zu dem zugehörigen Kommentar gelangt.

![2019-10-07_12:17:29](https://user-images.githubusercontent.com/11266773/66303953-7a229480-e8fc-11e9-80a9-7961da66f014.png)

**Comment by tneumueller** [comment]
Den gibt es in meinem Fall nicht, siehe Screenshot:

![](https://i.imgur.com/FXyMXbl.png)

**Comment by romanzipp** [comment]
Habe gerade nachgesehen, das war ein Fehler der mittlerweile behoben ist. Es lag daran, dass die Antwort in einem Vorschlag vorgenommen wurde, und dort die Verlinkung noch nicht funktioniert hat. Bei zukünftigen Antworten tritt der Fehler nicht mehr auf.
