### ISSUE TITLE
Fullscreen am Smartphone sollte den Bildschirm drehen

### ISSUE THREAD

**Issue by P34nut** [PietSmietde/Bugs#198]
**Beschreibe das Feature**
Ich finde, dass sich der Bildschirm am Smartphone drehen sollte, um die gesamte Fläche auszunutzen. Im Moment ist es so (zumindest bei mir), dass die Größe des Players nicht verändert wird und weiterhin an den vertikalen Modus ausgerichtet ist.
(Youtube kann als Referenz angesehen werden, dort dreht sich der Bildschirm auf die gesamte Fläche

**Comment by romanzipp** [comment]
Danke für die Anregung. Ist umgesetzt und wird demnächst gepatcht!
Das Feature wird vorerst nur unter Android funktionieren, da uns iOS dabei einen Strich durch die Rechnung macht.
