### ISSUE TITLE
Wiedergabe von Podcast's funktioniert nicht

### ISSUE THREAD

**Issue by GamerMarkus** [PietSmietde/Bugs#199]
Hallo,
wie im Titel schon erwähnt, funktioniert bei mir die Wiedergabe von Podcast's nicht.
Nach dem Einloggen auf der PietSmiet.de und dem Klicken auf "Podcast" sehe ich die Liste der Podcast's mit ihrer jeweiligen Länge/Dauer. Soweit so gut. Wähle ich dann einen Podcast aus, steht bei mir oberhalb der Leiste mit den Geschwindigkeitseinstellungen "00:00 / 00:00". Müsste da nicht an zweiter Stelle die Länge des Podcast's stehen?
Beim Klicken auf den Play-Button passiert dann bei mir entsprechend nichts. Dieses Problem habe ich sowohl bei neuen Podcast's und bei alten Podcast's, die ich noch nicht gehört habe. Auch bei bereits gehörten Podcast's funktioniert die Wiedergabe nicht.

 - Betriebssystem: Windows 8.1
 - Browser: Firefox
 - Browser-Version: 69.0.1 (64-Bit)
![Podcast Liste](https://user-images.githubusercontent.com/56338510/66461661-ce9f4e80-ea79-11e9-937e-9bfcfc51bd08.PNG)
![Podcast Auswahl](https://user-images.githubusercontent.com/56338510/66461677-d4952f80-ea79-11e9-809b-2e3abb198531.PNG)

**Comment by romanzipp** [comment]
Das liegt an einer Fehlerhaften Filterregel des AdBlockers "uBlock Origin". Darauf haben wir leider keinen Einfluss.
