### ISSUE TITLE
Bug:  Abgespeckt und Randomisiert 🎮 TTT #709 piets sicht geht nicht

### ISSUE THREAD

**Issue by shion2019** [pietsmietde/Bugs#20]
**Beschreibe den Fehler**
bei der TTT 709 folge geht peters sicht nicht es kommt folgende Fehler meldung : The media could not be loaded, either because the server or network failed or because the format is not supported.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu '...'
2. Klicke auf '....'

**Erwartetes Verhalten**

**Screenshots**

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: win 10
 - Browser: Firefox
 - Browser-Version: [z.B. 22]

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: [z.B. iPhone6]
 - Betriebssystem: [z.B. iOS8.1]
 - Browser: [z.B. stock browser, Safari]
 - Browser-Version: [z.B. 22]

**Weitere Informationen**
Weiter Informationen über das Problem, wenn vorhanden.

**Comment by derLesh** [comment]
![image](https://user-images.githubusercontent.com/11671272/53184252-00ec6080-35fd-11e9-91a8-b925bcc887c4.png)

Die Datei wird nicht gefunden

**Comment by romanzipp** [comment]
Es gab einen Fehler bei der Videoverarbeitung. Die Perspektive ist seit gestern Abend wieder verfügbar
