### ISSUE TITLE
Bug: Probleme beim Erstellen von Tags

### ISSUE THREAD

**Issue by Tanielll** [PietSmietde/Bugs#201]
Seit gestern habe ich Probleme bei dem Erstellen von Tags. Es kommt andauernd die Meldung "title bereits vergeben", wenn ich einen Namen für einen Tag eingebe und versuche diesen Tag zu erstellen.
Nach ein wenig rumprobieren hat es bei mir den Eindruck erweckt, als ob man die Tags nur noch erstellen kann, wenn sie zuvor noch nie von einem selbst oder anderen erstellt wurden.
Das könnte natürlich Absicht sein, um zu verhindern, dass immer die selben Tags gespammt werden, jedoch führt es dann meiner Meinung das ganze Tagsystem ab absurdum, da es immer schwieriger wird passende Tags für ein Video zu finden.
Außerdem ist die Fehlermeldung ja wohl ziemlich sicher noch fehlerhaft. Aus "title bereits vergeben" geht nicht wirklich hervor, was bei dem Tag das Problem ist.

Falls das Ganze Absicht ist, wäre ich zumindest über eine Erklärung sehr dankbar. :)

**Comment by romanzipp** [comment]
Es gab einen Fehler, wodurch es Tags allgemein nur einmal geben durfte. Das wurde behoben und ist nach dem Patch nur noch pro Objekt.
