### ISSUE TITLE
Vorschlag: Permanent sichtbare Anzeige für aktuelle Schnittchenanzahl oben rechts

### ISSUE THREAD

**Issue by Tanielll** [PietSmietde/Bugs#202]
**Beschreibung des Features:**
Ich würde eine dauerhaft sichtbare Anzeige für die Schnittchenanzahl sehr begrüßen, sodass man überall auf der Website sieht, wie viele Schnittchen man aktuell hat, ohne auf das eigene Profil gehen zu müssen.

**Mögliche Umsetzung:**
Als Position für diese Anzeige würde sich meiner Meinung nach die obere Leiste am besten eignen. Dort würde ich sie links neben der Glocke platzieren. So wäre sie jederzeit gut sichtbar.
Als Design fände ich die Darstellung wie sie auch in den Kommentaren ist sehr geeignet (die Zahl in dem abgerundeten Rechteck). Als Farbe würde ich für normale User Weiß vorschlagen und für Snob-Abonnenten Blau.

**Alternative Positionierung:**
Eine alternative Position wäre das Dropdown-Menü, welches erscheint, wenn man über das Profilbild oben rechts hovert.
Auf Mobilgeräten dann evtl. über oder unter der Anzahl, der ungelesenen Mitteilungen, im Sidebar-Menü.

**Mitbringende Verbesserung:**
Ich denke dieses Feature würde das Nutererlebnis auf der Seite für sehr aktive Nutzer nochmal verbessern, da sofort ersichtlich ist wie viele Schnittchen man akutell hält.

**Comment by romanzipp** [comment]
Danke für die Anregung, ist umgesetzt und wird demnächst gepatcht!
