### ISSUE TITLE
Vorschlag: Changelog über Änderungen an der Website

### ISSUE THREAD

**Issue by Tanielll** [PietSmietde/Bugs#203]
**Beschreibung des Features:**
Eine Liste alle Änderungen, die an der Website gemacht werden, welche bei jeder Aktualisierung der Website geupdatet wird. Dort sollten dann zumindest alle Änderungen, welche für den Nutzer irgendwelche Auswirkungen haben, aufgeführt sein.

**Alternative:**
Falls es zu viel Arbeit ist, so eine Liste bei jeder Aktualisierung zu erneuern, könnte man sich auf eine Erneuerung der Liste in einem festen Intervall beschränken.

**Grund für den Vorschlag:**
Die Idee kam mir, nachdem ich nach einem Update Probleme beim Tags erstellen hatte, weil ich nicht wusste was genau geändert wurde. Durch eine offenere Kommunikation dahingehend, könnten solche Vorkommnisse in Zukunft sicher beseitigt werden.

**Comment by romanzipp** [comment]
Wir haben bereits vor, Änderungen monatlich zusammengefasst als Devblogs zu veröffentlichen.
