### ISSUE TITLE
Werbeeinblendungen vor dem Video

### ISSUE THREAD

**Issue by Apokya** [PietSmietde/Bugs#205]
**Beschreibe den Fehler**
Die Werbeblöcke vor dem Video laden teilweise gar nicht. Selbst 15 mal neuladen der Seite hilft nicht. Es gibt mehrere Möglichkeiten was im Moment bei der Werbung passiert:
- Video buffert, "Advertisement" wird angezeigt, aber nur Werbeton wird abgespielt. Danach kein Videostart
- Video buffert, "Advertisement" wird angezeigt, Nichts passiert. Danach kein Videostart
- Video buffert, "Advertisement" wird angezeigt, Nichts passiert. Man drückt Play, das eigentliche Video starten, kann aber nicht mehr gestoppt werden.
- Video buffert, startet sofort, ohne Werbung.
- Video buffert, startet sofort, mit Werbung.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Video mit Play starten
2. Problem beobachten, wie oben gesehen

**Erwartetes Verhalten**
Naja. Wie es sein sollte: Werbung wird angezeigt und danach startet das Video ;)

**Screenshots**
---

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Firefox
 - Browser-Version: 69.0.3 (64-Bit)

**Weitere Informationen**
Weiter Informationen über das Problem, wenn vorhanden.

**Comment by romanzipp** [comment]
Es kann öfter dazu kommen, dass keine Werbeblöcke abgespielt werden, da keine Slots dafür zur Verüfgung stehen. Darauf haben wir keinen Einfluss.
Wir haben ein Rework der Werbeausspielung in der Pipeline. Damit sollten sich einige Fehler demnächst erledigt haben!
