### ISSUE TITLE
Mauszeiger im Bild

### ISSUE THREAD

**Issue by BrightDarknessXX** [PietSmietde/Bugs#206]
Ich bin mir nicht sicher, ob es wirklich ein Fehler ist, aber, wenn ich ein Video schaue, dann wird der Mauszeiger nicht mehr ausgeblendet bzw. bleibt einfach im Bild (Wenn die Videosteuerung im Video unten verschwindet). Dies ist auf mehreren Browser, die ich getestet hab, der Fall. (Firefox, Chrome, Edge, Explorer)
Bei Youtube z.B. wird er nach ein paar Sekunden ausgeblendet.
Ich persönlich finde es schon störend und würde es daher als Fehler einstufen.

**Comment by SelRiouS** [comment]
Denke, dass ist ein Duplikat von #150
Oder wurde vorher der Mauszeiger im nicht Vollbild ausgeblendet?

**Comment by BrightDarknessXX** [comment]
Ja, das stimmt. Mein Bug-Report ist ein Duplikat, dies muss ich wohl übersehen haben. Tut mir leid.

**Comment by romanzipp** [comment]
Duplicate of #150
