### ISSUE TITLE
Pietcast Feed

### ISSUE THREAD

**Issue by Siver123** [PietSmietde/Bugs#207]
**Beschreibe den Fehler**
Moin habe unter einem YT video auf diesen Link geklickt und mir wir auf der homepage dann nur der Quellcode angezeigt. Sieht sehr nach einem Fehler aus. (https://www.pietsmiet.de/podcast/feed)

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
Youtube Video: https://www.youtube.com/watch?v=lL0GdWFGMpI
Auf diesen link geklickt: https://www.pietsmiet.de/podcast/feed
**Erwartetes Verhalten**
eine funktionierende homepage

**Screenshots**
http://prntscr.com/plpe7a

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10
 - Browser: Chrome Dektop
 - Browser-Version: Neuste

**Weitere Informationen**
Ich hoffe ich konnte helfen. Würde mich über eine kleine Rückmeldung freuen :P. 
Sivercsf@gmail.com 
P.S. einen Fehler zu melden ist sehr umständlich. Dafür ein extra Github Account anzulegen wird denke ich einige davon abhalten Fehler zu melden. Ich habe selber eine Homepage und meine Programmier nutzen gitHub, daher habe ich ein Account

**Comment by whereo** [comment]
Eigentlich nur ein falscher Link. Entweder ist das `/feed` am Ende zuviel oder der Link zur eigentlichen Folge fehlt.
Aber: Da stimmt tatsächlich was an den Routes nicht ganz. Der "Quellcode" ist der Atom-Feed, den RSS-Reader und Co verwenden. Der sollte aber (laut Webseite) unter der Domain `/podcast/feeds/25` laufen (wofür auch immer der Index ist).
Interessant ist auch, dass `/podcast/feeds/` auf `/podcast/` umleitet, während `/podcast/feed` den (gleichen) RSS-Feed zurückgibt.

**Comment by romanzipp** [comment]
Die URL ist korrekt. Wenn diese auf Android/iOS mit einer kompatiblen Podcast App aufgerufen werden, kann man damit den PietCast abonnieren.

Es gibt viele verschiedene URLs, da sich das System im Laufe der Zeit viel verändert hat und alte Podcast Einbindungen noch auf alten URLs laufen.

**Comment by Siver123** [comment]
alles klar war nur verwundert :P und wollte keine Werbung machen sry :) aber wenn man stolz ist will man sein Baby überall zeigen.
