### ISSUE TITLE
Eigener Community Vorschlag weder sichtbar noch findbar

### ISSUE THREAD

**Issue by MoinNils** [PietSmietde/Bugs#208]
**Beschreibe den Fehler**
Moinsen, ich habe jetzt schon Zwei Community vorschläge gepostet, einen vor ner stunde, den anderen vor 1 monat, nun frage ich mich ob ich den sehen kann und ich habe alle 20 seiten durchgeguckt und nicht gefunden.. ;c

**Reproduktion**
1. Anmeldung, Normal
2. Navigiere zu 'Community, Vorschläge, Vorschlag einreichen, Vorschlag für aktuelles Format'
3. Fülle dort nun alles aus 
4. klicke auf 'Einreichen' 
5. Gehe auf mein Profil auf der Hoffnung dort steht irgendwas, aber nichts 

**Erwartetes Verhalten**
Naja ich hab gehofft das ich nun sehen kann, ob man mein Post sehen kann oder, ob die Idee den Leuten gefällt.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: [Windows 10]
 - Browser: [Chrome]
 - Browser-Version: [das neuste denk ich mal hehe]
- AdBlock natürlich ausgeschaltet <3

**Weitere Informationen**
Weiter Informationen über das Problem, wenn vorhanden.
Jungs, allet stabil keine Hektik sacht mein alter, hätte nur gerne gesehen was die Leute denken
Schönen tag noch 
Nils ohne E versteht sich.

**Comment by romanzipp** [comment]
Aktuell werden Vorschläge noch manuell freigegeben, damit wir intern Verbesserungen vornehmen können. Wenn der Vorschlag nicht freigegeben wurde kann es gut sein, dass es sich um ein Duplikat handelt.
