### ISSUE TITLE
Werbung durch Pause fehlerhaft

### ISSUE THREAD

**Issue by Im-sama7** [PietSmietde/Bugs#209]
**Beschreibe den Fehler**
Die Werbung funktioniert nicht, wenn man, während die Werbung lädt, auf Pause klickt --> man kann sie dadurch überspringen indem man dann die Seite neulädt und auf "siehe von dem Punkt weiter" anklickt 

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Gehe auf ein Video
2. Lass es bis zu einer Ad laufen
3. Drücke auf das Video während die Werbung lädt 
4. Video hängt dann --> Seite neu laden 
5. Auf den Zeitpunkt klicken und auf einen bestimmten Zeitpunkt auf der Zeitleisze klicken (ein paar Sekunden davor oder danach)

**Erwartetes Verhalten**
Das es unmöglich ist die Werbung zu überspringen (Die Seite keinen Verlust macht) z B irgendein ein Tool einbauen das einen zu der ad zwingt

**Screenshots**
Keine

**Smartphone (bitte die Informationen vervollständigen):**
 - Betriebssystem: [z.B. Android]
 - Browser: [z.B. Samsung Internet (jedoch über den über den Startbildschirm verknüpft (weiß nicht ob das was ändert))]
 - Browser-Version: [z.B. die neuste ka wie die heißt]

**Weitere Informationen**
Keine

**Comment by Im-sama7** [comment]
Vergessen was zu sagen:
Es ist nicht die erste Werbung sondern die Werbungen, die mitten in den Videos sind

**Comment by romanzipp** [comment]
Ich denke nicht, dass es sich hierbei um einen Fehler handelt. Wir haben einen Cooldown eingebaut, der darauf achtet, dass man nicht mit Werbungen zugegossen wird, sobald man in einem Video vor/zurück skipt.
Es kann auch immer vorkommen, dass Werbungen zwar laden aber nicht ausgespielt werden. Das ist normal, da z.B. keine Werbeslots verfügbar sind.
