### ISSUE TITLE
Bug: Twitter-Avatar werden nicht über https geladen

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#21]
**Beschreibe den Fehler**
Wenn ein Nutzer einen Account erstellt, und von diesem, sein Twitter-Avatar verwendet, wird dieser nicht über https geladen.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/videos/pietsmiet/52117-gpo-das-grosse-f1-event

**Erwartetes Verhalten**
Alles sollte über https geladen werden.

**Weitere Informationen**
Es geht um die URL: http://pbs.twimg.com/profile_images/650954061185880064/WI8Bb5pJ_normal.png

**Comment by YoKoGFX** [comment]
@romanzipp gibt es hierzu ein Update? Denn mit der neuen Version von Safari wird dies eine schöne Warnung anzeigen!

**Comment by romanzipp** [comment]
Ist gefixt, wird die Tage gepatcht.
