### ISSUE TITLE
Feature: Cinema Modus auf komplette Breite des Browsers

### ISSUE THREAD

**Issue by hasdf** [PietSmietde/Bugs#210]
Könnte man die Videogröße im Cinema-Modus auf die komplette Bildschirmbreite ausdehnen? 

So wäre es möglich, Videos in maximaler Größe auf einem zweiten Bildschirm oder in geteilter Ansicht auf einem Widescreen-Bildschirm zu genießen.

Aktuell wird das Video nur vergrößert dargestellt, und auf den Seiten Platz verschwendet. Die Website ist in diesem Modus sowieso nicht mehr verwendbar.

Beispiel-Screenshot:
![cinema_pietsmiet](https://user-images.githubusercontent.com/1760609/67642853-52798780-f910-11e9-972a-d52bf6ed4e87.png)

**Comment by romanzipp** [comment]
Danke für die Anregung! Beim nächsten Dev-Blog Post werde ich mal eine Umfrage dazu machen.
