### ISSUE TITLE
Bei manchen Videos sind die Videoqualitätseinstellungen falsch beschriftet

### ISSUE THREAD

**Issue by MarianNapierkowski** [PietSmietde/Bugs#211]
2 Videos die ich auf die Schnelle gefunden habe: 
Ode an Takeshi | P.RO.FI.
https://www.pietsmiet.de/videos/57007-ode-an-takeshi-profi

Könnt ihr die Verabschiedungen der anderen imitieren? | Frag Pietsmiet #1676
https://www.pietsmiet.de/videos/56923-fps-1676

Wenn man da die Qualität ändern will ist die Reihenfolge der AUFZÄHLUNG aufsteigend nicht absteigend. Die FUNKTION dahinter bleibt aber gleich, als wäre die Aufzählung noch absteigend.
Man klickt also auf 1080p60 und es schaltet auf 240p um und vice versa

 - Gerät: PC
 - Betriebssystem: Windows 10
 - Browser: Chrome
 - Browser-Version: 77.0.3865.120

**Comment by SelRiouS** [comment]
Also bei mir auch Win 10 und auch Chrome 77.0.3865.120 funktioniert es bei beiden so wie es soll.

**Comment by romanzipp** [comment]
Ich konnte den Fehler nicht reproduzieren, aber habe einen möglichen Fix dafür erstellt. Dürfte im Laufe des Tages dann gepatcht werden.
