### ISSUE TITLE
iOS Pietsmiet.de nicht dargestellt

### ISSUE THREAD

**Issue by idnovic** [PietSmietde/Bugs#212]
**Beschreibe den Fehler**
Die Pietsmiet.de Webseite wird mit Microsoft Edge nicht dargestellt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de

**Erwartetes Verhalten**
Die Webseite wird dargestellt. 

**Screenshots**
<img width="1024" alt="PNG-Bild" src="https://user-images.githubusercontent.com/28260793/67721156-24f71180-f9d6-11e9-853c-59b3ac17ca85.png">

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: iPad Air2
 - Betriebssystem: iOS 13.2
 - Browser: Microsoft Edge
 - Browser-Version: 44.9.11

**Weitere Informationen**
-

**Comment by romanzipp** [comment]
Der Fehler konnte unter iOS 13.2 & Edge nicht reproduziert werden. Hast du andere spezielle Sachen installiert, die darauf Einfluss haben könnten?

**Comment by idnovic** [comment]
Ich hatte einen VPN eingerichtet um tracking zu verhindern. Dieser VPN nutzt pi-hole um bestimmte Domain Anfragen zu unterbinden.

Mit dem selben Setup funktioniert Pietsmiet.de auf allen anderen Geräten und auf dem Problem Gerät mit Safari nur nicht mit Edge. (Edge auf Mac funktioniert wiederum)

Ich habe eben kurzzeitig den VPN deaktiviert und siehe da, nun funktioniert es auch mit Edge auf iOS.
Wenn nun der VPN aktiviert ist, funktioniert es auch. Allerdings werden die Domains noch im Cache gespeichert sein und die DNS Abfragen deswegen unnötig.

Ich werde warten bis es wieder nicht geht und rausfinden welche Domain dafür verantwortlich ist.
Ich könnte mir vorstellen, das Edge eine blockierte Resource nicht laden konnte und render blocking stattfand.

**Comment by idnovic** [comment]
Übrigens unterstütze ich natürlich Pietsmiet mit dem Snob Abonnement.

**Comment by idnovic** [comment]
Muss das Issue wieder öffnen.
Es geht nicht ein einziger Browser auf iOS für mich, welcher Pietsmiet.de darstellt.
Mit vpn oder ohne macht keinen Unterschied.

Ich denke es liegt an cloudflare. Direkt vor der nur weißen Pietsmiet Seite sehe ich die DDOS Protection Meldung von Cloudflare.

**Comment by romanzipp** [comment]
Ich kann selbiges auch auf Safari unter macOS reproduzieren, genauere Infos, wieso das passiert, konnte ich da aber nicht finden.
Denke wir werden von der Cloudflare Sicherheitsstufe zukünftig Abstand halten.

**Comment by idnovic** [comment]
ich habe selbst cloudflare und Pie mal Daumen nimm das nächst niedrigere bei der Stufe.
Cloudflare bietet auch bot protection an neuerdings. Damit habe ich noch keine Erfahrung.

**Comment by idnovic** [comment]
Was DDOS angeht, rate limiting könnte helfen. Allerdings lässt sich das Cloudflare per request bezahlen. https://support.cloudflare.com/hc/en-us/articles/115000272247-Billing-for-Cloudflare-Rate-Limiting

**Comment by romanzipp** [comment]
Das Sicherheitslevel ist mittlerweile wieder normal, sollte alles behoben sein.
