### ISSUE TITLE
Lange Videos wie z.B. stream archive funtionieren nach 5- 10 minuten nicht mehr

### ISSUE THREAD

**Issue by BLU3NINJ4** [PietSmietde/Bugs#213]
**Beschreibe den Fehler**
Wenn ich mir ein stream archiv anschauen will z.B. der ces 2019 stream bleibt das video nach ca 5-10 min. hängen. Danach wird das video nur noch mit einer max minuten anzahl angezeigt bei der das video stehen geblieben ist und das video wird einfach vorgespult.

**Reproduktion**
1. Navigiere zu 'pietstream archiv'
2. Klicke auf 'eins der längeren videos z.B. der ces  2019 stream'
3. Ein paar minuten schauen 5-10 bei mir immer

![pietsmiet](https://user-images.githubusercontent.com/57180882/67858884-950eb000-fb1a-11e9-982f-5afcc0579455.PNG)
hier sieht man das video ist bei 0:07/6:12 obwohl es eig. 6 stunden lang ist

 - Betriebssystem: Windows 10
 - Browser: Firefox und MS Edge
 - Browser-Version: 70.0

**Weitere Informationen**
Ich hatte dieses Problem bei dem ces 2019 Stream Video und bei dem 2. Roadtrip stream video

**Comment by BLU3NINJ4** [comment]
ich habe vergessen zu erwähnen ich hab es auch mit microsoft edge ausprobiert da hatte ich das selbe problem

**Comment by romanzipp** [comment]
Danke für die Meldung. Es sieht stark danach aus, dass die Videodateien korrupt sind, da ich den Fehler auch auf beiden Preset-Einstellungen reproduzieren konnte.
Bei neuen Streams funktioniert alles problemlos.
CC @dominovox

**Comment by BLU3NINJ4** [comment]
Ok schade hätte mich gefreut die nochmal zu schauen. ^^
