### ISSUE TITLE
Video läuft nicht flüssig.

### ISSUE THREAD

**Issue by Racemace** [PietSmietde/Bugs#215]
Fehlerbeschreibung:
Immer wenn ich auf der Website Videos ansehen will tritt von Anfang an bzw. im Verlauf des Videos der Fehler auf, dass das Video läd und daher ins stocken gerät. Der Player zeigt an, dass das Video gebuffert ist und nach mehreren Minuten Wartezeit tritt der Fehler dennoch auf. Vorspuhlen des Videos führt dazu, dass es oft gar nicht mehr weiter läuft und in einem endlosen Ladebildschirm endet. An der meiner Leitung sollte es nicht liegen mit 72 Mbit/s.

**Desktop:
 - Betriebssystem: Windows 7
 - Browser:  Chrome,
 - Browser-Version: 78.0.3904.87

**Comment by romanzipp** [comment]
Hast du die alternative Quelle mithilfe des Einstellungs-Buttons unterhalb des Players ausprobiert? Laufen die Videos auf einer niedriger Qualitätsstufe? Ist die CPU zu ausgelastet, während ein Video abspielt?
