### ISSUE TITLE
Home-Seite neu laden über "Home" oder Logo

### ISSUE THREAD

**Issue by Fenack** [PietSmietde/Bugs#217]
**Beschreibe das Feature**
Wenn man sich auf der Home Seite befindet und diese neu laden will, muss man dies über den Refresh vom Browser tun.
Über eine erneute Verlinkung über den Menüpunkt "Home" oder auch das Logo oben links wäre dies oft leichter zu erreichen. Zumindest, wenn man gerade nur mit Maus arbeitet und im Vollbild oder ähnlichem ist. Dies gilt auch für mobile Geräte (Tablet, Smartphone).

**Comment by romanzipp** [comment]
Aktuell habe ich noch keine zufriedenstellende Lösung dafür gefunden. Allerdings kannst du mit der `R`-Taste auf Desktop die Video/News/Podcastlisten neu laden.

Duplicate of #186

**Comment by romanzipp** [comment]
Duplicate of #186
