### ISSUE TITLE
Fehler bei der Qualitätseinstellung des Videos

### ISSUE THREAD

**Issue by Zero100895** [PietSmietde/Bugs#218]
Mir ist seit ein paar Tagen ein kleiner Fehler innerhalb des Video-Players aufgefallen und man die Qualität im Vollbild ändern möchte passiert dies nicht. Erst nach dem zweiten Versuch. Der von mir verwendete Browser ist in dem Fall Opera. Der Fehler müsste aber dann auch auf anderen Chromium basierten Browsern reproduzierbar sein.

Schritte um den Fehler zu reproduzieren:
1. Navigiere auf ein X-Beliebiges Video
2. Starte das Video
3. WICHTIG Video erst auf Vollbild vergrößern
4. Zahnrad auswählen
5. Qualität versuchen von Automatisch auf bspw. 1080p zu ändern
6. Keine Änderung
7. Schritt 4 wiederholen
8. Jetzt eine andere Videoqualität wie vorher auswählen bspw. 1080p60
9. Erst jetzt ändert sich die Qualität des Videos bzw. es buffert und lädt das Video ab dem Zeitpunkt neu.

 - Betriebssystem Windows 10 Home 1903 [Build 18362.418]
 - Browser: Opera
 - Browser-Version: Opera 60 – R3

**Comment by romanzipp** [comment]
Konnte den Fehler auf keinem Gerät reproduzieren. Der Player lädt beim Abspielen mehrere Sekunden im Voraus, wodurch eine Qualitätsänderung möglicherweise erst nach diesem Buffer geschehen kann.
Wir hätten auch weiterhin keinen Einfluss darauf, wenn wir es anders umsetzen wollten.
