### ISSUE TITLE
Bug: Antworten als nicht angemeldeter User führt zum Softlock

### ISSUE THREAD

**Issue by derLesh** [pietsmietde/Bugs#22]
**Beschreibe den Fehler**
Wenn man als nicht angemeldeter User in den Kommentaren auf den Antworten Button kommt lässt sich die Seite nicht mehr bedienen und kann nur noch per Neuladen weiter bedienen.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Webseite, wenn nötig, im Inkognito Modus aufrufen.
2. Video öffenen
3. Zu den Kommentar scrollen
4. Auf ein Kommentar antworten wollen

**Erwartetes Verhalten**
Verhalten wie beim angemeldeten Benutzer

**Video**
https://streamable.com/ot22w

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 
 - Browser: Chrome, Firefox, Edge (denke mal jeder Browser)
 - Browser-Version: Die aktuellste Version von allen Browser

**Comment by romanzipp** [comment]
Danke für die Meldung! Ist im nächsten Patch gefixt.
