### ISSUE TITLE
Rechtschreibfehler bei Account löschen

### ISSUE THREAD

**Issue by LasseRinstroem** [PietSmietde/Bugs#221]
Rechtschreibfehler bei Account löschen

PietSmiet / Einstellungen / Daten / Account löschen

Bitte stelle sicher, dass du eventuelle Abonnements gekündigt hast, bevor du mit dem Prozess **vorfährst**.

**fortfährst**

**Comment by romanzipp** [comment]
Danke für den Hinweis, wird beim nächsten Patch gefixt sein!
