### ISSUE TITLE
Cookie Banner mit weißer Schrift im Darkmode

### ISSUE THREAD

**Issue by kisimediaDE** [PietSmietde/Bugs#224]
**Beschreibe den Fehler**
Wenn ich den Darkmode aktiviert habe kann man den Text im Cookie Banner nicht mehr lesen, da die Schriftfarbe weiß wird.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Seite öffnen - Cookie Banner nicht wegklicken
2. Anmelden und auf Darkmode umstellen

**Screenshots**
![Bildschirmfoto 2019-11-14 um 11 19 06](https://user-images.githubusercontent.com/5765485/68848536-bd78db80-06d0-11ea-9ba1-1739d04ec94a.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: macOS Catalina 10.15.1
 - Browser: Google Chrome (Version 78.0.3904.97) und Safari (Version 13.0.3)

**Comment by romanzipp** [comment]
Danke für die Meldung, ist demnächst gefixt!
