### ISSUE TITLE
2-Faktor Fehlermeldung (Twitch/Discord Anmeldung)

### ISSUE THREAD

**Issue by mikalonia1** [PietSmietde/Bugs#225]
**Beschreibung**

Wenn ich mich im Login Screen über Twitch oder auch Discord anmelden will und die 2-Faktor Authentifizierung aktiv ist, bekomme ich folgende Fehlermeldung:

**Screenshot**

![image](https://user-images.githubusercontent.com/57991249/69236524-fcf16d00-0b93-11ea-8c13-836cea07f0f5.png)

<table>
  <thead>
    <tr>
     <th>Technische Informationen</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Browser</td>
      <td>Google Chrome (78.0.3904.108)</td>
    </tr>
    <tr>
      <td>Betriebsystem</td>
      <td>Windows 10 Home</td>
    </tr>
  </tbody>
</table>

Natürlich kann ich mich dann normal anmelden, aber dann würden die anderen beiden Login Möglichkeiten keinen Sinn ergeben.

**Comment by romanzipp** [comment]
Es war eine bewusste Entscheidung, dass wir die Login per Sozialen Netzwerken mit der 2-Faktor Authentifizierung deaktivieren. Wir haben demnach keinen Einfluss auf die Sicherheitsfaktoren dieser Netzwerke, wodurch der Sinn eines 2. Faktors verloren geht.
