### ISSUE TITLE
Dynamische Zeiten anstatt liner grading 

### ISSUE THREAD

**Issue by lucsoft** [PietSmietde/Bugs#226]
**Beschreibe das Feature**
![image](https://user-images.githubusercontent.com/11093382/69275246-567d8a00-0bdc-11ea-98a7-c7372702c35a.png)
Der alte boxshadow es würde schöner aussehen wenn der text automatisch auf schwarz umstellt anhand der Helligkeit 

**Gibt es Alternativen?**

**Geht der Vorschlag aus einem bestehenden Problem hervor?**

**Weitere Informationen**
Hier mal nen beispiel (nicht von mir) http://jsfiddle.net/PXJ2C/
 
BTW:
box-shadow: -5px 0px 15px black; ist für sowas besser

**Comment by romanzipp** [comment]
Die Technik aus dem Beispiel arbeitet mit normalen CSS Farben, bei uns ist das komplexer weil die Thumbnails aus natürlich aus Bildern bestehen. Es wäre eine nette Verbesserung, aber ich denke nicht dass es kurzfristig den Weg in das Projekt findet, da es relativ komplex und aufwändig ist, die Durchschnitte und zu verwendende Farbe aus den Thumbnails zu extrahieren und keinen verhältnismäßigen Mehrwert bietet.
