### ISSUE TITLE
Später ansehen (Fehler beim Anzeigen, Hinzufügen und Entfernen)

### ISSUE THREAD

**Issue by Patti2101** [PietSmietde/Bugs#227]
Heyho,
sofern man auf Dashboard -> Später ansehen klickt werden keine Videos angezeigt und wenn man Videos hinzufügen oder entfernen möchte kommt die Fehlermeldung: "No query results for model [App\Models\Videos\Playlist] undefined"

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Chrome (Version 78.0.3904.97 (Offizieller Build) (64-Bit)), Firefox (Version 70.0.1 (64-Bit))

**Comment by romanzipp** [comment]
Wurde gefixt
