### ISSUE TITLE
PietSmiet.DE mit Safari unter macOS oder iOS nicht aufrufbar

### ISSUE THREAD

**Issue by nitaco** [PietSmietde/Bugs#228]
**Beschreibe den Fehler**
Die PietSmiet.DE ist mit Safari unter macOS 10.15.1, iOS 13.2.3 und iPadOS 13.2.3 nicht aufrufbar. Der Traffic wird zwar erfolgreich durch Cloudflare geschickt, man landet dann nach dem erfolgreichen Ladeprozess jedoch auf einer weißen Seite.

Im Element-Inspector in Safari können die app.js und app.css (von VueJS?!) nicht geladen werden und laufen mit dem Fehler "An error occurred trying to load the resource." auf Fehler.

In Google Chrome unter macOS gibt es keine Probleme.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Adressiere auf die https://www.pietsmiet.de in einem aktuellen Safari-Browser auf macOS oder iOS.

**Hinweis:** History, Cache oder Cookies wurden abermals gründlich gelöscht - Fehler existieren trotzdem weiterhin.

**Erwartetes Verhalten**
Der Zugriff wird durch Cloudflare geprüft, läuft auf den eigentlichen Appserver dann auf eine weiße Seite. 

**Screenshots**
![Screen Shot 2019-11-21 at 09 18 16](https://user-images.githubusercontent.com/55355812/69319694-f6b8ca80-0c3f-11ea-86c8-4a5147c6099a.png)
![Screen Shot 2019-11-21 at 09 15 13](https://user-images.githubusercontent.com/55355812/69319695-f6b8ca80-0c3f-11ea-837c-b1df3be3feb2.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: macOS
 - Browser: Safari
 - Browser-Version: 13.0.3

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: iPhone 8 Plus
 - Betriebssystem: iOS 13.2.3
 - Browser: Safari
 - Browser-Version: 13.0.3

**Weitere Informationen**
Problem existiert bei mir seit der Cloudflare Einbindung.

**Comment by romanzipp** [comment]
Wurde behoben
