### ISSUE TITLE
Ausblenden des Mauszeigers.

### ISSUE THREAD

**Issue by ThePocketGamer** [PietSmietde/Bugs#229]
**Beschreibe das Feature**
_Eine klare Beschreibung des Features._

Ich würde mir wünschen, dass wie bei den meisten großen Videostreamanbietern der Mauszeiger zusammen mit den Bedienelementen im Vollbildmodus ausgeblendet wird.

**Gibt es Alternativen?**
_Beschreibe, ob es alternative Lösungen für das Feature geben kann._

Würde mir nicht einfallen.

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
_Bitte beschreibe das Problem, welches mit dem Vorschlag behoben werden soll, wenn vorhanden._

Naja... der Mauszeiger bleibt halt im Bild. 

**Weitere Informationen**
_Weitere Informationen zu dem Featurevorschlag, wenn vorhanden._

Ich habe es in der aktuellen Opera, Edge und Edge Beta(Chromium) Version getestet und der Zeiger ist jeweils nicht verschwunden, ich schreib das mal hier, falls es das Feature bereits gibt.

**Comment by romanzipp** [comment]
Duplicate of #150
