### ISSUE TITLE
Feature: Größere Videodateien übertragen

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#23]
**Beschreibe das Feature**
 Ihr solltet auch die Pakete, von dem Video-Player (sollte MPEG-Dash sein) auf 2 MB oder so (definitiv etwas größeres) aufteilen. Aktuell ist es auf ungefähr 200 KB gesetzt. Ihr habt dadurch aktuell unglaublich viele unnötige Requests! Eure Website zieht dadurch auch deutlich mehr Akku.

**Gibt es Alternativen?**
Meines Wissens nicht.

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Nein.

**Comment by romanzipp** [comment]
Mit der momentanen Videoauslieferung ist es nicht möglich, die Segmentegröße zu erhöhen, da wir eine Aufteilung in Keyframeintervallen machen.
Ich wage auch zu behaupten, dass es kaum einen Unterschied macht, ob viele Requests mit kleinen Datenmengen oder wenige mit größeren Datenmengen ausgeführt werden. Gibt es dazu Statistiken?
