### ISSUE TITLE
Suchleiste wird nicht fokussiert

### ISSUE THREAD

**Issue by manuel3108** [PietSmietde/Bugs#230]
**Beschreibe den Fehler**
Nach einem klick auf die Suche / die Lupe wird die Suchleiste nicht fokussiert.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'https://www.pietsmiet.de/'
2. Klicke auf 'Die Lupe / Das Suchen Symbol'

**Erwartetes Verhalten**
Wenn ich mir schon die Mühe mach mit der Maus auf die Lupe zu klicken, wäre es schön, wenn ich nicht erst noch in die Suchleiste tippen muss, damit ich endlich die Tastatur bedienen kann :D

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: [Linux]
 - Browser: [Chrome]
 - Browser-Version: [Version 78.0.3904.108 (Official Build) (64-bit)]

**Comment by romanzipp** [comment]
Danke für die Meldung, ist behoben und wird demnächst gepatcht!
