### ISSUE TITLE
Infinite-Scroll auf "Ultras"-Seite lädt unendlich Einträge nach

### ISSUE THREAD

**Issue by bejonwe** [PietSmietde/Bugs#233]
**Beschreibe den Fehler**
Wenn man in der Ultras Liste bis zum Ende scrollt versucht das Script unendlich lang weiter neue Einträge auf höheren "Seiten" zu laden. Dies resultiert (korrekterweise) nach kurzer Zeit in einem Rate-Limiting Error.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'PietSmiet/Community/Ultras'
2. Scrolle bis zum Ende.

**Erwartetes Verhalten**
Das Infinite-Scrolling sollte nach einer leeren bzw. besser nach einer Antwort, welche nicht das Limit an Elementen enthält, aufhören Elemente nachzuladen.

**Screenshots**
![image](https://user-images.githubusercontent.com/1766000/69565361-1c81fe80-0fb5-11ea-9363-95dbd7d673a3.png)

**Desktop:**
 - Betriebssystem: Windows
 - Browser: Microsoft Edge (Chromium)
 - Browser-Version: 80.0.334.3 (Official build) dev (64-bit)

**Comment by romanzipp** [comment]
Danke für die Meldung. Ist gefixt und wir die Tage gepatcht!
