### ISSUE TITLE
2-Faktor Authentifizierung QR Code fehlerhaft

### ISSUE THREAD

**Issue by daFailer** [PietSmietde/Bugs#235]
**Beschreibe den Fehler**
Habe meine alte 2-Faktor Authentification deaktiviert. Anschließend diese wieder aktivieren. Beim Scannen des Barcodes bekomme ich folgende Fehlermeldung:

>**Invalid barcode**
>Der Barcode "otpauth://totp/PietSmiet%3A**benutzername**?secret=**schlüssel**&issuer=PietSmiet&period=30&algorithm=SHA1&digits=6 " ist kein gültiger Barcode für ein Authentifizierungstoken.

_Info: Das Leerzeichen vor dem zweiten Anführungszeichen in der Fehlermeldung ist kein Fehler von mir sondern steht so in der Fehlermeldung._

Wenn ich den Schlüssel manuell eingebe, funktioniert es. Der Schlüssel in der Fehlermeldung stimmt auch mit der Zeichenfolge für die manuelle Eingabe überein.

Habe es zwei mal (erfolglos) mit jeweils neu generierten Codes probiert.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'Einstellungen' > '2-Faktor'
2. Klicke auf 'Einrichtung starten'
3. Scanne mit Authentification App den QR Code

**Erwartetes Verhalten**
Da es das letzte mal auch problemlos funktioniert hat. Hatte ich erwartet, dass der Code wie gewohnt eingescannt und das Konto in meiner App hinterlegt wird.

**Website aufgerufen mit:**
OS: Windows 10
Browser: Brave Browser
Browser-Version: 1.0.1 Chromium: 78.0.3904.108 (Offizieller Build) (64-Bit)

**Mit folgenden Geräten | Apps | OS gescannt:**
Huawei Mate 20 Pro | Authy | Android 9 EMUI 9.1
iPhone 6s | Google Authenticator | iOS 13.2.3

**Comment by Maaaxiii** [comment]
Probier es mal mit dem Microsoft Authenticator.

**Comment by romanzipp** [comment]
Ich kann den Fehler auch nicht reproduzieren. Mit mehreren Geräten und Apps ausprobiert

**Comment by daFailer** [comment]
@romanzipp Mein Benutzername lautet dafailer

Habs grade noch mal mit einem iPhone 6s und der Google Authenticator-App probiert. Der Fehler besteht weiterhin.

@Maaaxiii danke für den Tipp, nur finde ich es nicht sonderlich zielführend, wenn ich mir, nur für diesen Case, eine neue Authenticator-App herunterladen muss. Alles andere funktioniert ja wie es soll.
