### ISSUE TITLE
[Bug] Ad's überlappen Navbar on Mobile

### ISSUE THREAD

**Issue by Jusdon** [PietSmietde/Bugs#236]
**Beschreibe den Fehler**
Die Werbung auf dem Handy hat wahrscheinlich einen zu hohen z-index, sodass sie das Menü überlappt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Öffne auf dem Handy das Menü
2. Scroll

**Erwartetes Verhalten**
Menü sollte wenn möglich, einen höheren z-index erhalten.

**Screenshots**
![20191128_110948](https://user-images.githubusercontent.com/34418811/69797871-bb367700-11d0-11ea-827c-b8e69c2c4016.jpg)
![20191128_110927](https://user-images.githubusercontent.com/34418811/69797907-c689a280-11d0-11ea-98de-3a830a49a24d.jpg)

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: Samsung S9+
 - Betriebssystem: Android 9
 - Browser: Chrome Mobile
 - Browser-Version: 78.0.3904.108

**Comment by romanzipp** [comment]
Duplicate of #173
