### ISSUE TITLE
Anzeige der falschen Kommentare im Profil eines Benutzers

### ISSUE THREAD

**Issue by Tanielll** [PietSmietde/Bugs#237]
**Beschreibe den Fehler**
Wenn man das Profil eines Benutzers öffnet, werden nicht mehr wie die ganze Zeit nur die Kommentare dieses Nutzer in seinem Profil angezeigt, sondern irgendwelche anderen Kommentare (einige von euch [Roman und Domi] und einige andere random Kommentare.

**Reproduktion**
Auf den Namen eines Users klicken, um sein Profil zu öffnen und dann unter Kommentare.

**Erwartetes Verhalten**
Es wurden nur die Kommentare des Nutzer, dessen Profil man sich gerade ansieht, angezeigt. Am besten sortiert nach Likes (absteigend) bzw. noch besser: man kann selbst festlegen, wie die Kommentare sortiert werden sollen.

**Screenshots**
![image](https://user-images.githubusercontent.com/54218399/69870507-6b2ee180-12b0-11ea-894a-b1770bcf3b7d.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 Pro Version 1903 (Build-Nr.: 18362.476)
 - Browser: Google Chrome
 - Browser-Version: 78.0.3904.108

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: OnePlus 6
 - Betriebssystem: Android 10 (Oxygen OS 10.0)
 - Browser: Google Chrome
 - Browser-Version: 78.0.3904.108

**Weitere Informationen**
Cache des Browser leeren habe ich bereits probiert und zeigt keine Wirkung.

**Comment by romanzipp** [comment]
Danke für die Meldung. Der Fehler wurde behoben und ist in den nächsten Tagen gepatcht
