### ISSUE TITLE
Anzeige von code auf Webseite 

### ISSUE THREAD

**Issue by NH126** [PietSmietde/Bugs#238]
Problem:
Ich habe die Pietsmiet.de augerufen und habe rechts am Rand anstatt Videovorschlägen nur           eine Zeile Code vorgefunden.

![Neuste Videos _ PietSmiet de - Videos, News und Spiele - Mozilla Firefox 01 12 2019 12_46_38_LI](https://user-images.githubusercontent.com/50210466/69913619-2a62d400-143a-11ea-828a-5d22bda81e49.jpg)

Reproduktion:
vermutlich einmaliger Fehler (nach dem Neuladen der Seite war alles wie immer )

---------> War denke ich ein einmaliger Fehler, wollte euch trotzdem informieren. <-----------------

Desktop:
 - Betriebssystem: Windows 10
 - Browser: Firefox
 - Browser-Version: 70.0.1

**Comment by mikalonia1** [comment]
Selbes auch hier, bei mir wäre es eigentlich O2 Werbung gewesen.

Desktop:

- Betriebssystem: Windows 10
- Browser: Google Chrome
- Browser-Version:  78.0.3904.108

**Comment by romanzipp** [comment]
Wir selbst haben leider kein Einfluss darauf, aber es wird weitergegebene. Danke für die Meldungen!
