### ISSUE TITLE
Video-Seite wird am rechten Rand abgeschnitten in Firefox auf mobilen Geräten

### ISSUE THREAD

**Issue by froseb** [PietSmietde/Bugs#239]
**Fehlerbeschreibung**
Der Seiteninhalt der Video-Übersicht (https://www.pietsmiet.de/videos) wird in Firefox auf Geräten mit bestimmter Bildschirmgröße am rechten Rand abgeschnitten.

Das Problem tritt auf meinem Smartphone auch bei manchen Videos auf (z. B. auf der Seite https://www.pietsmiet.de/videos/57622-0react-chriskika), aber nicht bei allen Videos (z. B. auf https://www.pietsmiet.de/videos/57694-trials-195-brammen nicht).

![fehler](https://user-images.githubusercontent.com/44317686/69968530-e5fb3500-151a-11ea-9cda-0e63f8e3232a.png)

**Reproduktion**
Aufgefallen ist mir der Fehler auf meinem Smartphone bei Firefox für Android im Portrait Mode.

Der Fehler kann auch in der Firefox Desktop-Version mit den Entwickler-Tools (Strg+Shift+M) reproduziert werden, indem die Bildschirmbreite heruntergestellt wird.

**Desktop (mit Entwicklertools)**
 - Betriebssystem: Windows 10
 - Browser: Firefox
 - Browser-Version: 70.0.1 (64 bit)

**Smartphone**
 - Gerät: Honor 9 (STF-L09)
 - Betriebssystem: Android 
 - Browser: Firefox für Android
 - Browser-Version: 68.2.1

**Comment by Zercerium** [comment]
Könnte sich um das gleiche Problem wie hier: https://github.com/webcompat/web-bugs/issues/45936 handeln.

**Comment by romanzipp** [comment]
Sehr interessant, danke! Ich konnte das Problem auch ausschließlich in Firefox reproduzieren.
Werde es mir nachher genauer ansehen.

**Comment by romanzipp** [comment]
Es hat sich um den verlinkten Fehler gehandelt. Ich konnte den bei mir lokal beheben. Wird die Tage gepatcht!
