### ISSUE TITLE
Bug: Doppelter Header bei Fehler 500

### ISSUE THREAD

**Issue by manuel-st** [pietsmietde/Bugs#24]
**Beschreibe den Fehler**
Beim Header von Fehler 500 tauchen die Elemente "Home", "News", "Videos", "Podcast" und "Shop" jeweils doppelt auf.

**Erwartetes Verhalten**
Der Header sieht genauso aus wie bei den anderen Seiten.

**Desktop**
 - Betriebssystem: Ubuntu 18.04
 - Browser: Firefox
 - Browser-Version: 65.0.1

**Comment by manuel-st** [comment]
**Screenshots**
![bug000](https://user-images.githubusercontent.com/36520836/54490642-cdc58600-48b7-11e9-869a-e218cf08bee4.png)

**Comment by romanzipp** [comment]
Ich konnte den Fehler leider nicht reproduzieren. Auf welche Seite genau erscheint der Fehler und auf welcher Auflösung hast du die Seite angesehen?

**Comment by manuel-st** [comment]
Ich hatte einen Fehler 500: Internal Server Error bekommen, als ich die Bestrafung für die zweite Try Not To Laugh-Challange anschauen wollte. Es war kein Video zu sehen, nur die Fehlermeldung.

Die Auflösung ist 1920*1080.

**Comment by manuel-st** [comment]
Es wird wahrscheinlich an der Seite liegen, die bei einem Fehler 500 angezeigt wird und nicht an der Seite von dem Video selbst.

**Comment by romanzipp** [comment]
Natürlich. Ich kann mir gut vorstellen, dass es an einer Kollision während eine Patches lag. Ich werden den Issue erstmal schließen, da ich es nicht reproduzieren kann.
