### ISSUE TITLE
Hohe CPU Auslastung bei Idle

### ISSUE THREAD

**Issue by MoreDelay** [PietSmietde/Bugs#240]
**Beschreibe den Fehler**
Ich habe eine starke CPU Auslastung auf der PietSmiet Website, solange der Tab aktiv ist.
Dabei kann der Browser auch im Hintergrund laufen.
Ich habe das sowohl mit Mozilla FireFox (meinem Hauptbrowser) als auch mit Microsoft Edge feststellen können. Mit Chromium konnte ich scheinbar die Seite gar nicht laden... 
In FireFox sind eine Hand voll Add-Ons installiert, nicht aber in Edge. Der Effekt trat z.B. auch auf, als ich NoScript in FF deaktiviert hatte.
Ich habe ein wenig in Performance, dabei stellte sich heraus, dass FF die ganze Zeit das Style neu berechnet. Auch Edge zeigt an, dass irgendwas in der UI neu eingestellt wird.
Das Ergebnis der ständigen Berechnung: Bei FireFox durchgehend 20% Auslastung der CPU bei sonst 4-5% Auslastung (z.B. anderer aktiver Tab), bei Edge sehe ich auch einen Anstieg von ca. 10% Auslastung. (Wieso hier weniger berechnet wird weiß ich nicht)
Ich spüre keine Beeinträchtigung beim Navigieren der Seite, aber es frisst halt Strom und Prozessorlaufzeit.
Was ich auch zufällig herausgefunden habe: Falls ich die Dev Tools breit mache, dass die oberen Knöpfe "Home, News, Videos, etc." nicht meht angezeigt werden, verschwindet auch das Neuberechnen. Liegt wohl irgendwie mit der Breite der Darstellung zusammen.

**Reproduktion**
Besuche die Website, entweder Start oder Videos-Seite (eigentlich alle Pages, soweit ich das aktuell sehe)

**Erwartetes Verhalten**
Keine Last, da nichts passiert

**Screenshots**
*FireFox Listing*
![Performance Listing](https://user-images.githubusercontent.com/32901482/69981393-84df5b80-1532-11ea-976d-31a82db33aa7.png)

*FireFox Summary*
![Performance Summary](https://user-images.githubusercontent.com/32901482/69981470-adffec00-1532-11ea-81ba-01fe73ceec88.png)

*Edge Listing*
![Performance Listing (ME)](https://user-images.githubusercontent.com/32901482/69982579-1354dc80-1535-11ea-94ef-b15e637ac112.png)

*FireFox Resizing*
![Performance Resizing (FF)](https://user-images.githubusercontent.com/32901482/69983102-2ddb8580-1536-11ea-92ab-dcb5e750d3db.png)
*Hier wird die Phase zwischen zwei mal Resizen gezeigt*
*Achte auf die Graphik oben im Bild, welche die Tasks darstellt*

**Desktop (bitte die Informationen vervollständigen):**
Windows 10 10.0.18362 Build 18362,
FireFox 70.0.1 (64-bit),
Microsoft Edge 44.18362.449.0,
AMD Ryzen 5 1500X CPU (als Referenz)

**Weitere Informationen**
[FireFox Console Export.txt](https://github.com/PietSmietde/Bugs/files/3912489/FireFox.Console.Export.txt)

Hoffe das reicht an Information

**Comment by romanzipp** [comment]
Ich habe ein wenig recherchiert und eine unperformante, geloopte Animation gefunden, die dauerhafte Repaints verursacht hat.
Der Patch wird voraussichtlich die kommende Tage live geschaltet.
