### ISSUE TITLE
Auf dem Profil werden alle Kommentare angezeigt, statt nur denen des Users

### ISSUE THREAD

**Issue by Th0bse** [PietSmietde/Bugs#241]
**Fehler**
Wenn man zu einem beliebigen Profil navigiert, werden statt den Kommentaren des jeweiligen Users _alle_ Kommentare angezeigt, von allen Usern.

**Reproduktion**
Profilseite aufrufen, etwa https://www.pietsmiet.de/profile/6-Domi dort werden dann alle Kommentare angezeigt.

**Erwartetes Verhalten**
Es werden nur die Kommentare des jeweiligen Nutzers angezeigt.

**System:**
 - Betriebssystem: Windows 10 / Android 9
 - Browser: mehrere Chromium-basierte Browser, Firefox, Edge. Chrome und Firefox sowohl mobil als auch Desktop, sprich sicher platformunabhängig.
 - Browser-Version: diverse

**Comment by romanzipp** [comment]
Duplicate of #237
