### ISSUE TITLE
Fehler in der Zählung der Monate (Sprung direkt von "vor 10 Monaten" auf "vor einem Jahr")"

### ISSUE THREAD

**Issue by AntiCedros** [PietSmietde/Bugs#242]
In der Streamübersicht springt die Zählung unter den Streams von "vor 10 Monaten" direkt auf "vor einem Jahr", obwohl "vor 11 Monaten" richtig(er) wäre.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu Videos > Streams > Seite 7 (womöglich Seite 8, wenn Streams dazukommen)
2. Scrolle zum Stream "Civilization 6 mit Brammen, Piet, Chris und Sep - Stream vom 16.01.19"; darunter steht "vor einem Jahr", obwohl der 16.01.19 nicht einmal 11 Monate her ist.

**Erwartetes Verhalten**
Es wird "vor 11 Monaten" oder "vor 10 Monaten" angezeigt statt "vor einem Jahr".

**Screenshots**
![Screenshot_2019-12-03 PietSmiet de - Videos, News und Spiele](https://user-images.githubusercontent.com/53085275/70006494-aa3d8b00-156d-11ea-9e93-3d333666f5e7.png)

**Desktop:**
 - Betriebssystem: Kubuntu 18.04
 - Browser: Firefox
 - Browser-Version: 70.0.1

**Comment by romanzipp** [comment]
Das ist kein Fehler, da die Streams immer Periodenweise auf die Website geladen werden und somit nicht das Datum des Streams haben.
