### ISSUE TITLE
Fehlerhafte Weiterleitung zu eigenen Videos

### ISSUE THREAD

**Issue by themomomo** [PietSmietde/Bugs#243]
**Beschreibe den Fehler**
Verlinkte eigene Videos in der Werbung nicht aufrufbar

**Reproduktion**
1. Navigiere zu einer beliebigen Seite
2. Scrolle nach unten, um die Werbeblöcke zu sehen.
3. Falls vorhanden, klicke auf "React: Superbrain"

**Erwartetes Verhalten**
Weiterleitung auf https://www.pietsmiet.de/videos/55720-0react-superbrain
Dort jedoch keine Autorisierung, das Video zu schauen-

**Screenshots**
![aaaaaaabb](https://user-images.githubusercontent.com/19433977/70237748-269bbe00-1768-11ea-847d-39bda043e87e.PNG)
![aaaaaaaa](https://user-images.githubusercontent.com/19433977/70237750-269bbe00-1768-11ea-836d-fe0bac9bae50.PNG)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: MS Windows 10
 - Browser: Chrome
 - Browser-Version: 78.0.3904.108

**Weitere Informationen**
-

**Comment by romanzipp** [comment]
Das Video musste leider offline genommen werden. Die Verlinkung ist durch einen Servicepartner verursacht, wir haben diesen darüber in Kenntnis gesetzt. Danke für die Meldung!
