### ISSUE TITLE
Autoplay unleserlich

### ISSUE THREAD

**Issue by Doceus** [PietSmietde/Bugs#244]
Im (experimentellen) Dark-Mode ist der Banner mit dem Autoplay-Hinweis sehr schwer zu lesen und daher ist auch der "Abbrechen"-Button nur schwer anzuklicken.

Reproduktion: Immer wenn das Autoplay-Banner erscheint.

Windows 10, Chrome V. 78

Möglicherweise die Farbpalette etwas anpassen um Lesbarkeit zu erhöhen.

**Comment by romanzipp** [comment]
Der Fehler wurde behoben und ist bald gepatcht. Danke für die Meldung!
