### ISSUE TITLE
Werbe-Banner wird nicht korrekt dargestellt.

### ISSUE THREAD

**Issue by SgtChrisCross** [PietSmietde/Bugs#245]
**Beschreibe den Fehler**
Das Background-Werbe-Banner wird komplett schwarz angezeigt, wenn man ganz runter zum Footer scrollt.

**Reproduktion**
Ganz runter zum Footer scrollen. Siehe Screenshots.

**Erwartetes Verhalten**
Sollte richtig angezeigt werden.

**Screenshots**
![image](https://user-images.githubusercontent.com/53583350/70374446-7efec700-18f2-11ea-8c71-8bf73c99fe2d.png)
![image](https://user-images.githubusercontent.com/53583350/70374447-832ae480-18f2-11ea-9ac1-605263715b7c.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 Pro, 64-Bit
 - Browser: Opera GX
 - Browser-Version: LVL1 (core: 64.0.3417.146)
- Browser-Identifikation: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 OPR/64.0.3417.146

Lg Chris Cross

**Comment by romanzipp** [comment]
Der Fehler wurde behoben
