### ISSUE TITLE
Abo ändern

### ISSUE THREAD

**Issue by idnovic** [PietSmietde/Bugs#246]
**Beschreibe den Fehler**
Ich würde gerne den Preis des Abos anpassen. Leider wird mir die Möglichkeit nicht gegeben bei der Reaktivierung.

**Reproduktion**
Kündige ein aktuell bestehendes und nicht ausgelaufenes Abo.
Reaktiviere das Abo direkt danach ohne es auslaufen zu lassen.

**Erwartetes Verhalten**
Abo Preis anpassbar nach der Kündigung bei der Reaktivierung. 

Muss ich warten bis das gekündigte Abo ausgelaufen ist?

**Comment by romanzipp** [comment]
Es ist leider technisch nicht möglich, den Preis eines laufendes Abos zu ändern. Bitte kündige das Abonnement und schließe dann ein Neues mit dem gewünschten Preis ab.

**Comment by idnovic** [comment]
zu meinem Verständnis, das heißt kündigen, dann auslaufen lassen, dann neu abschließen richtig?

**Comment by romanzipp** [comment]
Genau. Leider ist es momentan nicht anders umzusetzen.
Die Vorteile des Abonnements bleiben natürlich aktiv, bis das Abo final ausgelaufen ist.
