### ISSUE TITLE
Löschen von Kommentaren am iPhone geht nicht 

### ISSUE THREAD

**Issue by kisimediaDE** [PietSmietde/Bugs#249]
**Beschreibe den Fehler**
Wollte gerade am iPhone (Safari) einen Kommentar löschen, weil ich mich leider verschrieben habe (Bearbeiten wäre cool: #220). Doch leider kommt nur der Tooltip mit ‚Löschen‘ und sonst passiert nichts. Hab ich jetzt paar mal probiert. 

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu einem Video
2. Schreibe einen Kommentar
4. Versuche ihn zu löschen 

**Smartphone:**
 - Gerät: iPhone XS
 - Betriebssystem: iOS 13.3
 - Browser: Safari

**Comment by romanzipp** [comment]
Ich kann den Fehler nicht reproduzieren. Hast du Popups blockiert oder anderweitig Einstellungen verändert?

![IMG_0970](https://user-images.githubusercontent.com/11266773/73191924-973bd700-4128-11ea-9e29-8debc933a8a4.jpeg)

**Comment by kisimediaDE** [comment]
Hallo,

Habe es jetzt noch einmal getestet. Jetzt bekomme ich auch das Alert. Allerdings wenn ich dann auf ‚OK‘ klicke bleibt das Kommentar da. 
Hab ich zweimal mit reload der Seite probiert.

**Comment by romanzipp** [comment]
Der Kommentar wird nach der Löschung leicht ausgeblendet, ist allerdings für dich noch max. 2 Minuten sichtbar, da er noch im Cache liegt.
