### ISSUE TITLE
Bug: Flowplayer wird noch immer geladen

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#25]
**Beschreibe den Fehler**
Es wird aktuell noch immer der alte Player geladen.
Beispiel: <script src="/vendor/players/flowplayer.commercial-7.2.7/flowplayer.min.js"></script>

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/videos/pietsmiet/52333-try-not-to-laugh-bestrafung-minecraft

**Erwartetes Verhalten**
Flowplayer sollte nicht mehr geladen werden

**Comment by romanzipp** [comment]
Die vorigen Player hatten wir immernoch als Fallback, falls primäre Player nicht geladen werden konnte - momentan aber deaktiviert. Ist gefixt und wird bald gepatcht.
