### ISSUE TITLE
Ständiges Buffering

### ISSUE THREAD

**Issue by sulkeee** [PietSmietde/Bugs#250]
**Beschreibe den Fehler**
Bei eigentlich jedem Video, welches ich auf PietSmiet.de schaue, wird nach wenigen Sekunden gebuffert. Die Auto Funktion stellt sich dann auf 480p oder so und dann funktioniert es teilweilse.
Meine Internet Verbindung ist aber eigentlich gut genug. Ich habe 50mbit upload und 10mbit download. 

**Desktop:**
 - Betriebssystem: Windows 10
 - Browser: Chrome
 - Browser-Version: 79.0.3945.79 (neuste)

**Comment by romanzipp** [comment]
Sofern der Fehler noch nicht behoben wurde, gibt es demnächst ein Update, mit welchem feinere Einstellungen im Player vorgenommen werden können. Dies sollte Performanceprobleme beheben
