### ISSUE TITLE
Neuladen der Seite

### ISSUE THREAD

**Issue by Kown** [PietSmietde/Bugs#251]
**Beschreibe den Fehler**
Wenn man beispielsweise auf der Videos Seite ist und diese neu laden will indem man nochmal auf Videos klickt wird die Seite nicht neu geladen. Ist natürlich nicht nur bei Videos so, sondern bei allen Tabs und Unter-Tabs

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu "Videos"
2. Klicken auf "Videos"

**Erwartetes Verhalten**
Bei klicken auf Videos sollte die Seite neu laden, auch wenn man schon auf der Videos Seite ist.

**Desktop:**
 - Betriebssystem: Windows
 - Browser: Chrome
 - Browser-Version: 79.0.3945.79

**Comment by romanzipp** [comment]
Duplicate of #186
