### ISSUE TITLE
Werbung als Ultra (+ Snob)

### ISSUE THREAD

**Issue by BronaldDumb** [PietSmietde/Bugs#253]
In letzter Zeit habe ich als Ultra und Snob auf Pietsmiet.de wieder volle Werbung. Also sowohl an den Bannern und so, als auch in den Videos. Ich habe gecheckt und die Bezahlung für zB diesen Monat wurde auch abgebucht und die Website zeigt mich noch als ultra an

**Reproduktion**
1. Einloggen
2. Fertig

**Erwartetes Verhalten**
Es wäre cool wenn man die Werbung entfernen könnte

**Screenshots**
<img width="1483" alt="Bildschirmfoto 2019-12-21 um 10 40 42" src="https://user-images.githubusercontent.com/54204227/71306310-e468b280-23de-11ea-855c-e6bd64f001c0.png">
(Mein Profil)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: macOS Catalina
 - Browser: Safari
 - Browser-Version: 13.0.4

**Comment by romanzipp** [comment]
Schreibe uns dazu bitte eine E-Mail an support@pietsmiet.de
