### ISSUE TITLE
2-Faktor-Authentifikation aktiv ohne Möglichkeit diesen zu empfangen.

### ISSUE THREAD

**Issue by TheZockerPlayZRaphael** [PietSmietde/Bugs#255]
**Beschreibe den Fehler**
Wenn ich mich versuche in meinen Pietsmiet.de Account einzuloggen wird von mir eine 2-Faktor-Authentifizierung verlangt, die ich aber deaktiviert habe. Ich habe also keine Möglichkeit einen Authentifizierungscode zu bekommen, benötige jedoch einen um mich einloggen zu können.

**Screenshots**
![chrome_qI3Cc2S80P](https://user-images.githubusercontent.com/24551622/71361862-92698d80-2594-11ea-8a25-33358aeed56d.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Win10
 - Browser: Google Chrome
 - Browser-Version: 79.0.3945.88 (Offizieller Build) (64-Bit)

**Comment by dominovox** [comment]
Schreibe uns dazu bitte eine Mail von der Mailadresse des betroffenen Accounts an support@pietsmiet.de - ich habe das Bild mit der Adresse aus Datenschutzgründen entfernt.
