### ISSUE TITLE
Uploadplan auf Startseite

### ISSUE THREAD

**Issue by Kippenhof** [PietSmietde/Bugs#256]
Ich würde es gut finden wenn man den Uploadplan direkt auf der Startseite sieht.

Als Alternative könnte ich mir auch vorstellen, dass man den neusten Uploadplan immer über den gleichen Link bekommt (z.b. pietsmiet.de/news/uploadplan/newest) und man über den oder einen anderen Link immer auf den neusten weitergeleitet wird.

Ich würde die Funktion gebrauchen können, da ich es so z.b. mir als Lesezeichen hinzufügen kann. Das wär echt Hilfreich

Frohes Fest!

**Comment by MartinV96** [comment]
Das wäre ein äußerst hilfreiches Feature.

**Comment by Kippenhof** [comment]
Ich würde mich auch weiterhin noch über das Feature freuen, Scheint ja ein wenig untergegangen zu sein :/

**Comment by MartinV96** [comment]
Mit pietsmiet.de/uploadplan hast Du jetzt immer den neuesten Uploadplan :)

**Comment by Kippenhof** [comment]
oh, okay Das machts echt um einiges Besser :) auf der Startseite wär natürlich noch ein wenig besser, aber genaugenommen wollte ich ja nicht mehr als das.
