### ISSUE TITLE
Video Fehler bei 1080p

### ISSUE THREAD

**Issue by rehti02** [PietSmietde/Bugs#257]
**Beschreibe den Fehler**
Seit kurzem ist mir aufgefallen, dass in den Videos auf der Pietsmiet.de immer so ein Steifen durch das Bild geht (unten auf dem Screenshot zu sehen). Es sieht aus als ob ein paar Pixel an dieser Stellte in dem Video Fehlen. Der Fehler tritt nur auf, wenn man das Video auf 1080p stellt.

**Reproduktion**
Ein Video auf 1080p ansehen.
Der Screenshot ist aus [diesem](https://www.pietsmiet.de/videos/58257-pietsmiet-allegegenalle-t1-v1) Video.

**Screenshots**
![Fehler Bild](https://user-images.githubusercontent.com/48827346/71526135-a0d9e100-28d5-11ea-9d1c-8b77f3d716c8.PNG)

**Desktop:**
 - Betriebssystem: Windows 10
 - Browser: Chrome
 - Browser-Version: 79.0.3945.88

**Weitere Informationen:**
Mir ist gerade aufgefallen, dass der Fehler nur auftritt, wenn man in den Einstellungen in Chrome die Hardwarebeschleunigung deaktiviert hat. Sobald sie aktiviert ist tritt der Fehler bei mir nicht mehr auf. (Kommt bei mir aber aus anderen gründen nicht in Frage diese auf lange zeit zu aktivieren)

**Comment by romanzipp** [comment]
Danke für die Meldung. Das hört sich stark nach einem speziellen Decodingproblem an, ich denke nicht dass wir von unserer Seite etwas ändern können, dass dieser Fehler nicht mehr auftritt
