### ISSUE TITLE
Bug: Video spielt wegen Fehlern in videojs nicht ab

### ISSUE THREAD

**Issue by manuel-st** [pietsmietde/Bugs#26]
**Beschreibe den Fehler**
Ungefähr jedes zweite mal kann das Video nicht gestartet werden, unabhängig von der Quelle in den Wiedergabeeinstellungen. Nach der folgenden Fehlermeldung zu urteilen, hängt das damit zusammen, dass das Skript zum Laden der Werbung nicht rechtzeitig lädt.
Wenn das passiert, muss die Seite neu geladen werden und man muss hoffen, dass es diesmal funktioniert.

Fehlermeldung:
```
VIDEOJS: ERROR: videojs-contrib-ads has not seen a loadstart event 5 seconds after being initialized, but a source is present. This indicates that videojs-contrib-ads was initialized too late. It must be initialized immediately after video.js in the same tick. As a result, some ads will not play and some media events will be incorrect. For more information, see http://videojs.github.io/videojs-contrib-ads/integrator/getting-started.html video.js:1:100757
	J https://www.pietsmiet.de/vendor/videojs/video.js:1
	error https://www.pietsmiet.de/vendor/videojs/video.js:1
	contribAdsPlugin https://www.pietsmiet.de/vendor/videojs/plugin.ads.js:86
	n https://www.pietsmiet.de/vendor/videojs/video.js:1
	r https://www.pietsmiet.de/vendor/videojs/video.js:1
```

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Ein beliebiges Video auswählen
2. Das Video starten
3. Wenn es sich starten lässt (und eine Werbung zu Beginn angezeigt wird), neu laden, bis es irgendwann nicht mehr passiert

**Erwartetes Verhalten**
Wenn ich auf ein Video klicke, kann ich es mir auch ansehen.

**Desktop**
 - Betriebssystem: Ubuntu 18.04
 - Browser: Firefox
 - Browser-Version: 65.0.1

**Comment by romanzipp** [comment]
Wir haben eine neue Playerversion implementiert. Für Fehler, welche ab jetzt aufkommen bitte einen neuen Issue öffnen.
