### ISSUE TITLE
Fehler beim Aufrufen von 'Neueste Videos' / Aufrufen von PS.de generell

### ISSUE THREAD

**Issue by Henrik2384** [PietSmietde/Bugs#260]
**Beschreibe den Fehler**
2 Fehler:
1. Fehler:
Manchmal, wenn ich eine Seite der neuesten Video laden möchte, wird mir angezeigt, dass kein Video auf dieser Seite gefunden wurde.
2. Fehler:
Tritt ebenso sporadisch auf: Anzeige wie auf dem Screenshot zu sehen (Error 504). 

**Reproduktion**
Schritte um den Fehler zu reproduzieren (für Fehler 1):
1. Navigiere zu 'Neueste Videos'
2. Klicke auf 'Seite xyz'

Für Fehler 2:
1. Pietsmiet.de öffnen/beliebige Seite auf Pietsmiet.de laden.

**Erwartetes Verhalten**
Fehler 1:
Anzeige durch Text: "Kein Videos gefunden :( "
Fehler 2: Anzeige wie auf Screenshot zu sehen (Error 504)

**Screenshots**
![PS-DE Screenshot 02 01 2020](https://user-images.githubusercontent.com/59451921/71686110-8f437e00-2d9a-11ea-8dd8-a124cd104242.PNG)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10; neuestes Update
 - Browser: Firefox
 - Browser-Version: 71.0 
- Build-ID: 20191202093317

**Weiteres**
Ich habe während die Fehler auftraten immer probiert, ob andere Seiten laden. Das war jedes Mal der Fall.
Vielen Dank für PS.de/den Support und viel Erfolg beim Fehler finden :)

**Comment by romanzipp** [comment]
Dieser Fehler kann kurzzeitig bei Netzwerkproblemen auftreten. Beim nächsten Mal einfach ein wenig warten und dann neu laden
