### ISSUE TITLE
Video ,,angesehen"

### ISSUE THREAD

**Issue by Misterfox99** [PietSmietde/Bugs#261]
Ich fände es ganz cool wenn man auch bei den älteren Videos den Status ,,angesehen" bekommt, sobald man sich das Video angeguckt hat. Finde ich bei den neuen Videos nämlich ganz cool, dann weiß man nämlich welches Video man schon geguckt hat. Es war sogar mal für eine kurze Zeit so, aber nach ein paar Tagen war es nicht mehr so. Fände ich ganz nett als kleines Feature :)

**Comment by romanzipp** [comment]
Was meinst du mit "älteren Videos"? Die Funktion ist für alle auf der Website abspielbaren Videos implementiert.

**Comment by Misterfox99** [comment]
Also die Videos die vor 8 Jahren hochgeladen wurden. Aber vielleicht klappt es nur bei mir nicht. Habe auch schon verschiedene Browser ausprobiert.

**Comment by romanzipp** [comment]
Wahrscheinlich meinst du die sehr alten Videos, die nur per YouTube eingebettet sind. Leider ist diese technische Möglichkeit aktuell nicht vorhanden.
