### ISSUE TITLE
Videos ruckeln wenn sie auf dem 2. Monitor abgespielt werden

### ISSUE THREAD

**Issue by Simofi** [PietSmietde/Bugs#262]
**Beschreibe den Fehler**
Videos ruckeln wenn sie auf dem 2. Monitor abgespielt werden

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Ein Video öffnen (z.b. Wer weiß mehr? | DUELL UM DIE GELD)
2. Tab auf den 2. Monitor verschieben
2. Video abspielen 

**Erwartetes Verhalten**
Das Video ruckelt, stoppt manchmal und ist teilweise asynchron.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 1909
 - Browser: Chrome (Problem tritt aber auch bei Edge usw. auf)
 - Browser-Version: 79

**Weitere Informationen**
Radeon 5700XT + neuste Treiber sind installiert
16GB RAM
AMD Ryzen 5 3600
1. Monitor mit der Auflösung 2.560 x 1.440 läuft problemlos
2. Monitor mit der Auflösung 1920 x 1080 Ruckelt
-> Problem tritt nicht bei YouTube auf

**Comment by romanzipp** [comment]
Ich denke leider nicht, dass wir an dem Problem etwas ändern können, da wir kein Vergleichbares Setup zum Testen haben und natürlich nicht jede Hardwarekombination einzeln supporten können.
