### ISSUE TITLE
Ladezeit und Keine automatische Video nachfolge auch mit playlist

### ISSUE THREAD

**Issue by Koelner1** [PietSmietde/Bugs#263]
Ladezeit und Keine automatische Video nachfolge auch mit Playlist
und ständige Abmeldung von der Seite

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'f5'
2. Klicke auf 'viedeo zuende schauen'
3. Pc an und aus machen 

**Erwartetes Verhalten**
War vor Wochen noch alles ok jetzt nicht mehr 

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: [z.B. Windows 10]
 - Browser: [z.B. Chrome]
 - Browser-Version: [z.B. Version 79.0.3945.88 (Offizieller Build) (64-Bit)

**Comment by romanzipp** [comment]
Ich kann den Fehler nicht reproduzieren. Wenn du dein PC zwischendurch neustartest kann es sein, dass die Webseite ihre Statusinformationen verliert. Lade sie in dem Fall einfach neu.

Es kann ebenfalls sein, dass du diese Einstellung deaktiviert hast:
![Screen Shot 2020-03-17 at 11 47 01](https://user-images.githubusercontent.com/11266773/76849085-05f20280-6845-11ea-8ff9-6eb81b8113aa.png)
