### ISSUE TITLE
Bug: Play on tv lädt auf chromecast nicht

### ISSUE THREAD

**Issue by Ironeer** [PietSmietde/Bugs#266]
Vor start des videos wird groß "Play on tv" angezeigt. Wenn ich meinen Chromecast auswähle zeigt der jedoch nur groß "Pietsmiet.de" an, gestreamt wird nichts.

**Comment by romanzipp** [comment]
Die Chromecast Unterstützung funktioniert leider momentan nicht, wir arbeiten daran.
