### ISSUE TITLE
Normalisierung zwischen Werbung und eurem Video

### ISSUE THREAD

**Issue by Voltoviper** [PietSmietde/Bugs#267]
**Beschreibe das Feature**
 Es wäre super, wenn eine Normalisierung zwischen den Videodateien (Werbung und euren Videos) genutzt werden könnte :)

**Gibt es Alternativen?**
Die Werbeclips müssten im Vorwege genauso vom Audio her normalisiert werden, wie die PS-Videos.

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Nicht selten fliegen mir in letzter Zeit die Ohren davon, wenn zwischen dem Video ein Werbeclip läuft. (Sowohl WoT als auch MonsterhunterWorld sind Beispiele hierfür)

**Weitere Informationen**
Aktuell nicht ;)

**Comment by romanzipp** [comment]
Duplicate of #40
