### ISSUE TITLE
Gravatar anbindung

### ISSUE THREAD

**Issue by XanatosX** [PietSmietde/Bugs#268]
**Beschreibe das Feature**
Anbindung an https://de.gravatar.com/ für die Nutzung von Profilbildern

**Weitere Informationen**
Bei Gravatar handelt es sich um ein Seite zum zentralen Verwalten von Profilbildern. Leider gibt es viel zu wenige Seiten die das System kennen.

**Comment by romanzipp** [comment]
Vorerst danke für den Featurevorschlag.

Die Gravatar Einbindung war längere Zeit im Einsatz, dennoch haben wir uns vor Kurzem gegen die Nutzung entschieden, da der Dienst ein - wenn auch minimales - Privatsphärenrisiko beinhaltet, da die URL-Adresse des Gravatar-Profilbilds die E-Mail Adresse des Nutzers per MD5-Hashing beinhaltet, weshalb es durchaus möglich wäre, Nutzer über E-Mail Adresse zu identifizieren.

Eine Diskussion dazu [kann man hier nachlesen](https://meta.stackexchange.com/questions/44717/is-gravatar-a-privacy-risk).

**Comment by XanatosX** [comment]
Gut zu wissen das war mir bis dato nicht bekannt. Ich kann die Entscheidung somit voll und ganz nachvollziehen.

Vielen Dank für die Informationen. Jetzt muss ich mir überlegen ob ich den Dienst überhaupt weiterhin nutzen möchte 👍
