### ISSUE TITLE
Bug: Werbepause ohne Werbung setzt auf 0:00 zurück

### ISSUE THREAD

**Issue by manuel-st** [pietsmietde/Bugs#27]
**Beschreibe den Fehler**
Wenn eine Werbung bei einer Werbepause geladen werden soll, aber dann keine Werbung gezeigt wird, wird die Wiedergabezeit des Videos an den Anfang zurückgesetzt. Dabei wird erst eine Ladeanimation angezeigt, wie auch sonst, wenn Werbung geladen wird. Dann ist der Bildschirm nur noch schwarz und zeigt den Play-Button. Wenn man dann auf den Play-Button drückt, startet das Video wieder vom Anfang, anstatt wie bei einer normalen Pause, an der aktuellen Stelle fortzusetzen.
Ob das bei allen Werbepausen der Fall sein kann, konnte ich nicht überprüfen. Bei mir tauchte das nur bei Werbung in der Mitte auf, aber wenn das am Anfang passiert, ist es ja auch nicht spürbar.
Es hat wahrscheinlich mit den gleichen Änderungen zu tun, die auch #26 verursacht haben.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Video anschauen.
2. Hoffen, dass man bei einer Werbepause in der Mitte des Videos keine Werbung bekommt.
3. Warten, bis die Lade-Animation aufgehört hat.
4. Auf das Play-Dreieck klicken.
5. Das Video beginnt wieder von Anfang.

**Erwartetes Verhalten**
Wenn kein Werbevideo geladen wird, sollte das Video automatisch normal fortgesetzt werden. (Oder es sollte zumindest an der aktuellen Stelle fortgesetzt werden, wenn man auf den Play-Pfeil drückt.)

**Desktop**
 - Betriebssystem: Ubuntu 18.04
 - Browser: Firefox
 - Browser-Version: 65.0.1

**Comment by romanzipp** [comment]
Wir haben eine neue Playerversion implementiert. Für Fehler, welche ab jetzt aufkommen bitte einen neuen Issue öffnen.
