### ISSUE TITLE
Keine neuen Format-Vorschläge

### ISSUE THREAD

**Issue by GniLudio** [PietSmietde/Bugs#271]
**Beschreibe den Fehler**
Es werden keine neuen Formatvorschläge mehr angezeigt.
Der neuste ist bei mir schon 9Tage alt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Klicke auf 'Community'
2. Navigiere zu 'Vorschläge'

**Erwartetes Verhalten**
Auch neuere Vorschläge werden angezeigt/freigeschaltet.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Firefox
 - Browser-Version: 73.0

**Comment by svensen1** [comment]
Das ist schon seit Januar so, ich habe einige Vorschläge eingereicht die bisher nirgendwo aufgetaucht sind. Scheinbar verschwunden im Bermuda Dreieck.
