### ISSUE TITLE
pietsmiet.de wird in IE nicht geladen

### ISSUE THREAD

**Issue by MisterMarlu** [PietSmietde/Bugs#272]
**Beschreibe den Fehler**
Wenn man versucht pietsmiet.de mit dem IE11 aufzurufen erscheint nur eine weiße Seite, da es JavaScript Fehler gibt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Öffne den IE11
2. Gebe "pietsmiet.de" in der url-Leiste ein.

**Erwartetes Verhalten**
Eine Info über den Bildschirm, dass der Browser nicht unterstützt wird. Schließlich ist der Support dafür seit dem 14.01.2020 abgelaufen.

**Screenshots**
![image](https://user-images.githubusercontent.com/15226569/75030604-c124b700-54a4-11ea-8d57-f7d0dee9b0e4.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 Pro
 - Browser: IE
 - Browser-Version: 11

**Weitere Informationen**
Keiner mag den IE.

**Comment by romanzipp** [comment]
Wir bieten keine Unterstützung für den Internet Explorer an und haben dies auch nicht geplant
