### ISSUE TITLE
Tabellen sind nicht responsive

### ISSUE THREAD

**Issue by MisterMarlu** [PietSmietde/Bugs#273]
**Beschreibe den Fehler**
Manche Tabellen sind breiter als mein Fenster im Smartphone und man kann nicht horizontal scrollen.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu "Einstellungen" -> "Sitzungen"

**Erwartetes Verhalten**
Wenn eine Tabelle zu breit für den Inhaltsbereich ist, sollte sie horizontal scrollbar sein.

**Screenshots**
![Screenshot_20200131_235232_com android chrome](https://user-images.githubusercontent.com/15226569/75031059-b61e5680-54a5-11ea-97a0-9416018afdd0.jpg)

**Smartphone:**
 - Gerät: Huawai P20 Lite
 - Betriebssystem: Android 9 (EMUI 9.1.0)
 - Browser: Chrome
 - Browser-Version: 79

**Weitere Informationen**
Jeder Browser verhält sich bei horizontal scrollbaren Tabellen anders.

**Comment by romanzipp** [comment]
Danke für die Meldung. Der Fehler ist im kommenden Patch behoben
