### ISSUE TITLE
Neuladen von Pages nicht ohne F5 möglich

### ISSUE THREAD

**Issue by e-men** [PietSmietde/Bugs#274]
**Beschreibe den Fehler**
Wenn man auf einer Seite ist, kann diese nur mit F5 neugeladen werden, was an sich schade ist, da durch euer Routing das Laden der Inhalte schneller erfolgt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'Videos'
2. Sobald ein neues Video hochgeladen wurde erneut auf 'Videos' klicken

**Erwartetes Verhalten**
Erneutes laden der Videos liste

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10
 - Browser: Chrome
 - Browser-Version: Version 79.0.3945.130 (Offizieller Build) (64-Bit)

**Comment by romanzipp** [comment]
Ich habe noch keine technische Lösung dafür gefunden. Die Videos, News & Podcastlisten können aber mit dem `R` Hotkey neu geladen werden.

Duplicate of #186

**Comment by romanzipp** [comment]
Duplicate of #186
