### ISSUE TITLE
Qualität einstellen bei Videos buggt manchmal

### ISSUE THREAD

**Issue by Florian2905** [PietSmietde/Bugs#275]
Beispiel: https://www.pietsmiet.de/videos/59133-wer-ist-der-beste-bogenschutze

Wenn ich z. B. bei diesem Video auf "1080p" schalte, bekomme ich die Auflösung von "240p". Und umgekehrt eben auch, schalte ich auf "240p" bekomme ich die eigentliche "1080p" Qualität.
![240p](https://user-images.githubusercontent.com/61358807/75096536-c830ef80-55a0-11ea-80f2-96c7bdb9ae39.JPG)
![1080p](https://user-images.githubusercontent.com/61358807/75096537-c8c98600-55a0-11ea-9062-fb349a1b96ab.JPG)

**Comment by romanzipp** [comment]
Habe versucht, den Fehler zu reproduzieren aber leider ohne Erfolg.
Mit welchem Betriebssystem, Prozessor, Browser (+ Version) rufst du die Seite auf?

**Comment by romanzipp** [comment]
Der Fehler wurde behoben
