### ISSUE TITLE
Darkmode

### ISSUE THREAD

**Issue by Phelps-2** [PietSmietde/Bugs#279]
**Beschreibe den Fehler**
Der Darkmode funktioniert auf meinem MacBook nicht mehr.

**Reproduktion**

Der Punkt Darmode erzwingen in den Einstellungen unter Erscheinungsbild ist ausgewählt.

**Erwartetes Verhalten**
Eine Beschreibung des zu erwartenden Verhaltens / Ergebnisses.

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.
(*Screenshots per Drag & Drop hier einfügen*)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: macOS High Sierra Version 10.13.6
 - Browser: Safari
 - Browser-Version: 13.0.4. (14608.4.9.1.4)

**Weitere Informationen**
Auf meinem iPhone X funktioniert der Darmode mit Safari weiterhin.

**Comment by romanzipp** [comment]
Das Fehler wurde im letzte Patch vor wenigen Minuten hinzugefügt, ein Hotfix ist unterwegs
