### ISSUE TITLE
Feature: Darkmode für MacOS (Mit Code)

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#28]
**Beschreibe das Feature**
Patch für den Dark Mode in Safari. Hierbei muss beachtet werden, dass `.bg-ps` in diesem CSS für die obere Navbar ist. Daher müsste vielleicht für die obere Navbar eine eigene CSS angelegt werden.
```
@media (prefers-color-scheme: dark) {
	body {
		background: #565656 !important;
	}
	.bg-ps {
		background-color: #000 !important;
	}
	#navBottom {
		background-color: #222;
	}
	#footer {
		background: #131313 !important
	}
}
```

So sieht es dann in Safari aus:
![Bildschirmfoto 2019-03-27 an 21 08 55](https://user-images.githubusercontent.com/18743976/55108992-0d207d80-50d5-11e9-90cb-4f5fa5ad2aa7.png)

Es sind natürlich noch kleinere Fehler wie z.B. die Icons und auf Mobile ist die untere Navbar noch grün, aber man sollte eine Idee dafür erhalten.

**Comment by romanzipp** [comment]
Die ganzen Techniken haben wir auf dem Schirm, trifft aber die gleiche Antwort zu, wie unter dem 1. Issue bzgl. Darkmode den ich schon geschlossen habe.

https://github.com/pietsmietde/Bugs/issues/5#issuecomment-465468422
