### ISSUE TITLE
Bug: Videos in neuem Tab resultieren in Serverfehler

### ISSUE THREAD

**Issue by TazorDE** [PietSmietde/Bugs#281]
**Beschreibe den Fehler**
Wenn Videos in einem neuen Tab geöffnet werden resultiert das geöffnete Fenster in einem Serverfehler. Ein Reload der Seite mit dem Serverfehler behebt das Problem nicht.  Man muss erneut zu dem Video navigieren und es in dem gleichen Tab öffnen, in dem man ist.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere auf die "Neue Videos"-Seite
2. Klicke mit der mittleren Maustaste auf die Videos, oder öffne das Video über das Kontextmenü in einem neuen Tab

**Erwartetes Verhalten**
Das Video öffnet sich problemlos in einem neuen Tab, sodass es später angesehen werden kann.

**Screenshots**
https://i.imgur.com/dw58ACj.png

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 1903
 - Browser: Mozilla Firefox
 - Browser-Version: Version 73.0.1 (64-Bit)

**Comment by romanzipp** [comment]
Ist behoben
