### ISSUE TITLE
Minify

### ISSUE THREAD

**Issue by t0rkh** [PietSmietde/Bugs#283]
**Beschreibe das Feature**
Eure Javascript und CSS Files werden unminifiziert ausgeliefert. 

**Gibt es Alternativen?**
PurgeCSS und js minifier

**Weitere Informationen**
Ich liebe euch und vuejs

**Comment by romanzipp** [comment]
Kannst du mir die URLs der nicht-minified assets nennen?

Alle aktuellen JS & CSS assets sind durch Terser, babel, PurgeCSS und cssnano optimiert:
<https://www.pietsmiet.de/js/app.1adafbdd7bc3c0a36d95.js>
<https://www.pietsmiet.de/css/app.1adafbdd7bc3c0a36d95.css>

**Comment by t0rkh** [comment]
Ich seh grad, ich hatte irgendwie einen Anzeigefehler, hast Recht, sorry.
