### ISSUE TITLE
Bug: Footer nicht an die Seite fixiert

### ISSUE THREAD

**Issue by YoKoGFX** [PietSmietde/Bugs#29]
**Beschreibe den Fehler**
Der footer ist aktuell nicht an die Website fixiert. Es müsste daher auf `position: absolute; bottom: 0` gesetzt werden.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/login

**Erwartetes Verhalten**
Footer sollte unten auf der Seite sein. (bei 24 Zoll)

**Comment by WizzardMaker** [comment]
Da muss aber aufgepasst werden!

`position: absolute; bottom: 0;`  kann bei kleineren Displays dazu führen, dass der Footer hinter dem eigentlichen Content ist, anstelle unter dem Content.

Zu sehen, wenn man z.B. zoomt, oder das Fenster kleiner macht. Da sollten media-queries (oder andere multi device Methoden) verwendet werden
