### ISSUE TITLE
Buch und Stuhl Links defekt

### ISSUE THREAD

**Issue by floh96** [PietSmietde/Bugs#290]
**Beschreibe den Fehler**
https://www.pietsmiet.de/buch und https://www.pietsmiet.de/stuhl meldet Seite nicht gefunden.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/buch

**Erwartetes Verhalten**
Link zum Buch öffnet sich.

**Comment by dominovox** [comment]
Funktionieren wieder!
