### ISSUE TITLE
Anhalten des Videos nach Lautstärke Änderung

### ISSUE THREAD

**Issue by OreBore** [PietSmietde/Bugs#291]
**Beschreibe den Fehler**
Bei Änderung der Lautstärke wird das Video angehalten bzw. fortgesetzt - wenn man außerhalb des Lautstärkebereichs loslässt.

**Reproduktion**
1. beliebiges Video Starten
2. zur Lautstärkeeinstellung navigieren
3. Verändern der Lautstärke - im Videobereich loslassen

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Win10
 - Browser: Chrome
 - Browser-Version: 81.0.4044.113

**Weitere Informationen**
nach einmaligen klicken in das Video Feld ist der Fehler behoben - für das Video

**Comment by OreBore** [comment]
hei Roman, habt ihr das Problem gelöst? bei mir besteht das Problem immer noch.

**Comment by romanzipp** [comment]
Das ist leider ein Problem, das sich nicht leicht bzw. gar nicht beheben lässt. Solche Sachen treten bei vielen UI Elementen im Web auf. Da es kein erheblicher Fehler ist und ein möglicher Fix u.U. viel Zeit in Anspruch nimmt kann ich die Behebung nicht als Priorität einordnen.
Demnach einfach versuchen, vorsichtiger mit der Lautstärkeregelung umzugehen bzw. einzelne Klicks anstatt "Drag & Drop" vorzunehmen.

**Comment by OreBore** [comment]
Danke für die Antwort :) 
Ihr nutzt doch den kaltura/playkit player. ich schau mal ob ich bei denen mal eine Lösung finde/ anrege. 
Danke für eure Arbeit! <3
