### ISSUE TITLE
Endless Scroller

### ISSUE THREAD

**Issue by lucsoft** [PietSmietde/Bugs#293]
**Beschreibe das Feature**
Anstatt des Pagings soll ein endless scroller hinzufügt werden

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Ja da es für ein seiten wechseln immer neu geladen werden muss

**Comment by OutOfRe4ch** [comment]
Wie soll man in dem Fall dann schnell z.B, an Seite 80 springen? Einige schauen sich gerne mal ältere Videos an und da bot sich bis jetzt die Möglichkeit an die URL entsprechend zu editieren.
Dafür müsste man dann eine extra Funktion einbauen.

**Comment by lucsoft** [comment]
warum willst du auf seite 80 gehen?

**Comment by romanzipp** [comment]
Ich sehe für einen infinite scrolling auf allen Seiten keinen Bedarf

**Comment by OutOfRe4ch** [comment]
um z.B. die ersten Folgen einer Serie zu schauen.

**Comment by lucsoft** [comment]
ja klar abers sowas kann man aber auch kreativer lösen wie zum beispiel "marathon starten" und man spielt die playlist automatisch bei Folge 1 oder den letzten spiel stand

**Comment by lucsoft** [comment]
sowas wie paging ist wirklich ne unschöne lösung und null modern
