### ISSUE TITLE
Playlist-Liste unter Video nicht scrollbar

### ISSUE THREAD

**Issue by DMeisel** [PietSmietde/Bugs#294]
**Beschreibe den Fehler**
Die Playlist-Box unter dem aktuellen Video ist nicht scrollbar. Man kann zwar sortieren, sollten aber mehr als 20 Videos in der Playlist sein, kann man die "mittleren" auch durch sortieren nicht erreichen.

**Reproduktion**
Rufe ein Video in einer Playlist auf.

**Screenshots**
![image](https://user-images.githubusercontent.com/55324488/80266845-63783b00-869e-11ea-8357-633db55cd296.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 
 - Browser: Opera GX
 - Browser-Version: 67.0.3575.130

**Comment by romanzipp** [comment]
Das Verhalte ist erwartet. Um alle Videos der Playlist anzusehen, kannst du auf den Playlisttitel oben links klicken. Die Liste unter dem Video soll nur eine kleine Übersicht der vorigen/nächsten Videos darstellen.

**Comment by DMeisel** [comment]
Es kommt jedoch dazu, dass man das aktuelle Video in der Liste nicht sehen kann, und dann auch nicht welches davor oder danach kommt.
