### ISSUE TITLE
Kommentar Text Box behält Größe nach Absenden des Formulars

### ISSUE THREAD

**Issue by InteraktivClever** [PietSmietde/Bugs#297]
Wenn man die Kommentar-Box groß zieht, um seinen ganzen Text zu sehen, bleibt die Größe unverändert nach absenden des Formulars.

Da die Seite nicht vollständig neu geladen wird, könnte die Lösung evtl. darin bestehen den Formular absenden-Event abzufangen und die Kommentar-Box zu resetten.

**Comment by romanzipp** [comment]
Die Größenänderungen von Textboxen ist eine integrierte Funktion der jeweiligen Browser, welche wir nicht aktiv eingebunden haben. Deshalb würde ich das nicht als Fehler sehen.
