### ISSUE TITLE
Bei mir gehen die Videos wo über 3 Jahre alt sind nicht 

### ISSUE THREAD

**Issue by phantom20p0** [PietSmietde/Bugs#299]
**Beschreibe den Fehler**
Eine klare und knappe Beschreibung, um welchen Fehler es sich handelt.
Wenn ich ein Video von Pietsmiet anschauen will was älter als drei Jahre ist startet das Video nicht 

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu Rainbow six siege Playlist 
2. Klicke auf ein Video wo älter als 3 Jahre ist 

**Erwartetes Verhalten**
Eine Beschreibung des zu erwartenden Verhaltens / Ergebnisses
Das Video lässt sich abspielen 

Screenshots

<img width="1024" alt="Suche nach Rainbow six siege   PietSmiet - Videos, News und Spiele" src="https://user-images.githubusercontent.com/64854572/82041896-3d482880-96a9-11ea-8881-619b20f87e40.png">

**Desktop
 - Betriebssystem: /
 - Browser: /
 - Browser-Version: /

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: IPad 2018
 - Betriebssystem: IOS 13.4.1
 - Browser: Safari
 - Browser-Version: ?

**Weitere Informationen**
Weiter Informationen über das Problem, wenn vorhanden.
Tritt auf wenn man angemeldet ist bei Gast weiß ich es nicht 
Ich habe kein Addon installiert 
Link :https://www.pietsmiet.de/videos/42-dhalu-das-tier-rainbow-six-siege-52?playlist=396-rainbow-six-siege

**Comment by romanzipp** [comment]
Bitte die Informationen aus den Vorlagen ergänzen und nicht löschen.

Welcher Browser, Betriebssystem wird verwendet? Auf welcher URL tritt das Problem auf? Sind Addons installiert? Wie genau sieht der Fehler aus? Tritt es als Gast oder angemeldet auf?

**Comment by phantom20p0** [comment]
Besser ?

**Comment by romanzipp** [comment]
Normalerweise sollte an dieser Stelle der YouTube-Player angezeigt werden, da das Video nur dort verfügbar ist.
Den Fehler kann ich aber leider nicht reproduzieren. Sind in deinem Netzwerk möglicherweise Content Blocker, wie Pihole installiert oder existieren Netzwerkregeln im Router?

![IMG_82FE2263D4B6-1](https://user-images.githubusercontent.com/11266773/82042847-e2afcc00-96aa-11ea-98dd-a5af3162aa3a.jpeg)

**Comment by phantom20p0** [comment]
Nein dann weiß ich jetzt aber warum es nicht geht mein Papa hat mir YouTube gesperrt deshalb 
Aber danke für die Hilfe
