### ISSUE TITLE
Feature Entfernung: Entfernung der Breadcrumbs beim Login und der Registrierung

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#3]
**Beschreibe das Feature**
Wenn man sich einloggen bzw. auch registrieren will, hat man wie auf den anderen Seiten eine Breadcrumb-Navigation. Diese lenkt den Nutzer unnötig ab und sollte auf diesen Seiten nicht notwendig sein.

**Gibt es Alternativen?**
Eine Alternative Navigation auf solchen Seiten wäre ein "arrow-left" icon, welches auf die vorherige Seite führt.

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Nein.

**Comment by romanzipp** [comment]
Ist gefixt, wird gepatcht
