### ISSUE TITLE
Bug: Videoplayer zeigt ständig die selbe Werbung an

### ISSUE THREAD

**Issue by derLesh** [pietsmietde/Bugs#30]
**Beschreibe den Fehler**
Es ist sicherlich kein richtiger Fehler, aber dennoch stört es ziemlich viele.
Seit dem neuen Player (finde ich übrigens super 😉) kommt ständig die selbe Werbung (Days Gone). Egal ob am Anfang oder in der Mitte. Das wird nicht irgendwann nur nervig, sondern hält mich auch vom gucken ab (Nicht wegen der Werbung, sondern weil es 30sek sind die ich mehrfach gesehen hab und nicht überspringen kann). Auch merkt sich die Seite nicht, ob ich schon mal vor kurzer Zeit eine Werbung gesehen hab. So werde ich beim Starten eines Videos direkt mit Werbung begrüßt und wenn ich eine Sekunde später nach dem die Werbung vorbei ist die Seite wieder neulade, bekomme ich direkt die selben 30 Sekunden Werbung abgespielt. 

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
Pietsmiet,de öffnen und ein Video abspielen

**Erwartetes Verhalten**
- Unterschiedliche Werbung
- Merken, ob man schon eine Werbung gesehen hat

**Weitere Informationen**
Das Problem ist nicht nur mir aufgefallen, sonder vielen anderen die unter die Videos Kommentare schreiben

**Comment by romanzipp** [comment]
Es wurde ein Cooldown eingebaut, womit Werbungen nicht häufig nachheinander angespielt werden können.
