### ISSUE TITLE
Keine Werbung(iOS)

### ISSUE THREAD

**Issue by SnowLeoo** [PietSmietde/Bugs#300]
**Beschreibe den Fehler**
Ich bekomme Werbung, allerdings ist diese nur 2 Sekunden lang und die Werbung ist schwarz. Nach den 2 Sekunden spielt sich das Video automatisch ab.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1.Einfach ein Video starten. 

**Erwartetes Verhalten**
Eigentlich sollte ja Werbung erscheinen die normalerweise so um die 10 Sekunden lang ist.!

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.
(*Screenshots per Drag & Drop hier einfügen*)

[image](https://user-images.githubusercontent.com/49914615/81473645-2c5a6b80-9200-11ea-9389-09020101848f.jpeg)

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: iPhone11
 - Betriebssystem: iOS 13.4.1
 - Browser: Safari (Bei z.B.der Mobile App von DuckDuckGo krieg ich gar keine Werbung)
 - Browser-Version: Weiß leider nicht wo der User-Agent steht.

**Weitere Informationen**
- Bin nicht angemeldet
- Habe kein Pi-Hole
- Kein AdBlocker
- Default DNS

**Comment by romanzipp** [comment]
Danke für die Meldung, das kann allerdings Standardverhalten sein, wenn keine Werbung zum Ausspielen zur Verfügung steht
