### ISSUE TITLE
Video "something went wrong", blackscreen

### ISSUE THREAD

**Issue by DarkZoomy** [PietSmietde/Bugs#301]
**Beschreibe den Fehler**
Beim schauen eines Fehlers auf pietsmiet.de erscheint nach unabhängiger Zeit der Fehler "Something went wrong". Dies sieht so aus: Blackscreen mit einer Wolke mit einem Blitz, Something went wrong steht darunter. 
Der Ton läuft während dessen weiter.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu einem Video.
2. Klicke auf das Zeichen für Vollbild.

**Erwartetes Verhalten**
Sehen von Videomaterial.

**Screenshots**
Ich würde gerne welche anhängen. Leider ist mir unbekannt, ob dies am Smartphone funktioniert.

**Smartphone:**
 - Gerät: Xiaomi Mi A3
 - Betriebssystem: Android 9, Android One Oberfläche
 - Browser: Firefox Nightly
 - Browser-Version: Nightly 200506 06:01 (Build #2015738675)

**Weitere Informationen**
Dieser Fehler trat bei der Funktion "Zum Startbildschirm hinzufügen", welche die Website ähnlich einer App anpasst, auf. Dies passiert willkürlich.

**Comment by romanzipp** [comment]
Tritt der Fehler nur unter Firefox Nightly (welche Version genau?) auf?

**Comment by DarkZoomy** [comment]
Da Firefox Nightly mein main Browser ist, kann ich das schlecht beantworten. Ich teste es mal bei Chrome, Opera Touch und Tor aus. Ich melde mich per Kommentar dann erneut. 

Hier alle Infos über die Firefox Version. Ich weiß nicht, welche davon wichtig sind:

Nightly 200514 06:00 (Build #2015740211)
42.0.20200513162226, 956bc5f9b
GV: 78.0a1-20200513094918
AS: 0.58.2

**Comment by romanzipp** [comment]
Firefox Nightly ist eigentlich eine instabile Preview Version des Browsers, weshalb es mich nicht wundern würde, wenn dort Fehler auftreten. Normalerweise testen wir auf solchen Versionen nie, da sich die Nutzer im Klaren sein sollten, dass dort öfter Probleme auftreten

**Comment by DarkZoomy** [comment]
Das bin ich auf jeden Fall. Nur ging dies vor einer gewissen Zeit noch problemlos (ein paar Wochen). Vor allem tritt dieser Fehler nur bei pietsmiet.de auf und bei keiner anderen Video-Sharing Website.
