### ISSUE TITLE
Zwei Faktor Einrichtungsprozess bleibt hängen (Recovery Codes werden nicht angezeigt)

### ISSUE THREAD

**Issue by TheAkio** [PietSmietde/Bugs#306]
**Beschreibe den Fehler**
Wenn man 2FA aktiviert wird der Button ausgegraut, die 2FA zwar aktiviert, aber die Seite bleibt hängen. Die Recovery-Codes enthält man dadurch dann nicht.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/settings?page=twofactor und aktiviere die Zwei-Faktor-Authentifizierung
2. Klicke auf 'Einrichtung starten'
2. Mit einer 2FA App den Code scannen bzw. den Schlüssel eingeben und den angezeigten Code eingeben
2. Klicke auf 'Einrichtung abschließen'

**Erwartetes Verhalten**
Die 2FA wird aktiviert und die Recovery Codes werden angezeigt.

**Screenshots**
Der Button bleibt ausgegraut:
![image](https://user-images.githubusercontent.com/6199741/81725532-4311f400-9486-11ea-8ae6-026ea5b1d3f3.png)

**Desktop:**
 - Betriebssystem: Windows
 - Browser: Firefox
 - Browser-Version: 76

**Weitere Informationen**
Folgender Fehler erscheint in der Konsole:
![image](https://user-images.githubusercontent.com/6199741/81725572-545b0080-9486-11ea-8c84-7b8a3b9125c4.png)
Man kommt an die Recovery Codes über den Netzwerktab der DevTools trotzdem noch dran. Dort sieht man, dass der Objektschlüssel eigentlich `recovery_codes` und nicht `recoveryCodes` sein sollte:
![image](https://user-images.githubusercontent.com/6199741/81726016-f975d900-9486-11ea-9e6f-c1f82bd5a487.png)

**Comment by romanzipp** [comment]
Danke für die Meldung. Das Problem wurde behoben und wird im Laufe des Tages gepatcht.
