### ISSUE TITLE
Unsichtbare Kommentare

### ISSUE THREAD

**Issue by Unnon1989** [PietSmietde/Bugs#307]
**Beschreibe den Fehler**
Teilweise verschwinden die Kommentare auf die man geantwortet hat. Die Kommentare ansich sind wohl noch weiterhin vorhanden da man Benachrichtigungen erhält wenn jemand darauf antwortet. Bisher ist das immer dann passiert wenn der Kommentar ganz unten angekommen ist und eine neue Kommentar Seite benötigt wird. Die Kommentare werden dann teilweise wieder sichtbar sobald man "älteste zuerst anzeigen" aktiviert.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 [aktuelle Version]
 - Browser: Firefox 76.0.1 (64-Bit)

**Comment by romanzipp** [comment]
Danke für die Meldung. Der Fehler ist bereits bekannt und es wird an einer Lösung gearbeitet

**Comment by Apokya** [comment]
Bei werden sie immer noch nicht / oder wieder nicht mehr gepostet. Ist der Fehler neu?

**Comment by fabian310** [comment]
Bei mir besteht der Fehler auch noch. Oder gibt es sowas wie Shadow-Bans wovon der Nutzer nichts mitbekommt?

**Comment by Unnon1989** [comment]
> 
> 
> Bei mir besteht der Fehler auch noch. Oder gibt es sowas wie Shadow-Bans wovon der Nutzer nichts mitbekommt?

Scheint wohl tatsächlich an sowas wie n Filter zu liegen da sobald bestimmte Begriffe gepostet werden die Kommentare nicht angezeigt werden. Der Filter scheint dabei aber bissjel überempfindlich zu reagieren und zu viel zu Filtern.

**Comment by Apokya** [comment]
Das fänd' ich auch nicht weiter schlimm, wenn sie viel filtern. Allerdings bekommt man keine Meldung darüber, warum er nicht erscheint.
Leidglich "Kommentar gepostet".

Wenn dort stehen würde "Kann nicht gepostet werden, weil ..." wäre es für uns User wesentlich einfacher :)

**Comment by K1ngL0u1** [comment]
Wir können eine Liste zusammentragen an Wörtern die weggefiltert werden, ich fange an:

nervt
leider

**Comment by romanzipp** [comment]
Es gibt bestimmt Wörter, die auf der Blocklist stehen um beleidigende Inhalte oder Spam vorzubeugen. Wenn ein Kommentar zur Prüfung nicht öffentlich angezeigt wird erscheint bewusst keine Meldung, damit es schwieriger möglich ist, diese Liste zu umgehen. Vor allem ist diese Maßnahme wichtig gegen Spam-Bots, mit welchen wir in der Vergangenheit einige Probleme hatten.

Das hier besprochene Problem ist allerdings nicht die Ursache für alle unsichtbaren Kommentare. Dies ist ein Fehler zusammenhängend mit der Auflistung & Sortierung von Kommentaren und deren Antworten, an welchem - wie gesagt - gearbeitet wird.

**Comment by romanzipp** [comment]
> Bei mir besteht der Fehler auch noch. Oder gibt es sowas wie Shadow-Bans wovon der Nutzer nichts mitbekommt?

Wir haben kein Shadow-Ban System. Wurde ein Nutzer für beleidigende Inhalte blockiert, wird es diesem auch klar an den entsprechenden Stellen zur Interaktion erkenntlich gemacht.

**Comment by romanzipp** [comment]
Der Fehler wurde behoben, Patch mit Bugfix folgt die Tage
