### ISSUE TITLE
YouTube Player

### ISSUE THREAD

**Issue by MoweME** [PietSmietde/Bugs#308]
**Beschreibe das Feature**
YouTube Player (für Snobs/Ultras)

**Gibt es Alternativen?**
Ich fände es auch angemessen, dieses Feature nur für Snobs/Ultras freizugeben, da über eingebettete YouTube Player meines Wissens nach, nicht häufig bis nie Werbung gespielt wird.

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Ich finde es schön, wenn ich meinen YouTube-Verlauf vollständig habe.

**Weitere Informationen**
Wichtig wäre mir, dass man es permanent in den Einstellungen des Benutzerkontos einstellen könnte.
Da die Videos erst nach 2h auf YT landen, wäre es auch okay, wenn vor dem YT Release der PS-Player über die PietSmiet Server genutzt wird.

**Comment by romanzipp** [comment]
Es gibt keine Möglichkeit für uns, den YouTube Player für die Seite zu nutzen, da die Videos auf YouTube zu verschiedenen Zeitpunkten veröffentlicht werden und wir die Videos der PietSmiet.de selbst hosten.

**Comment by MoweME** [comment]
Tut mir leid, wenn es so harsch wirkt, aber: Hast du mir meine Anfrage überhaupt durchgelesen?

Ich habe doch geschrieben, dass man die Videos vorher über PS-Server schauen könnte.
Desweiteren will ich nochmal darauf hinweisen, dass es Uploads gibt, wo der YT-Player genutzt wird, zudem ist 4K Streaming nicht über eure Seite möglich...

**Comment by romanzipp** [comment]
Ja, die Anfrage hab ich schon verstanden. Es macht für uns allerdings wenig Sinn, die Player zu vermischen, da auch einige interne Funktionen, wie tracken des Videofortschritts, damit nicht möglich sind.

**Comment by MoweME** [comment]
Video tracking funktioniert doch wunderbar?: https://developers.google.com/youtube/iframe_api_reference?hl=de
