### ISSUE TITLE
Nicht aktualisierung der Uploadpläne

### ISSUE THREAD

**Issue by Krieger2311** [PietSmietde/Bugs#309]
**Beschreibe den Fehler**
Wenn man die Seite neu aufmacht und aktualisiert, aktualisiert sich auf der Rechten Seite die Uploadpläne nicht. Mann muss erst extra über "News" auf Uploadpläne gehen, damit die einen auf der "Neusten Videos" aktualisiert angezeigt wird.

**Reproduktion**
1. Unter "Videos" auf "Neuste Videos"
2. Aktualisieren

Was hilft:
3. Auf "News" und dann "Uploadpläne"
(4. Auf den neusten Uploadplan klicken) //Nicht drauf geachtet, ob der Schritt von nöten ist
5. Schritt 1.

**Erwartetes Verhalten**
Gleichermaßiges Verhalten der Aktualisierung wie die Videos.

**Screenshots**
- / -

**Desktop (bitte die Informationen vervollständigen):**
 - Windows 10
 - Firefox
 - 76.0.1 (64-Bit)

**Smartphone (bitte die Informationen vervollständigen):**
 - Huawei P30 Pro
 - Android 10
 - Firefox
 - 68.8.0

**Weitere Informationen**
- / -

Edit: "Beschreibe den Fehler" aktualisiert aufgrund Fehler meiner Seite; "Reproduktion" hinzugefügt.

**Comment by OreBore** [comment]
Passiert der gleiche Fehler, wenn du Strg + F5 zum Aktualisieren nutzt?

**Comment by Krieger2311** [comment]
Jou, passiert das gleiche. Habs grade nochmal Probiert. Uploadplan wird erst im "Neuste Video" Tab trotz mehrfachen Aktualisierung angezeigt nachdem ich unter "News" auf "Uploadplan" geklickt habe.

**Comment by OreBore** [comment]
Das wundert mich. Eigl. sollte Strg. +F5 den Browser Cache überschreiben. Ich schau Mal ob ich Zuhause den Fehler reproduzieren kann.

**Comment by romanzipp** [comment]
Die Module der rechten Seitenleiste werden für 10 Minuten im Local Storage des Browsers gespeichert. Anscheinend hat es dort nicht richtig funktioniert, die Daten zu aktualisieren

**Comment by Krieger2311** [comment]
Hatte ich bis jetzt, hätte ich vielleicht erwähnen sollen, schon öfters gehabt. Mir ist es irgendwann mal vor einer Woche oder länger aktiv aufgefallen.
