### ISSUE TITLE
Zurückspulen per Pfeiltasten

### ISSUE THREAD

**Issue by Krieger2311** [PietSmietde/Bugs#310]
**Beschreibe den Fehler**
Wenn ich ein Video per Pfeiltastern z.B. um 2 Minuten zurück spulen möchte und ich deswegen die Linke Pfeiltaste spamme, befindet sich das Video irgendwann im Loop zustand, so dass ich die Seite neu laden muss um das Video weiter zugucken.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Video angucken
2. Oft hintereinander die Linke Pfeiltaste zum Zurückspulen verwenden
3. Loop sehen

**Erwartetes Verhalten**
Zurück spulen ohne Loop effekt und einfach von dort weiter gucken.

**Screenshots**
- / -

**Desktop (bitte die Informationen vervollständigen):**
 - Windows 10
 - Firefox
 - 76.0.1 (64-Bit)

**Smartphone (bitte die Informationen vervollständigen):**
- / -

**Weitere Informationen**
- / -

**Comment by romanzipp** [comment]
Ich kann den Fehler nicht reproduzieren. Allerdings würde ich auch vorschlagen, dass du diese Funktion nicht mehr nutzt, wenn es für dich Probleme bereitest. Für die Lösung dieses potentiellen Fehlers müssten wir voraussichtlich relativ viel Zeit aufbringen.
