### ISSUE TITLE
History Eintrag erstellen wenn man die nächste Seite Videos anschaut

### ISSUE THREAD

**Issue by autoantwort** [PietSmietde/Bugs#311]
**Beschreibe das Feature**
Wenn man in der [neuen Videos Ansicht](https://www.pietsmiet.de/videos) die Seite wechselt sollte ein History Eintrag erstellt werden ([Vue router push](https://router.vuejs.org/guide/essentials/navigation.html#router-push-location-oncomplete-onabort)). Wenn ich auf Seite 2 gehe und wieder zurück gehe will ich wieder auf Seite 1 landen.

**Gibt es Alternativen?**
Seitennummer in die URL reinschreiben, braucht man aber nicht unbedingt, da man über `param` des Routers und `props` der Komponente das auch einfach nur intern weitergeben kann. 

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Wenn ich auf Seite 2 gehe drückt ich oft auf Zurück, bzw. wische mit zwei Fingern nach links (macOS Geste für zurück) um wieder auf die erste Seite zu kommen, was mich aber sonst wo hin bringt da es kein history Eintrag für Seite 1 gibt.

**Comment by romanzipp** [comment]
Bitte keine Duplikate eröffnen. Bei der Anmerkung in #303 ging es darum, die Informationen des Systems zu ergänzen, da dieses Feature bereits existiert und nach meinen Tests auch funktioniert.

**Comment by autoantwort** [comment]
Oh hatte in Erinnerung, dass es unabhängig davon noch nicht möglich war

**Comment by autoantwort** [comment]
Ist kein Duplikat vom #303. Selbst wenn die History und die URLs normal funktionieren, ändert sich zwar die URL (der Query Parameter), aber es wird keine neuer History Eintrag erstellt. Könnt natürlich sagen das wollt ihr nicht.
