### ISSUE TITLE
Bot Unterstützung für Uploadplan

### ISSUE THREAD

**Issue by Unnon1989** [PietSmietde/Bugs#313]
**Beschreibe das Feature**
Es wär schön wenn man für den Uploadplan eine Bot Unterstützung einführen könnte. Warum? Wenn man z.B. auf Discord unterwegs ist wärs nice wenn man einen Channel haben könnte der jeden morgen den Uploadplan von der ps.de Website postet.

Umsetzen könnte man das ganze z.B. über n WebHook oder alternativ über RSS-Links die von Bots gelesen werden können.

**Comment by romanzipp** [comment]
So eine Funktion ist nicht geplant
