### ISSUE TITLE
Kommentare werden nicht gespeichert

### ISSUE THREAD

**Issue by hanselpeter** [PietSmietde/Bugs#314]
Mir ist in den letzten Tagen mehrfach passiert, das Kommentare, die ich poste nicht gepeichert werden.

es wird zwar gemeldet, das der Kommentar gepostet wurde, aber er erscheint dann nicht auf der betreffenden Seite. Auch nach mehrfachem Reload nicht.

Mittlerweile kopiere ich meine Kommentare bereits jedesmal bevor ich sie abschicke, da es beim zweiten Mal meist klappt. Aber vorhin klappte es selbst beim zweiten Mal nicht.

Leider kann ich euch keine Steps zur Reproduktion an die Hand geben, da es random erfolgt.

Achja: Auf pietsmiet.de bin ich unter dem Nick "papuaneuginea" unterwegs. Vielleicht ist es ja auch ein Problem mit meinem User.

**Comment by romanzipp** [comment]
Es handelt sich nicht um einen Bug sondern die automatisierte Filterung anhand von Keywords. Es ist nie eine gute Idee, Kommentare mehrmals abzusenden ohne dass eine Fehlermeldung erscheint.

**Comment by hanselpeter** [comment]
Dann gebt doch bitte eine vernünftige Fehlermeldung aus. Die Seite sagt mit jedesmal "Kommentar gepostet". Sorry, das ist murks. Das lernt jeder Fachinformatiker-Azubi im ersten lehrjahr.

**Comment by OutOfRe4ch** [comment]
Wäre dann vielleicht sinnvoll eine Fehlermeldung zu senden, z.B.: "Der Kommentar enthält nicht geduldete Wörter."
