### ISSUE TITLE
Fehlende Recovery Codes

### ISSUE THREAD

**Issue by schoenfeldj** [PietSmietde/Bugs#316]
**Beschreibe den Fehler**
Ich habe zwei mal die 2-Faktor Authentifizierung aktiviert und beide male wurden mir keine Recovery Codes angeboten. Nach der Eingabe des erstellten 6-stelligen Codes ist nichts weiter passiert. Anschließend war die 2-Faktor Authentifizierung jedoch aktiv. Die Bestätigungsmail ist angekommen. 

**Reproduktion**
1 .Aktiviere die 2fa und scanne den Code bzw. kopiere den Code in das entsprechende 2fa Programm (in meinem Fall Bitwarden)
2. Gebe dann den ersten Code auf Pietsmiet.de ein, um die Aktivierung abzuschließen.
3. Dann passiert schlicht nichts mehr, außer das die Mail verschickt wird.

**Erwartetes Verhalten**
Ich hätte erwartet, dass anschließend die Seite neu geladen bzw. die Einrichtung bestätigt wird und dann die Codes entweder angezeigt oder z.B. per Mail verschickt werden. 

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.
(*Screenshots per Drag & Drop hier einfügen*)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: [z.B. Windows] Windows
 - Browser: [z.B. Chrome, Safari] Chrome 81.0.4044.138 , Firefox 76.0.1

**Weitere Informationen**
Die 2fa war jedoch aktiv, das hat geklappt. Ich konnte mich auch einloggen und so weiter. Es kam nur keine Bestätigung und die Codes wurden nicht angezeigt, zugestellt etc.

**Comment by romanzipp** [comment]
Danke für die Meldung. Das Problem wurde behoben und wird im Laufe des Tages gepatcht.
