### ISSUE TITLE
Video lädt nicht direkt.

### ISSUE THREAD

**Issue by DennisI511** [PietSmietde/Bugs#320]
Sollte ich auf ein Video klicken per Pietsmiet.de Homepage, lädt das Video nicht. Erst wenn ich rechts auf ein anderes Video klicke und dann wieder auf das andere Video, funktioniert es. (Bei Neuladen der funktionierenden Seite geht es dann wieder nicht)

 - Betriebssystem: Windows
 - Browser: Chrome
 - Browser-Version: ka neuste

Der Fehler ist erst aufgetreten, nachdem der PIetsmiet Server "down war" (vor 2-4 Wochen)

**Comment by romanzipp** [comment]
Das sind leider zu wenig Informationen, damit wir das Problem angehen können.
- Hast du Extensions/Add-Ons im Browser installiert? Wenn ja, welche?
- Sind Inhaltsblocker, wie Kindersicherungen o.ä. im Netzwerk installiert?
- Kannst du den Fehler möglicherweise in anderen Browsern reproduzieren?
