### ISSUE TITLE
Doppelte User unter Community>Ultras

### ISSUE THREAD

**Issue by BrainOverflowDE** [PietSmietde/Bugs#321]
### Beschreibe den Fehler

In der Liste der User unter Community>Ultras werden viele User mehrfach angezeigt.

### Reproduktion

s.o.

### Erwartetes Verhalten

Jeder User nur einmal um eine echte Liste zu erhalten.

### Screenshots

![2020-06-03 11_39_06-Window](https://user-images.githubusercontent.com/28710040/83621933-9eb83480-a58f-11ea-8e85-f8bb84a24b88.png)
![2020-06-03 11_39_24-Window](https://user-images.githubusercontent.com/28710040/83621945-a24bbb80-a58f-11ea-95a5-b39888903962.png)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Win 10
 - Browser: Google Chrome
 - Browser-Version: Version 83.0.4103.61 (Offizieller Build) (64-Bit)
 - Extensions/Add-Ons installiert: uBlock

### Weitere Informationen

eventuell User nach Zeit sortieren ?

**Comment by BrainOverflowDE** [comment]
Ein weiteres Beispiel ist hier mit dem passenden HTML dazu, man suche nach "Pascal_Pradel".
[Ultras_HTML.txt](https://github.com/PietSmietde/Bugs/files/4722753/Ultras_HTML.txt)

**Comment by romanzipp** [comment]
Duplicate of #394
