### ISSUE TITLE
Falsche Videovorschläge

### ISSUE THREAD

**Issue by jankumme** [PietSmietde/Bugs#324]
Bei den vorgeschlagenen Videos unter dem Uploadplan werden manchmal Videos vorgeschlagen, welche wahrscheinlich noch nicht erschienen sind, siehe Bild. Wenn man dann versucht dieses Video zu öffnen, funktioniert dies nicht.
![Screenshot_20200607_232114](https://user-images.githubusercontent.com/66573742/83980519-e257c900-a916-11ea-9c23-2cd6289a74a2.jpg)
Liebe Grüße

**Comment by romanzipp** [comment]
Danke für die Meldung! Dabei handelt es sich um die Einbettung eines Partners, wobei vereinzelt auch nicht mehr verfügbare Videos gelistet werden. Wir haben keinen direkten Einfluss darauf aber leiten es weiter.
