### ISSUE TITLE
Uploadplan Thumbnail Erneuerung

### ISSUE THREAD

**Issue by MartinV96** [PietSmietde/Bugs#325]
### Beschreibe das Feature

Erneuerung des Uploadplan-Thumbnails aufgrund der Änderung des Erscheinungsbildes der Jungs in den letzten Jahren.

Altes Thumbnail:
![PS de](https://user-images.githubusercontent.com/55382951/84053360-159b6600-a9b2-11ea-83a7-93aa2cd9ee27.jpg)

Vorschlag für neues Thumbnail (wie beim neuen YT-Kanal "PietSmiet Live"):
![PSLive](https://user-images.githubusercontent.com/55382951/84053451-32379e00-a9b2-11ea-9ffc-72a292e658bc.png)

**Comment by dominovox** [comment]
Das ist Sache der Redaktion (Sven), nicht der Technik. Wird weitergegeben.
