### ISSUE TITLE
Splittesting für Titelwahl

### ISSUE THREAD

**Issue by Dojagames** [PietSmietde/Bugs#327]

**Comment by Dojagames** [comment]
weißt du was splittesten ist?

**Comment by romanzipp** [comment]
Im Normalfall formuliert man Bugreports und Vorschläge aus. Sollte es dir darum gehen, dass wir A/B Testing für diverse Videotitel einsetzen sollten um diverse Performances zu testen ist dies eine interne Entscheidung.
