### ISSUE TITLE
möglichkeiten clips/ Ausschnitte von Videos zu erstellen / herunterzuladen 

### ISSUE THREAD

**Issue by Dojagames** [PietSmietde/Bugs#328]
Ein solches Feuture würde Community Contributions vereinfachen/ ermöglichen

**Comment by SuperNyr0** [comment]
Meinst du so etwas?

![clip](https://user-images.githubusercontent.com/52377842/86175021-f44a1780-bb22-11ea-9f27-4550dc3addca.jpg)
