### ISSUE TITLE
PC Verlinkung geht nicht

### ISSUE THREAD

**Issue by DThommy** [PietSmietde/Bugs#329]
Hallo zusammen,

unter jedem Video habt ihr eine Verlinkung auf die Pietsmiet PCs.
Klickt man auf diesen kommt man zum PietsmietSnob Angebot.
Sucht man dann auf der Homepage weiter nach PCs so findet man nichts.
Bei Stühlen wird man zu Maxnomic weitergeleitet, das funktioniert ohne Probleme.

Soll das so? Oder gibt es aktuell einfach keine Kooperation?

**Comment by Gameniti** [comment]
Gefährliches Halbwissen, aber Brammen meinte in einem Stream, dass die Kooperation ausgelaufen ist (bzw. zu dem Zeitpunkt noch lief, aber halt ausläuft) und sie derzeit an einer neuen verhandeln. Denke also, dass der Link tot ist und sie den ps.de/pcs auf den Snob Link umgeleitet haben.

**Comment by romanzipp** [comment]
Was @Gameniti sagt ^^
