### ISSUE TITLE
Bug: Fehlende Übersetzung

### ISSUE THREAD

**Issue by YoKoGFX** [PietSmietde/Bugs#33]
**Beschreibe den Fehler**
Bei dem Videoplayer fehlen die Übersetzungen für einige Elemente.

Elemente, wo die Übersetzungen fehlen:

- "Advertisements" bei Werbeeinblendungen.
- "Speed" bei der Geschwindigkeits-Option. 
- "Quality" bei der Qualitätseinstellung.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/videos/pietsmiet/53845-jays-zufallspiel
2. Klicke auf Play

**Erwartetes Verhalten**
Alle Strings sollten ins deutsche übersetzt sein.

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Chrome
 - Browser-Version: 74.0.3729.157

**Comment by romanzipp** [comment]
Der Player ist natürlich nicht von uns selbst gemacht und ich sehe nicht, dass eine Überstzung in dem Fall nötig ist um dafür die schnelle Möglichkeit des Upgradens auf neue Versionen zu opfern.
