### ISSUE TITLE
Keine Unterstützung von Watch2Gether, Sync-Video Twoseven.xyz etc.

### ISSUE THREAD

**Issue by Kippenhof** [PietSmietde/Bugs#330]
Das nutzen von seiten wieWatch2Gether, Sync-Video oder Twoseven.xyz ist leider nicht möglich
### Reproduktion
Mit dem Plugin von z.b. Twoseven sieht man zwar mehrere Videos, aber keins Funktioniert

Es wäre schön, wenn man diese Seiten nutzen könnte, und falls das nicht möglich ist, wäre der Einbau eines solchen Features durchaus eine  gute Alternative

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows
 - Browser: Opera (Chromium Engine)
 - Browser-Version: 68.0.3618.125
 - Extensions/Add-Ons installiert: ublock, Twoseven.xyz, Windscripe und Downloadhelper

Es wäre schön, wenn das zusammen anschauen von Videos von der Pietsmiet.de Nativ unterstützt wird.

**Comment by romanzipp** [comment]
Die Unterstützung der PietSmiet.de in diesen Drittanbieterseiten liegt nicht in unserer Hand.

**Comment by Kippenhof** [comment]
Eigentlich schon. Ist eben das Format das ihr für die Videos auf der Seite verwendet.

**Comment by romanzipp** [comment]
Nein, wir haben keinen Einfluss darauf, welche Seiten von diesen dritten Diensten unterstützt wird. Ebenfalls gibt es keine Dokumentation, wie man Support einbauen könnte.
