### ISSUE TITLE
Twitch Subscriber bekommen den Snob-Status

### ISSUE THREAD

**Issue by RazoraDE** [PietSmietde/Bugs#336]
### Beschreibe das Feature

Zuschauer, die bereits Subscriber auf dem Twitch-Kanal sind, bekommen den Snob-Status und somit Werbefreiheit auf Pietsmiet.de

### Gibt es Alternativen?

Gerne nur die Video-Ads deaktivieren. Die Banner stören mich nicht.

### Geht der Vorschlag aus einem bestehenden Problem hervor?

Ich möchte nicht so viele Abos auf verschiedenen Webseiten abschließen. Die API von Twitch ermöglicht es zu ermitteln, ob man bereits bei Twitch 4,99€ im Monat bezahlt.

### Weitere Informationen

Benutzernamen können dadurch z.B. Lila versehen werden und eine separate Badge bekommen. In den Profil-Einstellungen kann man auswählen, welche Badge/Farbe angezeigt werden soll, falls man beide Abos abschließt.

**Comment by Kippenhof** [comment]
Das wär ein recht Cooles Feature

**Comment by romanzipp** [comment]
Danke für die Anregung!
