### ISSUE TITLE
Player erscheint nicht,

### ISSUE THREAD

**Issue by NilssonTV** [PietSmietde/Bugs#339]
### Beschreibe den Fehler

Wenn ich die 1915 Folge von FragPietsmiet anklicke erscheint der Player nicht, also kann ich das video nicht abspielen.
### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'Pietsmiet.de'
2. Klicke auf 'Tragt ihr in den Videos immer eine Hose? | Frag Pietsmiet #1915'

### Erwartetes Verhalten

Meine Erwartung ist das man das Video in naher Zukunft wieder abspielen kann.
### Screenshots

![Anmerkung 2020-06-25 103431](https://user-images.githubusercontent.com/59888994/85685708-999e5f00-b6cf-11ea-9619-442581def29a.png)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows
 - Browser: Opera GX
 - Browser-Version: Weiß ich leider nicht. 
 - Extensions/Add-Ons installiert: ich hab keine Add-Ons installiert.

**Comment by Unnon1989** [comment]
Kann den Bug so bestätigen. Scheint auch aktuell "nur" das FragPietSmiet Video betroffen zu sein, das Forts Video läuft ganz normal.

OS: Windows
Browser: Firefox
Version: Aktuelle (77.0.1 (64-Bit))

**Comment by dominovox** [comment]
Der Fehler ist behoben, Sven hat da ein paar Zeilen durcheinander gebracht beim Einstellen :D
