### ISSUE TITLE
Feature: PiP für Safari

### ISSUE THREAD

**Issue by YoKoGFX** [PietSmietde/Bugs#34]
**Beschreibe das Feature**
Wäre es nicht schön, wenn man die Videos in Safari in den PiP Modus bringen könnte?
Eine Dokumentation gibt es hier: https://developer.apple.com/documentation/webkitjs/adding_picture_in_picture_to_your_safari_media_controls

**Gibt es Alternativen?**
Ja, wie Youtube es macht. Doppel Rechtsklick zeigt das Kontext-Menü des Videos an.

**Comment by YoKoGFX** [comment]
Ich glaube, dass der Player diese Funktion sogar eingebaut hat.
Dokumentation: https://github.com/kaltura/playkit-js/blob/master/docs/configuration.md
`config.playback.pictureInPicture`

**Comment by romanzipp** [comment]
Der Player selbst hat tatsächlich einen Picture in Picture Modus, der hat aber keine spezielle Kompatibilität für Safari dabei, iirc. Für die neue Seite verwenden wir aber eine eigene Lösung.
Kannst du mir mal einen Screenshot von dem Safari-eigenen zukommen lassen?

**Comment by YoKoGFX** [comment]
@romanzipp Meinst du den PiP von Safari oder den default Player, wenn man sich HTML anschaut?

**Comment by romanzipp** [comment]
Ich meine den Picture-in-Picture Modus von Safari

**Comment by YoKoGFX** [comment]
@romanzipp Ist das okay?  
<img width="1440" alt="Bildschirmfoto 2019-06-18 um 18 32 30" src="https://user-images.githubusercontent.com/18743976/59702222-8375dd00-91f7-11e9-9211-597aaaecb004.png">

**Comment by romanzipp** [comment]
Besteht der Fehler immernoch?

**Comment by YoKoGFX** [comment]
Sorry habe es nicht gesehen. Nein, das ist jetzt tatsächlich fixed. :) 
Vielen Dank.
