### ISSUE TITLE
Kommentare werden nicht gepostet

### ISSUE THREAD

**Issue by K1ngL0u1** [PietSmietde/Bugs#340]
### Beschreibe den Fehler

Manche Kommentare sind nach dem Posten einfach verschwunden.

### Reproduktion

Kommentar posten, Kommentar weg, Kommentar posten, Kommentar weg. :D

### Erwartetes Verhalten

Kommentar wird gepostet

### Screenshots

Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.
(*Screenshots per Drag & Drop hier einfügen*)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10
 - Browser: Chrome
 - Browser-Version:  83.0.4103.116

**Comment by romanzipp** [comment]
Duplicate of #307
