### ISSUE TITLE
Suchfunktion / Zeitliche Reihenfolge

### ISSUE THREAD

**Issue by SuperNyr0** [PietSmietde/Bugs#341]
### Beschreibe das Feature

Ich persönlich finde es unübersichtlich, wenn die Suchfunktion zusammenhängende Videotitel nicht zeitlich sortiert, bzw. Videos nicht explizit mit dem Veröffentlichungsdatum präsentiert werden.
Als Beispiel: Ich habe letztens die Let's Plays zu "We were here together" gesucht, da wie auf YouTube keine Videovorschläge gemacht werden, welches Video als nächstes kommen müsste/sollte (würde ich jetzt auch nicht verlangen). Daher nutzte ich die Suchfunktion um mir alle Videos darüber anzuzeigen (Wie hier: https://www.pietsmiet.de/search?part=videos&q=we%20were%20here%20together&page=1), diese wurden jedoch namentlich sortiert und nicht zeitlich. Dann ist es aber unübersichtlich, wenn die Videos nur angezeigt werden mit "vor 7 Monaten hochgeladen".. Ja welches ist denn nun der nachfolgende Teil? Es gibt mehrere mit "vor 7 Monaten". Hierbei wäre eine Anzeige des exakten Datums interessant.

### Gibt es Alternativen?

Also entweder eine Suchfunktion mit einer zusätzlichen Sortierungsmöglichkeit nach Datum wäre interessant, bzw. dass Videos mit exaktem Veröffentlichungsdatum angezeigt werden, statt nur mit einem ungefähren "vor.." Stempel. Am besten wäre natürlich beides.

Mit freundlichen Grüßen
Chris

**Comment by romanzipp** [comment]
Das ist aktuell nicht so einfach umsetzbar, da unsere Suche auf Gewichtung der einzelnen Suchergebnisse basiert. Ansonsten wäre die Suche ziemlich "dumm" und würde nur wortgleiche Ergebnisse liefern
