### ISSUE TITLE
Video stoppt immer an der gleichen Stelle; lässt sich darüber hinaus nicht anschauen

### ISSUE THREAD

**Issue by ghost** [PietSmietde/Bugs#343]
### Beschreibe den Fehler

Ein Video aus dem Streamarchiv (Norwegen Roadtrip - Stream vom 20.05.19 [https://www.pietsmiet.de/videos/54148-norwegen-roadtrip-v427387786-20190520mp4?channel=44-pietstream]) stoppt immer an der gleichen Stelle und lässt sich darüber hinaus nicht anschauen. Wenn man ein Clip erstellen möchte hat man weiteren Zugriff auf ca. 15 Sekunden, eben so viel wie die Clip-Funktion in dem Moment hergibt.
Das Problem trifft sowohl beim PC als auch beim Handy auf.
Das Video stoppt immer bei 01:04:52

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu Streams unter Videos
2. Klicke auf die (aktuell) siebte Seite
3. Wähle das entsprechende Video aus.
4. Ein paar Sekunden vor der angesprochenen Stelle vorspulen und dann laufen lassen

### Erwartetes Verhalten

Das Bild bleibt stehen; Nichts geschieht

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10
 - Browser: Chrome und Opera
 - Browser-Version: Chrome Version: 83.0.4103.116   Opera Version: 69.0.3686.57
 - Extensions/Add-Ons installiert: AdBlock Plus

### Smartphone (bitte die Informationen vervollständigen)

 - Gerät: Huawei P9 Lite
 - Betriebssystem: Android: 7.0
 - Browser: Chrome
 - Browser-Version: 11.17.15.21.arm64

**Comment by dominovox** [comment]
Danke für die Meldung, die Originaldatei ist wegen den Internetausfällen auf der norwegischen Autobahn leider unrettbar Fehlerhaft und deshalb habe ich das Video deaktiviert.
