### ISSUE TITLE
CSS im Unteren Bereich geht nicht

### ISSUE THREAD

**Issue by Dominik1990PB** [PietSmietde/Bugs#345]
### Beschreibe den Fehler

Ganz unten auf jeder Seite kann man die Texte Aufgrund des weißen Hintergrundes nicht mehr lesen. Hier muss wieder der dunkel Graue oder Grüne (welcher es auch war) wieder hin. 

### Reproduktion

Seite Laden und nach ganz unten scrollen.

### Erwartetes Verhalten

Sollte eine andere Farbe sein.

### Screenshots

![Pietsmiet_de_Footer_1](https://user-images.githubusercontent.com/26764069/87822984-c7139e00-c872-11ea-81ee-0a9a29f5e9d9.PNG)
![Pietsmiet_de_Footer_2](https://user-images.githubusercontent.com/26764069/87822985-c7ac3480-c872-11ea-8815-80ba834a479e.PNG)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10 Pro
 - Browser: Firefox (78.0.2 (64-Bit)), Chrome (84.0.4147.89 (Offizieller Build) (64-Bit)), Opera GX (LVL2 (core: 68.0.3618.197)), Edge (Version 83.0.478.64 (Offizielles Build) (64-Bit))
 - Browser-Version: siehe Klammer nach Browser.
 - Extensions/Add-Ons installiert: Edge & Opera GX haben keine. Firefox & Chrome haben uBlock Origin in deaktiviertem Zustand.

**Comment by Dominik1990PB** [comment]
Außerhalb des Darkmodes wird der Footer richtig angezeigt laut Edge.

**Comment by kisimediaDE** [comment]
Ist mir auch schon aufgefallen. 
macOS 10.15.6 - Chrome Version 84.0.4147.89 (Offizieller Build) (64-Bit)

**Comment by romanzipp** [comment]
Ist behoben und wird demnächst gepatcht 👍
