### ISSUE TITLE
Qualitätsauswahl bei Clips

### ISSUE THREAD

**Issue by jonatanschneider** [PietSmietde/Bugs#349]
### Beschreibe den Fehler

Die Qualitätsoptionen in den Clips sind falsch beschriftet.

1080p60 sorgt dafür dass das Video in 240p dargestellt wird.
240p = 1080p60 usw.

### Reproduktion

Beispiel Clips:
https://www.pietsmiet.de/videos/clips/WuCXUZsCriSodKqw
https://www.pietsmiet.de/videos/clips/WuCXUZsCriSodKqw

Qualität auf 240p setzen -> Video sollte in bester Qualität wiedergegeben
Qualität auf 1080p60 setzen (bzw. die unterste Einstellung im Dropdown) -> Video wird in schlechtester Qualität wiedergegeben

### Erwartetes Verhalten

Videoqualität sollte Einstellung entsprechen

### Screenshots

Hier ein Ausschnitt mit der eingestellten Qualität. Video wurde vorher Zeit zum puffern gegeben.

![240p](https://user-images.githubusercontent.com/9830972/88050575-64165580-cb57-11ea-9823-11a4788e367a.PNG)
![1080](https://user-images.githubusercontent.com/9830972/88050583-6a0c3680-cb57-11ea-81b0-68228105d2f2.PNG)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10, 1909
 - Browser: Firefox
 - Browser-Version: 78.0.2
 - Extensions/Add-Ons installiert: uBlock

### Weitere Informationen

Problem tritt nur bei Clips auf, bei normalen Videos nicht. Dort ist die Liste allerdings auch anders sortiert (1080p steht ganz oben, bei den Clips ganz unten)

**Comment by romanzipp** [comment]
https://github.com/PietSmietde/Bugs/issues/386#issuecomment-753919063
