### ISSUE TITLE
Bug: Nicht funktionierende Playlist

### ISSUE THREAD

**Issue by Avestator** [PietSmietde/Bugs#35]
**Beschreibe den Fehler**
Playlists an sich funktionieren ja schon nicht, aber als nächstes Video wird mir auch immer eine völlig andere Folge angezeigt, in Folge Zwei wird mir Folge 64 als nächstes vorgeschlagen

**Reproduktion**
Öffne die Factorio Playlist
Sei enttäuscht, dass sie nicht wie eine normale Playlist funktioniert, du die Seite aber nutzen musst weil es keine Alternative gibt.
Öffne Folge eins
Siehe auf den Vorschlag "nächstes Video" unter der Folge

**Erwartetes Verhalten**
Funktionierende Playlists ohne ständig das neue Video anklicken zu müssen. Oder unter Folge 1 wird als nächstes Video Folge 2 vorgeschlagen

**Desktop (bitte die Informationen vervollständigen):**
Windows 10
Chrome, aber selbes Problem auch unter Firefox, Opera, TOR und sogar Microsoft Edge

**Comment by romanzipp** [comment]
Der Fehler ist bereits auf der neuen major Version der Website gefixt und das allgemeine Verhalten von Playlist wurde drastisch verbessert.
Wir haben uns dagegen entschieden, Resourcen für den Fehler auf der aktuellen Liveseite zu verweden, das der Release in absehbarer Zeit stattfinden wird.
