### ISSUE TITLE
Videos spielen nicht mit mobilen Daten

### ISSUE THREAD

**Issue by DerDon420** [PietSmietde/Bugs#352]
Guten Tag, 

leider ist es mir nicht gegönnt auch von unterwegs 2 Stunden früher Pietsmiet zu genießen. Ich bekomme immer die Fehlermeldung "something went wrong". Egal welchen Browser ich verwende oder wie viel Empfang ich gerade habe (min. 10 MBit/s meist um die 50 MBit/s). 

Aktuell habe ich einen Vertrag bei Vodafone (Young Tarif) mit einem S20+. Softwaretechnisch ist alles auf dem neusten Stand. Vorher hatte ich ein S9 im Vertrag bei 1&1. Da lief alles reibungslos. 

![Screenshot_20200728-120217_Chrome](https://user-images.githubusercontent.com/68900481/88652629-65053500-d0cb-11ea-88e1-c937456fdd4b.jpg)

**Comment by romanzipp** [comment]
Mit welchen Browser hast du es genau versucht und welche Android Version verwendest du?

**Comment by DerDon420** [comment]
Ich habe Android 10. Probiert habe ich es mit den aktuellsten Versionen von Chrome und Firefox

**Comment by dominovox** [comment]
Hast du die Einstellungen über das Zahnradsymbol unter dem Video geändert? Standardmäßig sollten die so aussehen:
![image](https://user-images.githubusercontent.com/26336654/88660174-87508000-d0d6-11ea-8287-1befeef2ccfb.png)

**Comment by DerDon420** [comment]
Auch dort habe ich jede mögliche Kombination getestet. 

Sorry das habe ich wohl übersehen. Kann ich das nach noch nachträglich ergänzen?

**Comment by dominovox** [comment]
Bei der Erstellung des Issues wäre das Automatisch als Textvorlage zum Ergänzen dagewesen. Du kannst einfach den ersten Comment editieren. Und Anbieter zu wissen wäre auch schön, damit wir das vlt versuchen können, nachzuvollziehen :)

**Comment by DerDon420** [comment]
Okay alles klärchen. Merke ich mir für das nächste mal ;) Kommentar ist editiert

**Comment by dominovox** [comment]
Hast du es seit der Meldung mal wieder probiert? Wenn nicht, probiere es bitte erneut.

**Comment by DerDon420** [comment]
Ja hab ich. Es funktioniert leider immer noch nicht.

**Comment by Shin0da92** [comment]
Ist es immer noch so bzw. bei allen Videos? Habe Telering (Österreich) und mit meinem Huawei P30 (entsprechend aktuelle Android Version) funktioniert alles ohne Probleme.

**Comment by DerDon420** [comment]
Habe es gerade nochmal probiert. Komischerweise funktioniert alles wieder.  Wer weiß woran es gelegen hat.

**Comment by DerDon420** [comment]
Habe es gerade nochmal probiert. Komischerweise funktioniert alles wieder. Wer weiß woran es gelegen hat.
