### ISSUE TITLE
Fehler im Footer der Website

### ISSUE THREAD

**Issue by PlzDntBlm** [PietSmietde/Bugs#353]
### Beschreibung
Die Links "Impressum", "Gewinnspielteilnahmebedingungen", "Datenschutz", "Nutzungsbedinungen" sowie "Fehler auf der Seite entdeckt?" sind in der Farbe #fff auf einem Hintergrund mit der Farbe #f8fafc. Man kann dadurch die Links nicht lesen.
Problem könnte die CSS-Klasse "text-white" beim <a> tag sein.

### Reproduktion
Ist auf jeder Site von pietsmiet.de.

### Erwartetes Verhalten
Readability der Links

### Screenshots
![image](https://user-images.githubusercontent.com/44626443/88662403-32166d80-d0da-11ea-8efc-0a21dcab27f3.png)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10
 - Browser: Opera GX, Chrome, Firefox
 - Browser-Version: aktuellster Stand (28.07.2020)
 - Extensions/Add-Ons installiert: unabhängig von add-ons

**Comment by Gameniti** [comment]
Ist mir auch eben aufgefallen als ich nach einem Link zu dieser Bug Report Seite gesucht habe, den ich nicht gefunden habe. Auch ist es eventuell nicht richtig im Dark Mode einen Weißen Footer zu haben.

**Comment by romanzipp** [comment]
Duplicate of #345
