### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by Maxeres** [PietSmietde/Bugs#355]
### Beschreibe den Fehler

ich kann seit einer sehr langen zeit keine videos auf pietsmeit.de schauen da immer wieder der fehler auftritt something went wrong 
pc hatte ich schon mal zurückgesetzt 
adobe ist auf der aktuellsten version 
Einstellungen unter den video habe ich schon alle möglichen Variationen getestet
bin auch snob auf der seite (hört sich irgendwie komisch an so zu schreiben)

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'video(egal welches) '
2. Klicke auf 'video'
3. something went worng

### Erwartetes Verhalten

Eine Beschreibung des zu erwartenden Verhaltens / Ergebnisses.

### Screenshots

Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.
(*Screenshots per Drag & Drop hier einfügen*)

### Desktop (bitte die Informationen vervollständigen)
zu meinen pc vlt hilft es kp:
AMD Ryzen 9 3950x
32gb ram
rog strix gtx 2080ti
rog stirx x570e gaming mainboard 
 - Betriebssystem: [Win 10 vers.:2004]
 - Browser: [Opera GX,Chrome,]
 - Browser-Version: [chrome:Version 84.0.4147.105 (Offizieller Build) (64-Bit)  Operagx kp müsste aber aktuell sein ]
 - Extensions/Add-Ons installiert: [keine -]

**Comment by dominovox** [comment]
Hast du es seit der Meldung wieder versucht? Wenn nicht, probier es bitte einmal.

**Comment by Maxeres** [comment]
ja das problem besteht immer noch außer ich habe VPN an dann gehts 
womit könnte das zusammenhängen?
Internetanbieter vlt da habe ich vodafone
