### ISSUE TITLE
Fehler beim Subscription Streak?

### ISSUE THREAD

**Issue by Milkaselnuss** [PietSmietde/Bugs#356]
### Beschreibe den Fehler
Theoretisch dürfte man eigentlich maximal im 11. Monat des Snob Abos bzw. Ultra sein. Bei einigen wird in der Hall of Fame jedoch ein (weit) höherer Wert angezeigt.

### Reproduktion
Siehe z.B.  Nutzer [erik47](https://www.pietsmiet.de/profile/42472-erik47), der angeblich seit 19 Monaten Ultra ist, obwohl er erst seit April 2019 überhaupt registriert ist.

### Erwartetes Verhalten
(Realistische) Anzeige, wie lange jemand schon Snob/Ultra ist.

### Desktop
 - Windows 8.1
 - Firefox 78.0.2

**Comment by romanzipp** [comment]
Die Streakt wird auch erhöht, wenn Benutzer mehrere Abonnements abgeschlossen haben.
