### ISSUE TITLE
Zeilenumbrüche in Vorschlägen werden nicht angenommen

### ISSUE THREAD

**Issue by florian-berger** [PietSmietde/Bugs#357]
### Beschreibe den Fehler

Wenn man Vorschläge schreibt, hat man dort ein Textfeld zur Verfügung, in dem man Zeilenumbrüche einfügen kann. Diese werden nach Absenden des Vorschlags jedoch ignoriert und alles ohne Umbruch dargestellt.

### Reproduktion

1. Vorschlag mit mehreren Zeilenumbrüchen schreiben
2. Vorschlag speichern

### Erwartetes Verhalten

Zeilenumbrüche sollten so dargestellt werden, wie sie im Text eingegeben wurden.

### Screenshots
Eingabe:
![image](https://user-images.githubusercontent.com/10084586/89047664-00f2a300-d34f-11ea-9bf0-9b218f58cc15.png)

Ergebnis:
![image](https://user-images.githubusercontent.com/10084586/89047734-15cf3680-d34f-11ea-87b8-ec583fa3c549.png)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10 Pro
 - Browser: Microsoft Edge (Dev-Channel)
 - Browser-Version: 86.0.587.0 (Official build) dev (64-bit)
 - Extensions/Add-Ons installiert: -

**Comment by romanzipp** [comment]
Der Fehler wurde behoben
