### ISSUE TITLE
Player buffert während des Videos

### ISSUE THREAD

**Issue by Shin0da92** [PietSmietde/Bugs#359]
### Beschreibe den Fehler

Ich lasse die Videos oft auf meinem Zweit-Monitor laufen. Öfters kommt es zu "Pufferungen" bzw. ladet der Player immer wieder 
mal zwischendurch. Dem Screenshot kann man aber entnehmen, dass es nicht am Internet liegt, da der weiße Balken zu sehen 
ist, wieviel Google Chrome runtergeladen hat.

Manchmal passierte es mir auch, wenn ich die 10 Sekunden Buttons nutzte.

### Reproduktion

1. Suche ein Video auf Pietsmiet.de
2. Das Video auf einen 2. Monitor ziehen
3. Auf Vollbild stellen
4. Abspielen und ab und zu tritt das Problem auf wenn ich ein Programm starte oder etwas abspeicher

### Erwartetes Verhalten

Wie im Screen zu entnehmen (die bunten Punkte) fängt der Player an, sich alle paar Sekunden aufzuhängen bzw.
taucht dadurch der Ladekreis im Video auf.

### Screenshots
![Image 2020 08 16 17 08 43](https://user-images.githubusercontent.com/69717293/90413859-551bb800-e0af-11ea-9b18-c945e72c91f0.png)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10
 - Browser: Chrome 
 - Browser-Version: 84.0.4147.125
 - Extensions/Add-Ons installiert: Adblock, Screengrab, Bitdefender Anti-Tracker

### Smartphone (bitte die Informationen vervollständigen)

 - Gerät: Huawei P30
 - Betriebssystem: EMUI 10.1.0.140
 - Browser: Chrome 84.0.4147.105
 - Browser-Version: [z.B. 22]

**Comment by Mazy998** [comment]
Das passiert bei mir auch auf dem Hauptbildschirm.

**Comment by Patti2101** [comment]
Schaue die Videos auch auf dem 2.Bildschirm und leider taucht der Fehler in den letzten Tagen vermehrt auf.

**Comment by romanzipp** [comment]
Wenn es nur auf einem 2. Bildschirm auftritt handelt es sich wahrscheinlich um ein sehr spezifisches Problem auf deiner Seite. Wir haben leider keine Möglichkeit, solche spezifischen Szenarien zu reproduzieren.
Setze mal an der Grafikkarte mit evnetueller Fehlerbehebung an. Sprich treiber aktualisieren, Einstellungen überprüfen etc.

**Comment by Shin0da92** [comment]
Komisch aber dass es auf Youtube ganz normal funktioniert und dieser Fehler einzig auf eurer Seite passiert aber ok....

**Comment by romanzipp** [comment]
Wie gesagt, ich würde gerne helfen, aber das ist schlicht und einfach nicht möglich.
