### ISSUE TITLE
Bug: Videos laden alle paar Sekunden bei höherer Auflösung

### ISSUE THREAD

**Issue by SuperNyr0** [PietSmietde/Bugs#36]
**Beschreibe den Fehler**
Wie man auch in Kommentaren und Tags erkennen konnte, scheint es bei einigen (vllt. sogar allen) Usern auf PietSmiet.de das Problem zu geben, dass der Player ab gewisser Auflösung stockt und mehrmals längere Zeit laden muss (Vorladen ist beim Player auch nur bis zu wenige Sekunden möglich), was das Ansehen in HD unmöglich erscheinen lässt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
Videos ansehen (Beispielsweise aufgefallen bei: https://www.pietsmiet.de/videos/pietsmiet-tv/54880-react-monoton-unfahig-5)

**Erwartetes Verhalten**
Reibungsloser Videoverlauf

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10
 - Browser: Firefox
 - Browser-Version: Neueste Version (67.0.4 - 64Bit)

**Comment by romanzipp** [comment]
Danke für die Meldung. Bei welchem Internetanbieter bist du zurzeit und welche Geschwindigkeit kommt durchschnittlich bei dir an? Die Angaben würde uns helfen

**Comment by SuperNyr0** [comment]
Ich bin Kunde der Telekom und bei mir kommen im Normalfall zwischen 50-60MBit/s im Download an.
Würd auch gern auf folgendes Video noch hinweisen:
https://www.pietsmiet.de/videos/pietsmiet/54847-wer-schaffts-das-schwert-aus-dem-stein-zu-ziehen
Dort kann man an einem Hashtag und mehreren Kommentaren unter dem Video feststellen, dass einige dieses Problem in letzter Zeit haben. Es ist auch nicht das einzige Video unter dem solche Kommentare zu finden sind.

**Comment by romanzipp** [comment]
Ich habe die Buffer-Zeiten für die einzelnen Videosegmente erhöht. Demnach sollte für ein Video eine höhere Zeitperiode vorgeladen werden.
Kannst du bitte prüfen, ob das Besserung gebracht hat?

**Comment by romanzipp** [comment]
Alternativ probieren, ob ein anderes Wiedergabepreset (per "Quelle"-Button unter den Videos erreichbar) besser funktioniert.

![2019-07-04_11-57-35](https://user-images.githubusercontent.com/11266773/60658178-f5366380-9e52-11e9-8e95-5df9d48dad34.png)

**Comment by SuperNyr0** [comment]
Seit einigen Tagen hatte ich bisher auch keine Probleme mehr, kann gut sein, dass dies nur eine vorübergehende Störung war oder nur zu gewissen Zeiten auftritt.
Trotzdem danke für jegliche Bemühungen, ich werde ein alternatives Wiedergabepreset beim nächsten Mal gerne in Erwägung ziehen und austesten, sollte wieder einmal so ein Fall eintreten.
