### ISSUE TITLE
Mögliche CDN Kostensenkung

### ISSUE THREAD

**Issue by Alexander-Zierhut** [PietSmietde/Bugs#362]
### Beschreibe das Feature

Vielleicht könntet Ihr davon profitieren, [Cloudflare Stream](https://www.cloudflare.com/products/cloudflare-stream/) zu verwenden. Ich kenne zwar eure Ausgabe für CDN und Storage nicht, aber ich bin sehr erstaunt von dem preiswerten Angebot. Vielleicht ist das ja was für euch.

### Gibt es Alternativen?

Die aktuelle content delivery Lösung.

### Geht der Vorschlag aus einem bestehenden Problem hervor?

Nein. Dies könnte die Kosten senken.

**Comment by romanzipp** [comment]
Danke für den Vorschlag :)

**Comment by Alexander-Zierhut** [comment]
Kurzes Update dazu: https://developers.cloudflare.com/r2/data-access/public-buckets/
Es gibt jetzt Cloudflare R2 Public. S3 kompatibel.
$0.015 pro GB pro Monat Speicher
**Keine** Kosten für Ein- **und** Ausgehenden Traffic
