### ISSUE TITLE
Gravatar als Alternative/Ersatz für Profilavatare

### ISSUE THREAD

**Issue by tintinmaster** [PietSmietde/Bugs#363]
### Beschreibe das Feature

Nutzen von [Gravatar](https://de.gravatar.com/) für Profilavatare.

### Gibt es Alternativen?

Das bestehende System weiterverwenden

### Geht der Vorschlag aus einem bestehenden Problem hervor?

Wenn ich mein Profilbild global ändern will, kann ich das an einer stelle mit Gravatar. Ohne die Funktion, geht das nur auf jeder Website manuell.

### Weitere Informationen

Einfach zu implementieren, Anleitungen vorhanden, keine API-Authentifizierung nötig

**Comment by romanzipp** [comment]
Danke für den Vorschlag, allerdings haben wir uns aus Datenschutzgründen gegen eine Gravatar Anbindung entschieden. Die Begründung dessen habe ich bereits im Issue #268 geschrieben
