### ISSUE TITLE
Virus Meldung

### ISSUE THREAD

**Issue by RealZezzo** [PietSmietde/Bugs#364]
Moin,

ich bekomme seit dem 10.09. immer eine Virus Meldung sobald ich die Pietsmiet.de aufrufe. BitDefender zeigt mir an, dass im cache des Browsers ein Virus versteckt ist. Jage ich die gewisse Datei durch Virustotal, bekomme ich 18x positive Feedback, dass es ein Virus ist. Das BitDefender ausschlägt, tritt nur auf der Seite auf.

Anti-Virus Programm: 

> BitDefender

BitDefender Meldung:

> Die Datei C:\Users\XXXXX\AppData\Local\Opera Software\Opera GX Stable\Cache\f_0753bc ist mit JS:Adware.Lnkr.A infiziert und wurde in die Quarantäne verschoben. Wir empfehlen die Durchführung eines System-Scans, um weitere Infektionen auszuschließen.

Virustotal Scan:

> https://www.virustotal.com/gui/file/cd1e0450a00fa9b7bbefdc3b140e599f724469823e00995fbb01cb5a1e40bd96/detection

Betriebssystem: 

> Windows 10

Browser: 

> Opera GX

**Comment by RealZezzo** [comment]
Browser-Version:

> 68.0.3618.206

Extensions/Add-Ons installiert:

> AHA Music 

> Ban Checker for Steam

> BetterTTV

> CSGOFloat Market Checker

> Enhanced Steam

> Honey

> Install Chrome Extensions 

> Shoop.de

> Steam Inventory Helper

> Temp Mail

> uBlock Origin (aber auf Pietsmiet.de deaktiviert)

> Volume Control

**Comment by romanzipp** [comment]
Danke für die Meldung
