### ISSUE TITLE
Seite über das Pietsmiet-Logo aktualisieren

### ISSUE THREAD

**Issue by Mazy998** [PietSmietde/Bugs#365]
### Beschreibe das Feature

Normalerweise kann man bei Webseiten, auch wenn man auf der Startseite ist, auf das Logo klicken und damit die Seite aktualisieren. Bei euch ist das leider nicht möglich. Natürlich kann man die Seite auch über F5 aktualisieren aber wenn man es über das Logo gewohnt ist, nervt einen das. 

LG

**Comment by romanzipp** [comment]
Duplicate of #186
