### ISSUE TITLE
Keine Likes trotz "Dein Kommentar ist beliebt"-Notification

### ISSUE THREAD

**Issue by Mano176** [PietSmietde/Bugs#366]
### Beschreibung & Reproduktion
Manchmal bekommt man eine Benachrichtigung, dass dein Kommentar vom [Datum] beliebt ist.
Da erwartet man nun, dass man mehrere Likes auf einem Kommentar hat.
Die letzten Male als ich aber auf die Nachricht klickte und sich das jeweilige Video mit dem Kommentar öffnete, wurden mir 0 Likes angezeigt. (Möglich wäre es eventuell, dass sich Likes und Dislikes ausgleichen (ich weiß nicht ob dies so gehandhabt wird), das würd ich aber mal für recht unwahrscheinlich halten.

### Desktop
 - Betriebssystem: Windows 10 Home
 - Browser: Chrome
 - Browser-Version: 85.0.4183.102 (Offizieller Build) (64-Bit)
 - Extensions/Add-Ons installiert: AdBlock Plus (auf PS aber ausgeschaltet, trotz Snob), einige andere welche sich nicht auf die PS beziehen, wie BetterTTV, Ban Checker for Steam, etc

### Smartphone
Auf dem Smartphone hab ichs noch nicht getestet bzw. ist es mir noch nicht aufgefallen

### Edit
Ich weiß nicht ob das hiermit zusammenhängt oder ob es beabsichtigt ist, aber mir ist gerade aufgefallen, dass wenn ich einen anderen Kommentar like, der likecount trotzdem auf 0 bleibt aber der Daumen grün wird (das bleibt auch nach Aktualisieren der Seite genau so)

**Comment by Milkaselnuss** [comment]
War es ein Kommentar auf oberster Ebene (direkt unter dem Video) oder eine Antwort auf einen anderen Kommentar? Hatte persönlich in letzter Zeit häufiger das Gefühl, dass die Likes bei Antworten verbuggt sind, wollte bisher aber noch kein Ticket deswegen aufmachen.

**Comment by Mano176** [comment]
Stimmt, hab gerade nachgeschaut. Von den letzten 4 Benachrichtigungen bezüglich Likes sind 3 zu Antworten die ich auf andere Kommentare gemacht habe. Dort habe ich immer 0 Likes. Die 4. Nachricht war zu einem selbst verfassten Kommentar, dort wurden mir 46 Likes angezeigt

**Comment by Tanielll** [comment]
Ich würde sagen es werden bei Antworten auf Kommentare generell keine Likes mehr angezeigt. Da steht immer 0. Bei allen Antworten, wo mir früher auch schon mal Likes richtig angezeigt wurden steht jetzt einfach 0.
Wobei die Likes anscheinend vom System noch richtig gezählt werden, da die Benachrichtung ab dem. 6. Like immer noch funktioniert. Lediglich die Anzeige und dem Kommentar funktioniert bei den Antworten auf andere Kommentare nicht mehr.

**Comment by romanzipp** [comment]
Habe mir die Sache mal genauer angeschaut. Die Annahme ist korrekt, dass die Likezahl für Antworten momentan nicht geladen wird, deshalb wird dort 0 angezeigt. Das Liken an sich funktioniert jedoch, weshalb auch die Benachrichtigungen über beliebte Kommentare gesendet werden.
Zusätzlich wird diese Benachrichtigung auch gesendet, wenn nur ein bestimmer Like.Threshold überstiegen wird. Die Differenz von Likes & Dislikes wird nicht beachtet.

Für beide Punkte werde ich mir mal eine Lösung ausdenken
