### ISSUE TITLE
Aktive Sicht im Cinema Modus ist falsch markiert

### ISSUE THREAD

**Issue by Patrick-D3V** [PietSmietde/Bugs#368]
### Beschreibe den Fehler

Im Cinema Modus ist die aktuelle Sicht falsch markiert

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'https://www.pietsmiet.de/videos/63115-uncut-nur-1-versuch-60-seconds-reatomized'
2. Klicke auf 'Cinema Modus aktivieren.'
3. Unterm Video erscheinen Tabs zu den Sichten
4. Wähle Piet aus -> Brammen wird grün markiert, aber es spielt das Video von Piet
5. Wähle Jay aus -> Piet wird grün markiert, aber es spielt das Video von Jay
6. Bei Sep funktioniert es wie erwartet
7. Wählt man Brammen wird Jay grün markiert

### Erwartetes Verhalten

Wenn ich auf Piet drücke sollte Piet markiert sein, und nicht Brammen

### Screenshots

-

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10
 - Browser: Chrome 
 - Browser-Version: 85.0.4183.121 64-Bit
 - Extensions/Add-Ons installiert: -

### Weitere Informationen

Mir scheint es so, dass die Videos in der falschen Reihenfolge dort eingepflegt wurden (oder der Player sortiert die Sichten alphabetisch nach im Overlay).
Auf der Seite davor, würde es vom Index passen, Piet ist im Overlay auf Position 3, markiert aber Position 1, was in der Ansicht ohne Cinema Modus Piet wäre.

**Comment by romanzipp** [comment]
Der Fehler wurde behoben
