### ISSUE TITLE
Falsches Datum bei den Streamaufzeichnungen

### ISSUE THREAD

**Issue by deralex100** [PietSmietde/Bugs#372]
### Beschreibe den Fehler?

Neuerdings werden ja immer die Streamaufzeichnungen hochgeladen. Das Problem ist allerdings, dass die Jungs das oftmals nicht direkt machen, sondern erst einen oder mehrere Tage später. In die Beschreibung wird aber anscheinend automatisiert immer das Datum des Hochladens als Datum des Streams eingetragen. 
Dort liest man also immer: "Der Stream lief am xx.xx.xxxx". Das angegebene Datum ist aber häufig falsch, was mindestens mal sehr irritierend ist. Zum Beispiel hat Sep heute einen drei Tage alten Among us Stream hochgeladen (in dessen Beschreibung natürlich steht, dass er von heute ist), sodass ich schon gedacht habe, dass ich einen Stream verpasst habe. Da heißt selbst ich werde davon immernoch verwirrt, obwohl ich ja eigentlich schon verstanden habe, dass die Angabe ständig falsch ist.

Ich weiß nicht genau wie man umsetzen kann, dass das korrekte Datum wirklich automatisiert da eingetragen wird. Ich weiß auch ehrlich gesagt garnicht, ob ihr das irgendwie direkt aus Twitch zieht oder ob die Jungs nebenbei eine Aufnahme laufen lassen oder wie auch immer. Aber in jedem Fall sollte in der Videodatei doch irgendwie hinterlegt sein, wann die aufgenommen wurde, oder?

### Gibt es Alternativen?

Kurzfristige Lösung: Sagt den Jungs, dass sie die Beschreibung ändern sollten, falls sie den Stream erst später hochladen. Aber auf lange Sicht würden sie das sicherlich ständig vergessen.
Ansonsten könnte man die Information über das Datum des Streams in der Videobeschreibung einfach weglassen. Dann ist es zumindest nicht mehr falsch. Denn eine falsche Information ist wirklich irritierend.

Wäre schön, wenn ihr das irgenwie lösen könntet. Auf dauer triggert mich das echt ein bisschen :D

**Comment by romanzipp** [comment]
Danke für die Meldung! Die Streams werden von unserem System automatisiert direkt nach dem Livestream veröffentlicht. Wenn das Datum vereinzelt ein falsches Datum haben sollte ist dies technisch bedingt.

Bis jetzt wurde das angegebene Datum aus dem Zeitpunkt der Importierung genommen, habe ich jetzt dahingehend aktualisiert, dass Datum & Uhrzeit aus dem Twitch VOD bzw. Highlight berücksichtigt werden.

**Comment by deralex100** [comment]
> Danke für die Meldung! Die Streams werden von unserem System automatisiert direkt nach dem Livestream veröffentlicht. Wenn das Datum vereinzelt ein falsches Datum haben sollte ist dies technisch bedingt.
> 
> Bis jetzt wurde das angegebene Datum aus dem Zeitpunkt der Importierung genommen, habe ich jetzt dahingehend aktualisiert, dass Datum & Uhrzeit aus dem Twitch VOD bzw. Highlight berücksichtigt werden.

Ich will ja nicht nerven, aber so ganz scheint es immer noch nicht zu stimmen. Seps Streams vom Dienstag (1.12) waren laut Beschreibung angeblich am Mittwoch (2.12):
https://www.pietsmiet.de/videos/64375-technik-sep-am-start
https://www.pietsmiet.de/videos/64377-der-imposter-among-us-mit-sep-annitheduck-dhalu-ginoswelt-vlesk-matteo-bonjwa-shlorox-trilluxe-unge-mate-bamm

Der Demon's Souls Stream vom Montag (30.9) war laut Beschreibung am Dienstag (1.12):
https://www.pietsmiet.de/videos/64367-der-storm-king-muss-fallen-demons-souls-7

Und bei Peters Twin Mirror Stream von Mitwoch (2.12) steht gar kein Datum in der Beschreibung (in der Beschreibung steht Werbung, weil der Stream Werbung war, aber die Beschreibung wird ja wohl mehr als eine Zeile haben können):
https://www.pietsmiet.de/videos/64381-pedda-testet-twin-mirror-das-neue-story-game-von-dontnod-ent

Kann natürlich auch sein, dass ich das irgendwie falsch verstanden habe, was du da fixen wolltest, aber die Beschreibung stimmt auf jeden Fall nicht
****
