### ISSUE TITLE
Auswahlmöglichkeiten bei Umfragen in zufälliger Reihenfolge

### ISSUE THREAD

**Issue by berl1n** [PietSmietde/Bugs#373]
Nicht wirklich ein Feature Vorschlag, sondern ein Verbesserungsvorschlag:

Aktuell werden die Umfragen auf Pietsmiet.de anhand der Stimmen sortiert. Zum Beispiel bei der aktuellen GPO Umfrage sind die Optionen mit den meisten Stimmen immer an oberster Stelle, auch wenn man noch keine Stimme abgegeben hat. Das beeinflusst meiner Meinung nach die Stimmabgabe, weshalb ich es besser fände, wenn die Auswahlmöglichkeiten in zufälliger Reihenfolge aufgelistet werden.

**Comment by berl1n** [comment]
Falls unklar ist wieso es die Stimmabgabe beeinflussen könnte ein paar Beispiele:

1. Wenn man weiß, dass die Ergebnisse so sortiert sind, wie es aktuell der Fall ist, wird man höchstwahrscheinlich nicht für die letzten Optionen stimmen.
2. Es ist so, dass man bei Umfragen mit vielen Optionen häufig schon eine Entscheidung trifft, bevor man sich überhaupt alle Optionen durchgelesen hat. Dadurch ist es selbst wenn man nicht weiß, dass die Optionen sortiert sind, wahrscheinlich, dass man eher eine der ersten wählt, als eine der letzten.

**Comment by romanzipp** [comment]
Die Sortierung erfolgt jetzt zufällig. Danke für den Hinweis!
