### ISSUE TITLE
Alle Features freischalten wenn der Account verifiziert ist

### ISSUE THREAD

**Issue by SamuelNitsche** [PietSmietde/Bugs#374]
### Beschreibe das Feature

Ich hab mir einen Account erstellt, weil ich eine Aussage in einem Video lustig fand und diese Stelle gerne für das Best-Of einreichen wollte. Leider habe ich beim Einreichen die Fehlermeldung "Account zu jung" erhalten.

Grundsätzlich verstehe ich ja dass man irgendwie vor Spam etc. schützen will, meiner Meinung nach sollte das aber nicht an das Account Alter gebunden werden sondern daran, ob ich meine E-Mail Adresse verifiziert habe. Sonst ist das ganze irgendwie witzlos.

### Gibt es Alternativen?

Eigentlich keine, aber vielleicht wenigstens eine Information, was man wann kann.

### Geht der Vorschlag aus einem bestehenden Problem hervor?

Nein

### Weitere Informationen

Keine

**Comment by romanzipp** [comment]
Wir hatten es in der Vergangenen Zeit sehr oft mit Spam auch unter Nutzern mit verifizierter E-Mail Adresse zu tun, weshalb wir einige Accountfunktionen zwagsmäßig an Parameter, die Alter des Accounts knüpfen müssen

**Comment by SamuelNitsche** [comment]
Alles klar, besteht trotzdem die Möglichkeit irgendwie an Infos zu kommen, wie alt der Account für bestimmte Funktionen sein muss?

**Comment by romanzipp** [comment]
Für das Einsenden von Best-Of Highlights muss der Account 24 Stunden alt sein. Andere Funktionen sind nicht verfügbar, wenn der Account aufgrund von Verstößen gesperrt wurde oder Limits erreicht wurden, diese Fehlermeldungen werden aber auch explizit formuliert.

**Comment by SamuelNitsche** [comment]
Danke für die Info.
