### ISSUE TITLE
Suchfunktion funktioniert nicht korrekt (außerhalb der Website)

### ISSUE THREAD

**Issue by SamuelNitsche** [PietSmietde/Bugs#375]
### Beschreibe den Fehler

Bei der Verwendung der Suchfunktion über OpenSearch oder über die URL direkt (pietsmiet.de/search?q=test) liefert die Seite einen 503 Response Code.

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Browser öffnen und "pietsmiet.de/search?q=test" eingeben
2. Absenden und warten bis Cloudflare den Browser überprüft hat
3. Fehlermeldung erscheint

### Erwartetes Verhalten

Suche funktioniert ganz normal.

### Screenshots

![image](https://user-images.githubusercontent.com/24483576/98043350-601bf400-1e25-11eb-9599-34c53727d5b9.png)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows, macOS
 - Browser: Edge, Firefox, Brave
 - Browser-Version: Edge 86.0.622.58, Firefox 80.0.1, Brave 1.16.72
 - Extensions/Add-Ons installiert: Zu viele zum aufzählen

**Comment by romanzipp** [comment]
Das war eine temporäre Maßnahme. Ist behoben, danke für die Meldung!
