### ISSUE TITLE
Transparenz in Avatar wird zerstört

### ISSUE THREAD

**Issue by Ponjimon** [PietSmietde/Bugs#376]
### Beschreibe den Fehler

Wenn man ein PNG als Avatar hochlädt, welches Transparenz beinhaltet, wird die Transparenz nicht übernommen, da es in ein JPG konvertiert wird. Hinzukommt, dass das die JPG-Qualität wohl nicht sonderlich hoch ist.

### Reproduktion

PNG als Avatar hochladen, welches Transparenz beinhaltet

### Erwartetes Verhalten

Es sollte die Transparenz übernehmen oder einheitlich ersetzen.

### Screenshots

![image](https://user-images.githubusercontent.com/770632/98385975-efa4eb00-204f-11eb-8036-ef58afabbba1.png)

**Comment by romanzipp** [comment]
Ich habe einen Fix gestartet, womit die Hintergründe aller Bilder mit Alphakanal einheitlich weiß ersetzt werden

**Comment by Ponjimon** [comment]
Habe meinen Avatar gelöscht und das obige Bild erneut hochgeladen, aber das Ergebnis ist unverändert:
![image](https://user-images.githubusercontent.com/770632/115962409-8b9db280-a51b-11eb-99eb-23e344766955.png)

**Comment by romanzipp** [comment]
Der neuste Stand mit dem Fix ist noch nicht live. Der Fehler wird ab Version 2.0.9+ nicht mehr auftauchen, voraussichtlich kommende Woche
