### ISSUE TITLE
Lautstärke von Werbung und Video anpassen

### ISSUE THREAD

**Issue by Xerusial** [PietSmietde/Bugs#377]
Seit ca. 2 Wochen ist die Werbung deutlich lauter als die Videos (Meine Ohren werden regelmäßig zerstört wenn im Video die Werbung einsetzt, vgl. https://www.pietsmiet.de/videos/63985-anno-brammino-das-land-der-lowen-anno-1800).

**Comment by romanzipp** [comment]
Duplicate of #40

Wir haben leider keinerleir Einfluss auf die Lautstärke der Werbung, das liegt nicht in unserer Hand
