### ISSUE TITLE
Community Vorschläge nur Upvote geht

### ISSUE THREAD

**Issue by fabian310** [PietSmietde/Bugs#384]
### Beschreibe den Fehler

Bei den Community Vorschlägen geht die Bewertung immer um einen nach oben egal ob man disliked oder liked.

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'https://www.pietsmiet.de/community/suggestions'
2. Klicke auf 'Pfeil nach oben' oder 'Pfeil nach unten'

### Erwartetes Verhalten

Richtige Bewertung

### Weitere Informationen
https://www.pietsmiet.de/community/suggestions/24807-bewertungen-hier-verbuggt

**Comment by dominovox** [comment]
Tatsächlich sieht es für mich gerade so aus, als ob Up- und Downvotes der Vorschläge gerade einfach zusammengezählt werden und als + angezeigt werden, anstatt die Differenz zu nehmen. Schauen wir uns an.

**Comment by romanzipp** [comment]
Fehler wurde behoben und wird demnächst gepatcht
