### ISSUE TITLE
Neuer Uploadplan - Ansehen-Button kommt nicht zur richtigen Zeit

### ISSUE THREAD

**Issue by qSenkMillo** [PietSmietde/Bugs#385]
### Beschreibe den Fehler

Der Button "Ansehen", bei dem neuen Uploadplan, kommt nicht rechtzeitig. Ich vermute, dass dieser erst zur Youtube-Veröffentlichung angezeigt wird, obwohl er zum Video auf PietSmiet.de verlinkt.

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu "Uploadplan" (Unterpunkt von "News")

### Erwartetes Verhalten

Der "Ansehen"-Button sollte auftauchen, sobald das Video auf Pietsmiet.de erschienen ist, da es auch zu diesem verlinkt, und nicht zu dem auf Youtube.

### Screenshots

![Pietsmiet de Uploadplan](https://user-images.githubusercontent.com/18755887/102642170-90adb800-415d-11eb-92ae-72902e175ef6.png)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows
 - Browser: Opera GX
 - Browser-Version: LVL 2 (core: 71.0.3770.456)
 - Extensions/Add-Ons installiert: Operas interner Adblock (ausgeschaltet für Pietsmiet.de), Avast Online Security

### Smartphone (bitte die Informationen vervollständigen)

nicht getestet

### Weitere Informationen

keine weiteren Informationen

**Comment by dominovox** [comment]
Danke für die Meldung - aber das ist kein Bug. Der Dienst, der die Videos zuordnet war gerade deaktiviert, weil wir nach einem Fehler gesucht haben (Zeiten aktualisieren sich random). Habe es mal verlinkt.
