### ISSUE TITLE
Wiedergabeeinstellungen Preset Kompatibilität Auflösungen falsch herum

### ISSUE THREAD

**Issue by fabian310** [PietSmietde/Bugs#386]
### Beschreibe den Fehler

Bei dem Wiedergabe-Preset "Kompatibilität" ist die eingestellte Auflösung im Player falsch herum. D.h., dass die Einstellung "240p" eigentlich 1080p ist und die Einstellung "1080p" eigentlich 240p ist.

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Gehe auf ein Video (z.B. https://www.pietsmiet.de/videos/64689-pietsmiet-lg-c10-v3-1440p#comment-250289)
2. Bei Wiedergabeeinstellungen das Preset auf "Kompatibilität"
3. Auflösung im Video ändern

### Erwartetes Verhalten

Richtige Auflösung.

**Comment by fabian310** [comment]
Getestet am PC in Chrome und Edge.

**Comment by fabian310** [comment]
Das Problem gibt es wohl schon länger
https://github.com/PietSmietde/Bugs/issues/349#issue-662920274

**Comment by romanzipp** [comment]
Danke für Meldung! Der Fehler trat tatsächlich sehr vereinzelt und nicht reproduzierbar auf, bin das Problem jetzt anders angegangen. Sollte behoben sein und wir die Tage gepatcht!
