### ISSUE TITLE
Pietcast wird in Brave Browser nicht abgespielt

### ISSUE THREAD

**Issue by mrbean457** [PietSmietde/Bugs#387]
### Beschreibe den Fehler

Wenn man versucht mit dem Brave Browser, den PietCast abzuspielen, passiert nichts

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'pietsmiet.de/pietcast'
2. Klicke auf 'einen beliebigen Podcast'
3. Klicke auf den Play Button

### Erwartetes Verhalten

Eine Beschreibung des zu erwartenden Verhaltens / Ergebnisses.

### Screenshots

Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.
(*Screenshots per Drag & Drop hier einfügen*)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10 & Ubuntu Linux
 - Browser: Brave
 - Browser-Version: 1.18.75
 - Extensions/Add-Ons installiert: Brave Shields (standardmäßig im Browser vorhanden)

### Weitere Informationen

Man kann das Problem 'temporär' beheben, in dem man in den Brave Einstellungen unter 'Sicherheit' die Einstellung 'Tracker & Anzeigenblockierung' von 'Standard' auf 'Deaktiviert' stellt

https://user-images.githubusercontent.com/44673644/102697499-6da30700-4236-11eb-955e-d824bf10988e.mp4

**Comment by romanzipp** [comment]
Den Fehler kann ich leider nicht reproduzieren. Auf allen 3 Stufen funktioniert bei mir der Podcast-Player ohne Probleme.
Tritt das Problem bei dir immernoch auf?

**Comment by mrbean457** [comment]
Das Problem tritt mittlerweile nicht mehr auf. Hat wohl ein Update das Browsers behoben
