### ISSUE TITLE
Mittlere Maustaste startet/stoppt Videos

### ISSUE THREAD

**Issue by alxhu-dev** [PietSmietde/Bugs#389]
### Beschreibe den Fehler

Wenn man mit der mittleren Maustaste auf ein Video klickt, wird dadurch das Video pausiert/fortgeführt.

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Beliebiges Video aufrufen
2. Video starten
3. Mit der mittleren Maustaste auf das Video klicken

### Erwartetes Verhalten

Die mittlere Maustaste interagiert nicht mit dem Video.

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10 (1909)
 - Browser: Firefox
 - Browser-Version: 84.0
 - Extensions/Add-Ons installiert: -

### Weitere Informationen

Die mittlere Maustaste sorgt auf einer Webseite dafür, dass man auch ohne Mausrad scrollen kann. Wenn man über diese Funktion bei einem Video scrollen möchte und man versehentlich auf das Video dabei klickt, wird das Video unterwarteterweise gestoppt.

**Comment by romanzipp** [comment]
Kann ich reproduzieren. Allerdings denke ich nicht dass sich der Aufwand zum Ändern dieses Verhaltens lohnt, da wir den Player nicht selbst entwickelt haben und somit Ressourcen ins Einarbeiten und ständige weiterentwickeln investieren müssten.
