### ISSUE TITLE
Refresh bei erneuten klicken von Menü-Button der aktuellen Seite

### ISSUE THREAD

**Issue by Flooooooooooorian** [PietSmietde/Bugs#391]
### Beschreibe das Feature

Beim anklicken des Navigations-Element welches einen zu der aktuellen Seite führen würde, soll sich die Seite refreshen.
Z.B. man befindet sich auf pietsmiet.de/ und drückt auf "home" oder aufs Pietsmiet Logo.
oder man befindet sich auf pietsmiet.de/videos und klickt auf "videos" oder auf "neuste videos"

bisher: nichts passiert.

feature: die Seite aktualisiert sich

### Gibt es Alternativen?

Ja, gibt mehrere alternativen. (F5, etc.)

**Comment by romanzipp** [comment]
Duplicate of #186
