### ISSUE TITLE
News Page wird nicht aktualisiert

### ISSUE THREAD

**Issue by jcoxall** [PietSmietde/Bugs#392]
### Beschreibe den Fehler

Die täglichen Upload Pläne erscheinen nicht mehr auf der News Seite.
Seit bereits über 2 Wochen bleibt die News Seite unverändert.

### Reproduktion

Schritte um den Fehler zu reproduzieren:
Direkter Aufruf von https://www.pietsmiet.de/news
oder
1. Navigiere zu 'News' -> 'Alle News'

### Erwartetes Verhalten

Tägliche Upload Pläne erscheinen auf der News Seite (https://www.pietsmiet.de/news)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: [Windows]
 - Browser: [Chrome, Mozilla]
 - Browser-Version: [Chrome:87.0.4280.88, Moz:84.0.2 (64-Bit)]
 - Extensions/Add-Ons installiert: [uBlock]

### Weitere Informationen

Wenn dies gewollt ist, dass keine Uploadpläne mehr auf der News Seite erscheinen sollen kann dieser "Bug" als gegenstandslos und gelöst betrachtet werden.

**Comment by romanzipp** [comment]
Wie im [letzten Uploadplan-Artikel unter "News"](https://www.pietsmiet.de/news/8307-upload-plan-am-17122020) erwähnt, befindet sich der aktuellste Uploadplan nun stets unter [/uploadplan](https://www.pietsmiet.de/uploadplan)
