### ISSUE TITLE
Neuer Uploadplan: Alte Uploadpläne einsehen

### ISSUE THREAD

**Issue by lukmi15** [PietSmietde/Bugs#393]
### Beschreibe das Feature

Der neue Uploadplan ist nett, aber die schönen Texte die Peter aktuell schreibt verschwinden leider mit dem nächsten Uploadplan. Der alte Uploadplan war wie ein News-Artikel und somit konnte man die Pläne auch später noch nachlesen. Ich schlage vor, die vergangenen Uploadpläne im Nachhinein verfügbar zu machen.

### Gibt es Alternativen?

- Nicht den gesamten Uploadplan, sonder nur den Text Archivieren
- Die Möglichkeit vom Uploadplan direkt zum Video zu springen in einen News-Artikel einbinden und den Uploadplan wieder zum News-Artikel machen

### Geht der Vorschlag aus einem bestehenden Problem hervor?

Ja, dem Problem dass ich jeden Tag den Uploadplan lesen muss wenn ich keinen von Peter's schönen Texten verpassen will

### Weitere Informationen

/

**Comment by romanzipp** [comment]
Wir haben uns gegen diese Möglichkeit entschieden
