### ISSUE TITLE
Doppelte Einträge in der Ultras Liste

### ISSUE THREAD

**Issue by TebosBrime** [PietSmietde/Bugs#394]
### Beschreibe den Fehler

Es geht um folgende Seite: https://www.pietsmiet.de/community/ultras. Auf dieser sind alle Ultras gelistet. Eigentlich sollte nur jeder einmal in der Liste auftauchen. Allerdings tauche ich mindestens 3 mal auf.

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu 'https://www.pietsmiet.de/community/ultras'
2. Scrolle nach unten um mindestens ein Nachlanden zu erzwingen
3. Nutze die Browser Suche um mehrfache Treffer zu finden

### Erwartetes Verhalten

Jeder Ultra wird nur einmal gelistet.

### Screenshots

https://i.imgur.com/axY3krV.png
https://i.imgur.com/3YEISWV.png
https://i.imgur.com/KQZRVkI.png

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows
 - Browser: Firefox
 - Browser-Version: 84
 - Extensions/Add-Ons installiert: irrelevant

### Weitere Informationen

Vermutlich durch das nachladen der Seite bedingt.

**Comment by romanzipp** [comment]
Der Fehler wurde behiben
