### ISSUE TITLE
Emoji wird in der Videoleiste unter dem Header nicht korrekt dargestellt

### ISSUE THREAD

**Issue by floh96** [PietSmietde/Bugs#395]
### Beschreibe den Fehler

😍 Emoji wird in der Videoleiste unter dem Header nicht korrekt dargestellt.

### Reproduktion

Schritte um den Fehler zu reproduzieren:

Siehe Screenshot.

### Erwartetes Verhalten

😍 Emoji wird korrekt angezeigt.

### Screenshots

![Unbenannt](https://user-images.githubusercontent.com/49693964/106282305-b344ed80-6240-11eb-890e-a7b71dc62aa9.PNG)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Microsoft Windows [Version 10.0.19042.746]
 - Browser: Chrome
 - Browser-Version: 88.0.4324.104

**Comment by romanzipp** [comment]
Sieht für mich nicht nach einem Fehler aus. Was genau meinst du?
Je nach Betriebssystem werden die Emojis anders dargestellt, das ist kein Verhalten, das wir aktiv beeinflussen.

![Screen Shot 2021-01-29 at 15 18 02](https://user-images.githubusercontent.com/11266773/106285797-30726180-6245-11eb-88d8-2ac428fb0b7c.png)

**Comment by floh96** [comment]
War vermutlich schlecht dass ich den großen Emoji im Screenshot markiert habe :D Über dem Video Titel ist doch noch die Leiste mit den Titeln der verschiedenen Videos. Da wird der Emoji nur als ?Block dargestellt.

**Comment by romanzipp** [comment]
Fehler ist behoben und wird bald gepatcht
