### ISSUE TITLE
Bug: (Relative) Zeiten auf Englisch

### ISSUE THREAD

**Issue by FallenWarrior2k** [PietSmietde/Bugs#398]
### Beschreibe den Fehler

Die relativen Zeiten an den einzelnen Elementen wie "vor drei Tagen" o.Ä. scheinen meine Systemsprache, Englisch, zu nutzen.

### Reproduktion

Direkt sichtbar auf der Startseite.

### Erwartetes Verhalten

Zeiten sollte die gleiche Sprache wie der Rest des Inhalts nutzen.

### Screenshots

![image](https://user-images.githubusercontent.com/20320149/107560357-8ea42a80-6bdd-11eb-952c-d09a1f52acd4.png)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Arch Linux
 - Browser: Firefox Developer Edition
 - Browser-Version: 86.0b7
 - Extensions/Add-Ons installiert: keine
 
Kann das Problem auch auf meinem Hauptbrowser (Chrome 88.0.4324.150) reproduzieren—dort ist es mir zuerst aufgefallen—aber den Dev-Firefox gelistet, weil das mein "blank slate testing browser" ist und Chrome zu viele Extensions installiert hat, als dass ich die hier alle sinnvoll aufzählen könnte.

### Smartphone (bitte die Informationen vervollständigen)

 - Gerät: Xiaomi POCO F1
 - Betriebssystem: LineageOS 17.1 (Android 10)
 - Browser: Chrome
 - Browser-Version: 88.0.4324.152

### Weitere Informationen

Ich konnte leider keine anderen Sprachen testen, allerdings scheint es zumindest nicht an der präferierten Content-Sprache des Browsers zu liegen. Diese habe ich versucht sowohl in Chrome als auch in Firefox versucht auf Deutsch zu stellen, jedoch hat sich dabei nichts geändert.

**Comment by romanzipp** [comment]
Dank für die Meldung. Ist tatsächlich ein Fehler, habe versehentlich die deutsche Lokalisierung fürs Frontend rausgeworfen.
Ist gefixt :) deshalb werde ich den Issue mal schließen, kann aber leider erst in 2 Wochen gepatcht werden.
