### ISSUE TITLE
Bug: Videos werden über Manjaro-Linux nicht abgespielt

### ISSUE THREAD

**Issue by StratorDE** [pietsmietde/Bugs#4]
**Beschreibe den Fehler**
Es werden keine Videos über eine Manjaro-Installation abgespielt. Es ist dabei egal, um welches Video es sich handelt. Das einzige, was man zu sehen bekommt, ist das "Play" Symbol mit dem bewegenden Kreis drumherum.

**Reproduktion**
Klicke auf x-beliebiges Video.

**Erwartetes Verhalten**
Das Video wird abgespielt.

**Screenshots**

**Desktop:**
 - Betriebssystem: 4.20.7-1-MANJARO (Arch Linux)
 - Browser: Firefox
 - Browser-Version: Firefox 65.0-0 mit firefox-i18n-de

**Comment by romanzipp** [comment]
Hast du es schonmal mit anderen Wiedergabeprofilen ausprobiert?
Verfügt Firefox unter Manjaro über Hardwarebeschleunigung?

![2019-02-10_12-28-38](https://user-images.githubusercontent.com/11266773/52533126-7b7ccc80-2d2f-11e9-85cd-e9919417e427.png)

![2019-02-10_12-28-50](https://user-images.githubusercontent.com/11266773/52533127-7e77bd00-2d2f-11e9-9cf8-763a912f2b7b.png)

**Comment by StratorDE** [comment]
Seltsam...
Gestern hab ich an den Einstellungen rumspielen können und es hat sich nix getan.
Gerade nochmal getestet und es klappt jetzt.
