### ISSUE TITLE
Snob Checkout: Lock Icon wird nicht dargestellt

### ISSUE THREAD

**Issue by TheT0fu** [PietSmietde/Bugs#401]
### Beschreibe den Fehler

Auf der Checkout Seite vom Snob Abonnement wird das Lock Icon nicht richtig dargestellt, egal ob Dark- oder Lightmode.

### Reproduktion

Schritte um den Fehler zu reproduzieren:

1. https://www.pietsmiet.de/subscribe
2. Weiter klicken bis zum Punkt Rechnungsanschrift

### Erwartetes Verhalten

Früher war da mal ein schönes grünes Lock Icon.

### Screenshots

![01-03-2021_21-25-15](https://user-images.githubusercontent.com/24474449/109554697-d4fdf280-7ad4-11eb-82d6-3446e733f621.png)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows
 - Browser: Brave, Chrome, Opera
 - Browser-Version: jeweils die aktuellste
 - Extensions/Add-Ons installiert: keine

**Comment by romanzipp** [comment]
Danke für die Meldung, der Fehler ist behoben und wird demnächst gepatcht 👍
