### ISSUE TITLE
Uploader des Videos Fehlt

### ISSUE THREAD

**Issue by Kippenhof** [PietSmietde/Bugs#405]
### Beschreibe den Fehler
Der Uploader von Videos wird nicht mehr angezeigt

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Ein Video Anklicken
2. 2. Neben dem Kanal, und der Vergangenen Zeit seid dem Upload fehlt der Name der Person, die es hochgeladen hat.

### Erwartetes Verhalten
Der Name der Person wird wie vorher dort angezeigt

### Screenshots
[So siehts bei mir aus](https://imgur.com/a/N8xFyVR)

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: WIndows
 - Browser: Opera GX
 - Browser-Version: LVL 2 (core: 73.0.3856.408)
 - Extensions/Add-Ons installiert: TwoSeven, UBlock, Honey, SponsorBlockAPI, SurfShark[Verbindung zu Berlin, DE], Ghostery, IdontCareaboutCookies, JDownloader, NetflixParty, PrivacyBadger, minerBlock, StreamParty

### Smartphone (bitte die Informationen vervollständigen)

 - Gerät: Mi 9T
 - Betriebssystem: Miui 12.0.4 Global; Android 10
 - Browser: Opera
 - Browser-Version: 62.3.3146.57763

### Weitere Informationen

Aufgetreten auf Handy und PC

**Comment by romanzipp** [comment]
Das Verhalten ist erwartet
