### ISSUE TITLE
Next Up Video auswählen - "Als nächstes abspielen/Neuste Videos zu später ansehen hinzufügen"

### ISSUE THREAD

**Issue by LeoKuenne** [PietSmietde/Bugs#407]
### Beschreibe das Feature

Beim schauen eines Videos werden am rechten Bildschirmrand neue Videos angezeugt sowie das nächste Video dortdrüber.
Es gibt in der Kachelansicht der neuen Videos einen kleinen Button in der oberen rechten Ecke des Thumbnails mit dem man das Video zu der "Später ansehen" Playliste hinzugefügt werden kann. Wenn es diesen Knopf auch bei den vorgeschlagenen Videos geben würde, ist es komfortabler sich eine Reihe an Videos anzuschauen.

### Gibt es Alternativen?

Man sucht sich alle Videos raus, die man schauen möchte, fügt sie zur "Später ansehen" Playliste hinzu und spielt dann diese Playliste ab.

### Geht der Vorschlag aus einem bestehenden Problem hervor?

Es ist mir schon öfters passiert, das ich gerne Videos anschauen möchste, die vorgeschlagen werden. Diese mache ich dann in einem neuen Tab auf um sie als "Liste" zu haben.

**Comment by romanzipp** [comment]
Duplicate of #252
