### ISSUE TITLE
Refresh der seite bei wiederholten klicken

### ISSUE THREAD

**Issue by albertlast** [PietSmietde/Bugs#408]
### Beschreibe das Feature

Ich habe die Angewohnheit, das ich eine Page refreshen in dem ich auf das Logo eine Webseite klicke z.b. https://winfuture.de/ auf den oberen Banner o.
https://www.tagesschau.de/ auf das Tagesschau Icon oben Links das die Page reloaded.

Bei PSDE kann man nur per Icon interagieren,
wenn man nicht auf Home ist, aber die Hand zum Interagieren ist dennoch angezeigt -> weckt bei mir die Erwartungshaltung das was passiert.

https://www.pietsmiet.de/ -> oben das icon klicken passiert nicht
![grafik](https://user-images.githubusercontent.com/1782906/113567515-0ce5e180-960f-11eb-99cb-9f3f3b07e191.png)
wenn man nicht in Home ist: https://www.pietsmiet.de/me/following funktioniert der icon.

Dieses Problem haben die anderen Unterseiten auch,
wenn ich auf "Für Dich" bin, kann ich nicht noch mal in "Für Dich" refreshen in dem ich den Menüpunkt neu aufrufe. 

### Gibt es Alternativen?
F5 Drücken -> ist in mobilen Browser schwer zugänglich.

**Comment by romanzipp** [comment]
Duplicate of #186
