### ISSUE TITLE
Videos fortsetzen und bereits angeschaut

### ISSUE THREAD

**Issue by MaxTheDeath** [PietSmietde/Bugs#409]
### Beschreibe den Fehler
Es wird sich nicht mehr "gemerkt" wo ich ein Video beendet habe und kann nicht dort forgesetzt werden. Ebenfells wird nicht gespeichert welche Videos schon angesehen wurden.

### Reproduktion

Schritte um den Fehler zu reproduzieren:
Schaue Video, beende es in der Mitte, komme später wieder zum Video, Video gibt mir keine Option es dort fortzusetzen, wo ich aufgehört habe. 

In der Videoübersicht wird nicht markiert welche Videos bereits geschaut wurden.

### Erwartetes Verhalten

Unter dem Video taucht eine Box auf: Sie haben dieses Video bereits geschaut. Fortsetzen bei xx:xx

Videos im Videotab ausgegraut und roter Balken zum signalisieren, wurde bereits angeschaut

### Unter welcher Version tritt der Fehler auf?

PietSmiet Portal 2.0.8 by PietSmiet

### Desktop (bitte die Informationen vervollständigen)

 - Windows 
 - Firefox
 - 87.0
 - ublock (ausgestellt für pietsmiet.de), BetterTwitchTv, Ecosia, Tampermonkey

### Weitere Informationen

Weitere Informationen über das Problem, wenn vorhanden.

**Comment by romanzipp** [comment]
Danke für die Meldung. Dieses Teilsystem ist aktuell zu Testzwecken deaktiviert, wird aber bald wieder laufen 👍

**Comment by MaxTheDeath** [comment]
Okay danke für die info ^^
