### ISSUE TITLE
Bug: Error 404 nach benutzen des Links in Youtube

### ISSUE THREAD

**Issue by 0100110101010011** [PietSmietde/Bugs#41]
**Beschreibe den Fehler**
Benutzt man den Links (Minecraft Suro 2 ) um auf die Pietsmiet.de zu gelangen, bekommt man nen 404 Error.

**Reproduktion**
Minecraft Suro 2 E1S2 --> Beschreibung --> Link zur Pietsmiet.de

**Erwartetes Verhalten**
Man kommt zur Playlist auf der Pietsmiet.de

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: [Windows]
 - Browser: [Chrome]
 - Browser-Version: [latest]

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: [z.B. iPhone6]
 - Betriebssystem: [z.B. iOS8.1]
 - Browser: [z.B. stock browser, Safari]
 - Browser-Version: [z.B. 22]
![Pietsmite](https://user-images.githubusercontent.com/53395554/62004795-f2652080-b129-11e9-892a-5ab6808f9b92.PNG)

**Weitere Informationen**
Würde ganz einfach behaupten : 

https://www.pietsmiet.de/videos/playlists/3049
Der Link ist nicht richtig oder die playlist mit der ID = 3049 existiert nicht 💃

**Comment by romanzipp** [comment]
Danke für die Meldung, die Playlists ist jetzt zugänglich.
