### ISSUE TITLE
Seite lädt für immer

### ISSUE THREAD

**Issue by pickbreaker** [PietSmietde/Bugs#413]
### Beschreibe den Fehler

Manchmal, wenn ich versuche die pietsmiet.de aufzurufen lädt die Seite ewig ohne Fortschritt zu erzielen

### Reproduktion

Schritte um den Fehler zu reproduzieren:
Öffne pietsmiet.de

### Erwartetes Verhalten

Die Seite öffnet sich

### Screenshots

https://user-images.githubusercontent.com/10897560/115259282-089ee580-a132-11eb-829a-fef744e66ebe.mp4

### Unter welcher Version tritt der Fehler auf?

Keine Ahnung

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10 1909 b18363.1500
 - Browser: Firefox 87.0 (64-Bit)
 - Extensions/Add-Ons installiert: Alle deaktiviert zum testen

**Comment by romanzipp** [comment]
Sieht aus als wäre das CDN unseres Icon Frameworks bei dir nicht erreichbar. Kannst du den Link so im Browser aufrufen?
https://unpkg.com/ionicons@5.0.0/dist/ionicons.js

**Comment by pickbreaker** [comment]
Jetzt geht es auch gerade wieder. Das ist nur manchmal so.

**Comment by romanzipp** [comment]
Denke einfach mal du hast ein schlechtes Routing zu unpkg. Das Problem wird sich aber bald erledigt haben. Demnächst wird dieses Asset direkt von uns zur Verfügung gestellt 👍
