### ISSUE TITLE
Die website open source machen

### ISSUE THREAD

**Issue by SamuelTJackson** [PietSmietde/Bugs#415]
### Beschreibe das Feature
Webiste open source machen

### Geht der Vorschlag aus einem bestehenden Problem hervor?
Viele issues die mit hilfe der community schneller und vllt. auch besser geloest werden koennen.

**Comment by romanzipp** [comment]
Wir haben keine Pläne, die Website als Open Source Projekt zu veröffentlichen.

**Comment by SamuelTJackson** [comment]
Ok schade. Ich denke das haette nur vorteile und man koennte zusammen mit der community die website um einiges verbessern.
