### ISSUE TITLE
Lautstärke der Werbung zu hoch im Vergleich zu den Videos.

### ISSUE THREAD

**Issue by SchlomSchlom** [PietSmietde/Bugs#416]
### Beschreibe den Fehler

Hallo an alle, ich weiß nicht, ob es ein wirklicher Fehler bzw. Bug ist, jedoch habe ich das "Problem" eigentlich schon immer und hoffe es könnte ein wenig behoben werden. 

Und zwar ist der Ton bei euren Videos oftmals sehr leise im Gegensatz zu den Werbungen und es kommt dann oftmals zu extrem lauter Werbung. Vielleicht könnte man die Lautstärke der Videos anheben, so dass man ein bis zwei Stufen leiser stellen könnte oder die Werbung ein wenig leiser regeln. Vielleicht geht es ja nicht nur mir so. Ich bin eigentlich ein Fan eurer Seite aber manche Videos werden dadurch oft zur Qual, wenn z.B. die Wow Werbung kommt. 

### Erwartetes Verhalten

Bessere Lautstärken Anpassung!

### Unter welcher Version tritt der Fehler auf?

PietSmiet Portal [2.0.9] by PietSmiet

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10
 - Browser: Chrome 
 - Browser-Version: 90.0.4430.93
 - Extensions/Add-Ons installiert: AdBlock Plus, jedoch bei euch immer deaktiviert!

**Comment by romanzipp** [comment]
Wir haben leider keinen Einfluss auf die Lautstärke der Werbung

**Comment by romanzipp** [comment]
Duplicate of #40
