### ISSUE TITLE
"Noch keinen Account?"-Meldung bei 2FA verschwindet nicht

### ISSUE THREAD

**Issue by bauspanderu** [PietSmietde/Bugs#419]
### Beschreibe den Fehler

Wenn ich mich anmelde, steht auf der Seite für die 2-Faktor-Authentifizierung noch der Text "Du hast noch keinen Account?"

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Auf Login klicken
2. E-Mail und Passwort eingeben

### Erwartetes Verhalten

Auf der Seite steht nur, dass ich meinen Code eingeben muss.

### Screenshots

![Screenshot_20210613_191243](https://user-images.githubusercontent.com/25692171/121816354-6146b680-cc7b-11eb-8691-cdf906edf1c4.png)

### Unter welcher Version tritt der Fehler auf?

PietSmiet Portal 2.0.11 by PietSmiet

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Manjaro Linux
 - Browser: Brave
 - Browser-Version: Version 1.25.68 Chromium: 91.0.4472.7
 - Extensions/Add-Ons installiert: -

### Weitere Informationen

Da die Meldung eine ähnliche Schriftart verwendet, war ich beim Anmelden im ersten Moment etwas verwirrt.

**Comment by romanzipp** [comment]
Danke für die Meldung, Fehler ist behoben und wird demnächst gepatcht
