### ISSUE TITLE
Regelmässig werden Kommentare geschluckt

### ISSUE THREAD

**Issue by xitara** [PietSmietde/Bugs#420]
### Beschreibe den Fehler

Wenn ich Kommentare schreibe kommt bei ca. 40% die Meldung, dass der Kommentar gepostet wurde obwohl der dann nirgends zu finden ist.

### Reproduktion

Einfach ein paar Kommentare unter einem Video schreiben, passt von ganz allein.

### Erwartetes Verhalten

Ein Kommentar sollte erscheinen, wenn die Software behauptet, er wäre erfolgreich übertragen worden.

Es könnte evtl. mit den vielen Javascript-Errors zusammen hängen die schon seit Monaten ungefixt existieren. Dass ihr euch durch div. Debugausgaben für hacker angreifbar macht, erwähne ich nur am Rand. Bin mir nicht sicher oder die zuständige/n Person/en wirklich die ausreichende Kompentenz haben um die Seite sicher zu machen und die Funktion zu garantieren.

**Comment by romanzipp** [comment]
Bitte schreibe eine E-Mail mit deinem Benutzernamen an support@pietsmiet.de
Für deinen Username auf Github konnte ich kein Profil finden. Das hat wahrscheinlich mit der Blocklist zu tun, mehr Infos in https://github.com/PietSmietde/Bugs/issues/412

**Comment by xitara** [comment]
6 Wochen um auf einen Bugreport zu reagieren ..... respekt .....
In der Zeit hab ich rausgefunden, dass es eine statische Blacklist ist, bei der die Programmierer vor 30 jahren schon fesatgestellt haben, dass sie nicht funktioniert und völliger Unfug ist.

In meinem Fall war es der Teilsatz "Das ist ja gar nicht dumm" und nach einigen tests war es dann das Wort "Dumm", das ich einem absolut positiven Zusammenhang offensichtlich verboten ist.

Dass dann aber trotzdem angezeigt wird, dass der Kommentar gespeichert wurde, ist eindeutig ein Bug (oder die Dummheit des Projektmanagers). Trotzdem wird das hier geschlosssen als wenn alles ok wäre. Schon spannend wie ihr mir Bugreports umgeht. Mir sagt das, ihr wollte nichts von Bugs hören, sie sind nur lästig.
Kein Problem, behalt ich die restlichen für mich. Dass ich theoretisch ohne Login Kommentare posten könnte, weil ihr ein massiges Sicherheitsleck habt, ist nur eins der Dinge, die ich ändern würde, wäre es meine Seite.

Viel Spass weiterhin mit dem Ignorieren von Bugreports. Schönes Leben noch.

**Comment by xitara** [comment]
Achja. Folgender Kommentar wurde, laut Meldung, auch wieder gepostet, erscheint aber nirgends. Ich sehe absolut gar nichts, was auch nur ansatzweise eine Zensur rechtfertigt. Naja, vielleicht ist "geil" ja so ein böses Wort, da die Piets sich immer so gewählt ausdrücken dass so extrem schlimme Worte gar nicht gehen.

------------------------------Geblockter Komentar ----------------------------

Wieso müssen Leute, die Vegan kochen sich immer mit der Lüge rechtfertigen, dass Fleisch eh nach nix schmeckt?
Dass in Wurst immer minderwertiges Fleisch ist, ist auch gelogen.

Essen ohne Fleisch kann richtig geil sein, aber dann ist es nicht nötig es zusätzlich schönzureden
---------------------------------------------------------------------

**Comment by romanzipp** [comment]
Kurze Randnotiz, bevor ich auf dein Feedback eingehe: Alle zwei Kommentare, die du verfasst hast, wurden gepostet und sind öffentlich einsehbar. Sie enthalten keine Wörter aus unserer Blocklist und wurden auch nicht manuell entfernt. Die beiden Kommentare - Sicht aus dem Frontend ohne Authentication - habe ich dir als Screenshot angehängt.

> 6 Wochen um auf einen Bugreport zu reagieren ..... respekt .....

Ja, das ist richtig. Wie du sehen kannst, sind in diesem Repository noch viele Issues offen, die noch bearbeitet wurden. Das liegt an vielen Gründen: Fehler werden priorisiert, werden erst angegangen wenn anhängende Projektteile überarbeitet werden, Strukturen sind mitgealert. Du bist anscheinend auch Programmierer und müsstest wissen, dass nicht bei jeder Meldung alles stehen und liegen gelassen wird, damit er behoben wird.

Zudem habe ich dir den Issue #412 verlinkt, in welchem eine Überarbeitung des Systems in Teilen angekündigt wurde.

> nach einigen tests war es dann das Wort "Dumm", das ich einem absolut positiven Zusammenhang offensichtlich verboten ist.

Nein, das ist falsch. Das Wort "dumm" wird nicht blockiert.

> Dass dann aber trotzdem angezeigt wird, dass der Kommentar gespeichert wurde, ist eindeutig ein Bug (oder die Dummheit des Projektmanagers)

Auch hier stehen mehr Informationen im angehängten Issue #412. Es ist eine Designentscheidung und keine "Dummheit". Bei zwei Personen, die für die IT zuständig sind, können keine Ressourcen aufgebracht werden um für jedes Feature alle Use-Cases inkl. Feedback abzudecken.

> Mir sagt das, ihr wollte nichts von Bugs hören, sie sind nur lästig.

Du hast diese Meldung über unseren eigens für diesen Zweck eingerichteten Bugtracker formuliert. Von 418 Meldungen wurden 357 abgeschlossen. User Feedback ist uns tatsächlich wichtig, aber Probleme werden aber priorisiert - wie bereits erwähnt.

> Kein Problem, behalt ich die restlichen für mich. Dass ich theoretisch ohne Login Kommentare posten könnte, weil ihr ein massiges Sicherheitsleck habt, ist nur eins der Dinge, die ich ändern würde, wäre es meine Seite.

Wenn du tatsächlich einen sicherheitskritischen Fehler gefunden hast, lege ich dir ans Herz, uns diesen zuzusenden. Auf so eine Sache mit Trotz zu reagieren ist der falsche Weg. Wie ich sehe bist du auch in der IT tätig und müsstest damit wissen, welcher "Verhaltenscodex" im Bezug auf Sicherheitslücken zu verfolgen ist.


Ich würde mich freuen, wenn du allgemein ein sachlicheres Verhalten an den Tag legst. Mit Drohungen, Beleidigungen und falschen Unterstellungen ist der Sache nicht geholfen.

Danke und Grüße

----

Screenshots

![Screenshot 2021-08-08 at 23 12 12](https://user-images.githubusercontent.com/11266773/128645842-ef59db52-e860-4f03-a33e-42ca5cefe893.png)
![Screenshot 2021-08-08 at 23 12 25](https://user-images.githubusercontent.com/11266773/128645844-9622529c-feb4-4d87-b481-ee5f45fba212.png)
