### ISSUE TITLE
Fehler mit Pride Info

### ISSUE THREAD

**Issue by deadepona** [PietSmietde/Bugs#422]
### Beschreibe den Fehler

Es hat auf der Homesite und auch allgemein rechts auf der Seite eine schöne Box mit Prideflaggenemojis. Diese ist mit einem i gekennzeichnet, ich als User hätte wenn ich da draufklicke eine info erwartet bei einem solchen i. Darum bin mir nicht sicher ob dies beabsichtigt ist oder ob da etwas kommen sollte, denn habe jetzt so auf die schnelle im Code auch keine Click Action dazu gefunden.

### Reproduktion

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu pietsmiet.de
2. Klicke rechts auf das kleine grün umrandete Kästchen mit den Prideflagemojis.

### Erwartetes Verhalten

Eine Info zu Pride oder ähnliches

### Unter welcher Version tritt der Fehler auf?
2.1.2

### Desktop (bitte die Informationen vervollständigen)

 - Betriebssystem: Windows 10 Pro
 - Browser: Chrome
 - keine weiteren Extensions installiert

**Comment by romanzipp** [comment]
Es handelt sich nicht um einen Fehler
