### ISSUE TITLE
Eingabe der URLs für React-Vorschläge

### ISSUE THREAD

**Issue by Milkaselnuss** [PietSmietde/Bugs#430]
### Art des Vorschlags

Verbesserung einer bestehenden Funktion

### Beschreibe das Feature

Beim Einreichen von Vorschlägen für Reacts sollte es ein separates Feld geben, in das die URL zum Youtubevideo direkt eingegeben werden kann. Dadurch wären Duplikate, die gerade bei React-Vorschlägen sehr häufig vorkommen, über die URL relativ einfach und eindeutig zu finden. Diese Duplikate sollten im Optimalfall auch nicht mehr ins System gelangen und die User stattdessen auf den bereits bestehenden Eintrag verwiesen werden.

### Geht der Vorschlag aus einem bestehenden Problem hervor?

Aktuell wird v.a. bei den React-Vorschlägen häufig dasselbe Video mehrfach vorgeschlagen. Dabei verteilen sich die Votes auf den verschiedenen Einträgen. Die Seite mit den Vorschlägen wird sehr unübersichtlich, da dasselbe Video mehrfache Einträge hat, die in der Regel von den Nutzern jedoch unterschiedlich benannt wurden. Außerdem ist unklar, wieviele unterschiedliche User tatsächlich für einen Videovorschlag sind, da sich die Votes möglicherweise aufteilen.

**Comment by romanzipp** [comment]
Danke für den Vorschlag! Die Idee habe ich umgesetzt, der Issue hier wird geschlossen sobald die Funktion live geschaltet wurde :)
