### ISSUE TITLE
Invalide Mehrwertsteuer-Anzeige für Pietsmiet-Snob Abo auf Mobilansicht

### ISSUE THREAD

**Issue by adrboettcher** [PietSmietde/Bugs#433]
### Fehlerbeschreibung

Die Mehrwertsteuer wird in der mobilen Ansicht der Website nicht korrekt angezeigt. Statt des korrekten Mehrwertsteuerbetrags wird ein `undefined` angezeigt.

Der Fehler wurde im Chrome-Browser auf Android erstmalig festgestellt, tritt jedoch auch auf andern Mobilansichten auf, wie unter der Mobilansicht von Firefox auf dem PC (mittels `STRG+SHIFT+M` aufgerufen).

### Reproduktion

1. [https://www.pietsmiet.de/subscribe](https://www.pietsmiet.de/subscribe) öffnen
2. Über Betrag hovern

### Erwartetes Verhalten

Die Mehrwertsteuer wird korrekt ausgewiesen.

### Website Version

2.1.3

### Gerät

Smartphone

### Betriebssytem

Android

### Browser

Google Chrome

### Browserversion

92.0.4515.159

### Bild zum Fehler
![Fehler_MwSt](https://user-images.githubusercontent.com/44713819/131221483-bc1dbe3e-1371-4526-8d63-d68cc8030843.jpeg)

**Comment by romanzipp** [comment]
Danke für die Meldung! Der Fehler ist behoben und wird demnächst gepatcht :)
