### ISSUE TITLE
Bug: Suche funktioniert nicht

### ISSUE THREAD

**Issue by Gameniti** [PietSmietde/Bugs#44]
**Beschreibe den Fehler**
Gerade habe ich auf Pietsmiet.de die Suche benutzt mit dem Suchbegriff "Playback Show". Ergebniss = Keine Videos gefunden

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zur Suchleiste
2. Schreibe 'Playback Show'
2. Klicke auf 'Suchen'

**Erwartetes Verhalten**
Suchergebniss mit der Playback Show

**Screenshots**
-

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Chrome
 - Browser-Version: Version 76.0.3809.100

**Weitere Informationen**
Wenn ich bei Google nach 'Playback Show pietsmiet' suche wird mir direkt als ersten Eintrag das Video angezeigt, allerdings auf Youtube.

**Comment by romanzipp** [comment]
Das liegt daran, dass die Playlist - bzw. das Video - "Playback-Show" heißt. Unsere aktuelle Suche kann diesen Fall leider noch nicht einbeziehen. Bis dato am Besten nach einzelnen Wörtern anstatt Wortkonstrukten suchen.
