### ISSUE TITLE
"Schnittchenpunkte"-Verlust nach gemeldetem Kommentar?

### ISSUE THREAD

**Issue by xLucylicious** [PietSmietde/Bugs#442]
### Fehlerbeschreibung

Hallöchen :)
Ich habe den lieben Sven die Tage schon drauf angesprochen und er wollte das weiterleiten, aber ich dachte mir, ich mach hier jetzt nochmal eine "offizielle" Meldung.
Unter dem letzten PS-Kocht Video, in dem die Jungs mein Rezept gekocht haben, wurde ich unter meinem Kommentar von jemandem beleidigt. Habe den Kommentar dann gemeldet und auch noch andere haben sich dann zu seinem Kommentar geäußert und ihn auch gemeldet. Über Nacht war der Kommentar dann verschwunden und wir alle waren auf einmal mit unseren Schnittchen-Punkten im Minusbereich. Ich hatte fast 300 und jetzt hab ich -57, also denke ich nicht, dass über Nacht auf einmal hunderte Leute trollmäßig meinen Kommentar gedownvoted haben oder so. Könnte das ein Bug sein? Ist eben auch komisch, dass das bei mehreren Leuten passiert ist, die denjenigen gemeldet hatten.
Würde mich sehr freuen, wenn da mal geschaut wird, da ich jetzt keine Kommentare mehr liken, Tags erstellen und sonstiges nicht mehr kann, was etwas Schade ist, da ich gerne drauf eingehen wollen würde, wenn die Jungs meine Quizes etc benutzen und jemand etwas dazu kommentiert. 
Vielen Dank schon mal^^

Besagtes Kochvideo: https://www.pietsmiet.de/videos/68576-zuviele-apfel-im-essen-pietsmiet-kocht-schweinefilet

Liebe Grüße,
Janina aka Lucylicious

### Reproduktion

Ok ich schreib einfach mal den Werdegang hier nochmal rein:

Habe einen Kommentar unter das Video gepostet.
Jemand schrieb einen beleidigenden Kommentar.
Ich habe den Kommentar gedownvoted und denjenigen gemeldet.
Andere haben auf seinen Kommentar kommentiert und ihn ebenfalls gemeldet.
Am nächsten Tag war sein Kommentar verschwunden und alle beteiligten waren im Minusbereich mit den Schnittchenpunkten und meine sowie ihre Kommentare hatten keine Upvotes mehr. Alle anderen Kommentare von mir auf der Seite haben allerdings noch ihre Votes. 

### Erwartetes Verhalten

Bin jetzt nicht sicher, was hier rein gehört. 
Also als Ergebnis wäre eben schon ganz cool, wenn da geschaut wird und ich hoffentlich meine Punkte wiederbekomme oder zumindest nicht mehr im Minus bin. 

### Website Version

PietSmiet Portal 2.2.2 by PietSmiet

### Gerät

Desktop

### Betriebssytem

Windows 10

### Browser

Google Chrome

**Comment by stiblu** [comment]
Heute das selbe beobachtet. Unter dem Video (https://www.pietsmiet.de/videos/68778-fragpietsfps-2419) hat sich einer über zu viele Videos beschwert und heute ist der Kommentar und die Antworten weg und ich bin im Minus. Halte es auch für unwahrscheinlich, dass da so viele gedownvoted haben, da unter den Frag Pietsmiets für gewöhnlich nicht so viel los ist. Vielleicht war der Kommentarschreiber auch getriggert und hat Downvotes auf allen Kommentaren der Profile gespammt

**Comment by xLucylicious** [comment]
Hey Roman^^ 
Ist jetzt ja schon ein paar Monate her, da dachte ich ich frag mal, ob es vielleicht irgend eine Neuigkeit zu dem Anliegen gibt 🙂

**Comment by romanzipp** [comment]
Die Vergabe von negativen Schnittchenpunkten habe ich letztens deaktiviert, dmait dort nicht noch mehr Schaden angerichtet wird. Ein richtiger Fix ist tatsächlich schon fertig und steckt in der Pipeline 👍 Wird vermutlich diese oder kommende Woche ausgerollt

**Comment by xLucylicious** [comment]
Oh, sehr cool! Danke schon mal für die Arbeit! 😊
Im Bezug auf den beschriebenen Vorfall oben, wird es da die Punkte auch irgendwie wieder zurückgeben? Also mich selbst betrifft dieser starke Punkteverlust grad nicht mehr so, da ich mittlerweile wieder im plus bin und somit wieder alles machen kann, aber andere Betroffene sind, wie ich das sehe, immer noch im Minus seitdem und können nichts bewerten, oder Tags machen etc., was etwas schade ist. Oder wird genau das mit dem Fix geändert, dass man das dennoch alles irgendwie machen kann?

**Comment by romanzipp** [comment]
Wir speichern Informationen, wie, wann und wofür Schnittchenpunkte vergeben werden. Allerdings hat der ursprüngliche Fehler ein Verhalten ausgelöst, bei dem vorige Vergaben von Schnittchenpunkten revidiert wurden. Deshalb ist es stand jetzt nicht möglich, fehlerhafte Transaktionen rückgänig zu machen. Allerdings werde ich mal zusehen, dass die Voraussetzungen für das Setzen von Tags und Bewerten von Inhalten darauf angepasst werden
