### ISSUE TITLE
Vollbildmodus Video Player

### ISSUE THREAD

**Issue by KampfMuffin** [PietSmietde/Bugs#443]
### Fehlerbeschreibung

Wenn man Videos im Vollbild guckt und die Maus auf dem Bildschirm lässt, dann verschwindet die nicht wie bei Youtube Zum beispiel sondern bleibt dauerhauft auf dem bildschirm.
Ist zwar kein riesen problem aber vielleicht etwas zum verbessern. ;)

### Reproduktion

1. Video starten
2. Vollbild schalten
3. Maus im bild lassen bis Zeitleiste verschwindet aber maus nicht

### Erwartetes Verhalten

Die Maus sollte wie die Zeitleiste verschwinden

### Website Version

PietSmiet Portal 2.2.2 by PietSmiet

### Gerät

Laptop

### Betriebssytem

Windows 10

### Browser

Microsoft Edge (neu, Chromium)

**Comment by romanzipp** [comment]
Duplicate of #428

Danke für die Meldung, ein ähnlicher Bugreport wurde bereits eingesandt

**Comment by romanzipp** [comment]
Duplicate of #428
