### ISSUE TITLE
Video Länge in Uploadplan

### ISSUE THREAD

**Issue by MVerclas** [PietSmietde/Bugs#451]
### Art des Vorschlags

Verbesserung einer bestehenden Funktion

### Beschreibe das Feature

Hi, Es wäre cool, wenn die Videolänge im Uploadplan zu sehen sein würde. Also neben den Erscheinungszeiten für PS.de und YT auch XX.XX min. Damit könnte man etwas besser planen :) 

### Gibt es Alternativen?

Alternativ auch beim Hovern oder so... 

### Geht der Vorschlag aus einem bestehenden Problem hervor?

Ohne dieses Feature sieht man halt nicht, wie lange ein Video geht.

**Comment by MarianNapi** [comment]
Soweit ich weiß werden Videos teilweise ja erst Stunden vor der Veröffentlichung hochgeladen, manchmal sogar erst nach dem eigentlichen Ziel, eine Implementierung der Videolänge im Uploadplan würde mMn nur zu Verwirrung führen, da nicht alle Zeiten angezeigt werden können.

**Comment by romanzipp** [comment]
Ich sehe genau das selbe Problem wie @MarianNapi. Viele Parameter sind bei Veröffentlichung des Uploadplans noch nicht verfügbar, die Information über die Videolänge ist bei einem veröffentlichtem Video nur einen Klickt entfernt
