### ISSUE TITLE
Suche sucht nur nach ganzen Wörtern

### ISSUE THREAD

**Issue by MaiAndr** [PietSmietde/Bugs#454]
### Fehlerbeschreibung

Die Suchfunktion findet nur Videos in denen das eingegebene Wort genau so wie eingegeben darin vorkommt.
Wenn zum Beispiel nach "Rekord" gesucht wird, werden die Videos die "Rekorde" oder "Rekorden" im Titel haben nicht angezeigt.

### Reproduktion

1. "Rekord" in das Suchfeld eingeben und suchen
2. "Rekorde" in das Suchfeld eingeben und suchen
3. "Rekorden" in das Suchfeld eingeben und suchen

### Erwartetes Verhalten

Wenn nach "Rekord" gesucht wird, sollen auch die Videos mit "Rekorde" und "Rekorden" angezeigt werden.

### Website Version

2.2.8

### Gerät

Desktop

### Betriebssytem

Windows 10

### Browser

Firefox

**Comment by romanzipp** [comment]
Danke für die Meldung. Ein ähnlicher Bugreport wurde bereits geöffnet, weshalb ich diesen schließen und dort verlinken werde, damit wir alles gesammelt an einer Stelle haben

**Comment by romanzipp** [comment]
Duplicate of #439
