### ISSUE TITLE
Bug: Links leiten auf Haupsteite zurück 

### ISSUE THREAD

**Issue by oliverthms** [PietSmietde/Bugs#46]
**Beschreibe den Fehler**
Wenn ich auf Registrienen auf pietsmiet.de/login gehe, werde ich auf die hauptseite zurückgeleitet. Das selbe ist auf im Post der neuen Webseite mit dem Darkmode. (Ka ob da noch mehr sind)

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/
2. Klicke auf Login                                          |  Die neue PieSmiet.de
3. Klicke auf Du hast noch keinen Account?    |  Darkmode

**Erwartetes Verhalten**
Weiterleitung auf pietsmiet.de

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10
 - Browser: Firefox/ Microsoft Edge
 - Browser-Version: Firefox 68.0.1 (64 Bit)

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: [z.B. iPhone6]
 - Betriebssystem: [z.B. iOS8.1]
 - Browser: [z.B. stock browser, Safari]
 - Browser-Version: [z.B. 22]

**Weitere Informationen**
Weiter Informationen über das Problem, wenn vorhanden.

**Comment by romanzipp** [comment]
Die Registrierung ist aktuell deaktiviert. Dass der Textbaustein an der Stelle fälschlicherweise angezeigt wurde ist behoben.
