### ISSUE TITLE
OAuth-Funktionalität für Externe bereitstellen

### ISSUE THREAD

**Issue by florian-berger** [PietSmietde/Bugs#469]
### Art des Vorschlags

Komplett neues Feature

### Beschreibe das Feature

In der Watchbuddy-App kann man sich mittels PietSmiet.de-Account anmelden. Ich würde mir wünschen, diese Möglichkeit auch externen Entwicklern bereitzustellen - ggf. auch nach vorheriger Verifizierung oder ähnlichem. 

### Geht der Vorschlag aus einem bestehenden Problem hervor?

Da ich eine eigene Anwendung bereitstelle, die stark mit der PietSmiet-Community verbunden ist, würde ich mir wünschen, diese Login-Möglichkeit ebenfalls für meine App haben zu können.

**Comment by romanzipp** [comment]
Bitte schreibe mir dafür eine Mail an roman.zipp@pietsmiet.de
Wir planen aktuell nicht, die API für freie externe Nutzung zu öffnen
