### ISSUE TITLE
Feature: Sortierung der eigenen Kommentare nach Zeit

### ISSUE THREAD

**Issue by lukri100** [PietSmietde/Bugs#47]
**Beschreibe das Feature**
Aktuell werden die eigenen Kommentare auf der Profilseite nach Likes sortiert. Wenn man aber nach seinen kürzlichen Kommentaren suchen möchte, ist eine solche Sortierung sehr unpraktisch. Deswegen wäre es ganz gut, wenn man die Sortierung aussuchen könnte.

**Gibt es Alternativen?**
Alternativ kann man natürlich alles lassen wie es jetzt ist. Wird nur bei sehr vielen Kommentaren wohl irgendwann ziemlich unübersichtlich, wenn man seine neuesten Kommentare sehen will.

**Weitere Informationen**
Eine Sortierung nach Aktualität würde die Übersichtlichkeit erhöhen. Vielleicht ist an der Stelle ja ein drop down menu möglich, mit dem man seine präferierte Sortierung einstellen kann.

**Comment by Gameniti** [comment]
Du kannst in den Einstellungen unter Erscheinungsbild die Kommentare nach Datum statt Beliebtheit sortieren.
