### ISSUE TITLE
Webseite ruckelt

### ISSUE THREAD

**Issue by sebastiancx** [PietSmietde/Bugs#472]
### Fehlerbeschreibung

Egal was ich mache bzw. wie ich scrolle oder auf welcher Unterseite ich mich befinde, es ruckelt ziemlich stark. Das Problem hab ich bei anderen Seiten nicht und fällt mir nur hier auf.

### Reproduktion

Beliebige (Unter-)Seite aufrufen und schauen, ob es flüssig läuft

### Erwartetes Verhalten

Ruckelfrei?

### Website Version

PietSmiet Portal 2.4.3 by PietSmiet 

### Gerät

Laptop

### Betriebssytem

macOS 12 Beta

### Browser

Firefox

### Browserversion

103.0.1

### Extensions & Add-Ons

Diverse Add-Ons und Extensions, die es aber auch schon vorher gab als bei mir die Seite noch flüssig lief. Kann gerne alle aufzählen, sind aber überwiegend nur Devtools

### Weitere Informationen / Screenshots

In der Issue-Auswahl Betriebssystem steht im Übrigen "macOS 12 (Beta)", dabei ist macOS 12 doch nicht mehr in der Beta, oder nicht? Ich zumindest hab keine Beta-Version.

**Comment by romanzipp** [comment]
Das dürfte der selbe Fehler wie #474 sein, mittlerweile habe ich diese Style-Regel entfernt
