### ISSUE TITLE
Ruckelige Website auf M1 MacBookAir

### ISSUE THREAD

**Issue by dingu23** [PietSmietde/Bugs#474]
### Fehlerbeschreibung

Die Website ist extrem ruckelig, vor allem beim Scrollen auf meinem MacBookAir. Das Problem existiert seit ungefähr 2 Monaten würde ich schätzen.

### Reproduktion

1. Use MacBook M1
2. Go to pietsmiet.de
3. Scroll up&down

### Erwartetes Verhalten

Ruckeliges Scrollen

### Website Version

 PietSmiet Portal 2.4.3 by PietSmiet 

### Gerät

Laptop

### Betriebssytem

macOS 12 Beta, macOS (anderes)

### Browser

Firefox

### Browserversion

103.0.2

### Extensions & Add-Ons

KeePassXC, DuckDuckGo, Privacy Badger

**Comment by romanzipp** [comment]
Es sieht aus, als würde [ein Bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1718471) das Verhalten verursachen. Ich werde dafür einen Fix patchen.

In der Zwischenzeit könnte es helfen, die `layout.css.backdrop-filter.enabled` Regel in den [`about:config`](https://support.mozilla.org/en-US/kb/about-config-editor-firefox) Einstellungen zu deaktivieren.

**Comment by dingu23** [comment]
Danke! Das Deaktivieren der Regel hat geholfen.
