### ISSUE TITLE
Bug: Emoji-Liste beim Kommentieren fehlt

### ISSUE THREAD

**Issue by lukri100** [PietSmietde/Bugs#48]
**Beschreibe den Fehler**
Ich weiß nicht ob gewollt oder Bug, aber ich zähle es provisorisch mal als Bug: Auf der alten Seite gab es, wenn man einen Kommentar schreiben und dabei Emojis verwenden wollte, eine Liste, aus der man Emojis aussuchen konnte. Die gibt es jetzt nicht mehr.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Schreibe einen Kommentar zu einem Video oder Artikel.
2. Bemerke die nicht vorhandene Emoji-Liste.
3. Repeat

**Erwartetes Verhalten**
Einblendung der Option, eine Emoji-Liste aufzurufen, beim Schreiben eines Kommentars.

**Screenshots**
Hab leider keine von der alten Seite.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 (1809)
 - Browser: Firefox 
 - Browser-Version: 68.0.1

**Comment by romanzipp** [comment]
Wir haben vorerst keine Pläne, den Emoji-Picker wieder einzubauen. Dafür gibt es alternativ Browser-Erweiterungen oder eine eingebaute Funktion unter macOS
