### ISSUE TITLE
Video weg: https://www.pietsmiet.de/videos/74591-ich-weiss-was-du-nicht-weisst-mit-bonjwa-und-teams

### ISSUE THREAD

**Issue by Derlustischeglueckshase** [PietSmietde/Bugs#488]
### Fehlerbeschreibung

Nicht autorisiert

### Reproduktion

Gehe auf https://www.pietsmiet.de/videos/74591-ich-weiss-was-du-nicht-weisst-mit-bonjwa-und-teams

### Erwartetes Verhalten

Video  vorhanden

### Website Version

PietSmiet Portal 2.4.7 by PietSmiet

### Gerät

Laptop

### Betriebssytem

Windows 10

### Browser

Google Chrome

### Weitere Informationen / Screenshots

![image](https://user-images.githubusercontent.com/122994284/213202342-d0cbe1ae-9ea8-42ee-aabb-aaa09e93b8fb.png)

**Comment by romanzipp** [comment]
Video ist wieder online
