### ISSUE TITLE
Authentifikator Code falsch und Passwort zurücksetzen funktioniert nicht

### ISSUE THREAD

**Issue by LuckyNighthunter** [PietSmietde/Bugs#489]
### Fehlerbeschreibung

Wie im Titel stehend:
Als ich mich einloggen wollte, wollte er von mir den Authentifikator Code. Mittlerweile hats funktioniert weiß nich worans lag, aber er sagte mir vorher immer er wäre falsch. Und beim Passwort zurücksetzen bekam ich zwar den Link, aber der Link ist dann angeblich abgelaufen obwohl ich keine 10 sekunden gebraucht hab um den zu nutzen.

### Reproduktion

Authentifikator App nutzen um sich einzuloggen.
Passwort vergessen Link zuschicken lassen und in der Email die hinterlegt ist auf ps.de den Link anklicken und das Passwort ändern

### Erwartetes Verhalten

Der Link für das ändern des Passwort sollte nicht abgelaufen sein und der Authentifikator Code sollte funktioniereten

### Website Version

PietSmiet Portal 2.4.10 by PietSmiet

### Gerät

Desktop

### Betriebssytem

Windows 10

### Browser

Firefox

### Browserversion

109.0

### Extensions & Add-Ons

uBlock Origin 7

**Comment by romanzipp** [comment]
Schreibe uns dafür bitte eine E-Mail von deinem PietSmiet.de Account an support@pietsmiet.de
