### ISSUE TITLE
Bug: Das Wort "Thumbnail" wird bei leerem Avatar schlecht dargestellt

### ISSUE THREAD

**Issue by Vulturemox** [PietSmietde/Bugs#49]
Wenn ein User keinen Avatar gesetzt hat, wird standardgemäß das Wort "Thumbnail" angezeigt. Dies ist aber eine schlechte Lösung, da das Wort über den Bereich hinaus ragt.

![Screenshot_20190815_215504](https://user-images.githubusercontent.com/31129858/63122762-cd850000-bfa7-11e9-8e57-9ad8d4dc305c.png)

Schritte um den Fehler zu reproduzieren:
1. Navigiere zu beliebigem Nutzerprofil und siehe Top-Benutzer

**Erwartetes Verhalten**
Mögliche Lösung: Bei CSS die overflow property auf hidden setzen (https://www.w3schools.com/cssref/css3_pr_text-overflow.asp) oder einen Standard Avatar bei allen Nutzern festlegen.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Ubuntu
 - Browser: Firefox 68.0.1 (64-Bit)

**Comment by moritzruth** [comment]
Hängt wohl mit #49 zusammen, aber in dem Issue geht es um eine andere Stelle, außerdem wird nicht das Icon für kaputte Bilder angezeigt (oder macht Firefox das einfach nicht?).

**Comment by Vulturemox** [comment]
Firefox zeigt nicht gefundene Bilder gar nicht an, im Opera Browser (Chromium Engine) sieht es dann so aus:
![Screenshot_20190815_224938](https://user-images.githubusercontent.com/31129858/63125951-1ee4bd80-bfaf-11e9-93ab-ea11c26c939c.png)

**Comment by manuel-st** [comment]
Vielleicht sollte es ein Standard-Bild geben, falls man noch kein Profilbild gesetzt hat.

**Comment by romanzipp** [comment]
Wir haben ein Standardbild hinzugefügt, wenn der Avatar nicht gefunden wird
