### ISSUE TITLE
CDN pietcdn.de nicht über IPv6 erreichbar

### ISSUE THREAD

**Issue by Leseratte10** [PietSmietde/Bugs#490]
### Fehlerbeschreibung

Hallo liebes PietSmiet-Team, 

der bereits gemeldete und als gelöst markierte Bug #38 scheint sich irgendwann wieder eingeschlichen zu haben - die Domain `lft1.pietcdn.de` hat zwar einen AAAA-Record (eine IPv6-Adresse) im DNS, diese antwortet aber auf keinerlei Verbindungsversuche; es gibt einen Timeout und der Browser springt zurück auf IPv4. 

Aktuell sehe ich folgende DNS-Einträge für die Domain: 

```
lft1.pietcdn.de.	300	IN	AAAA	2a00:c98:2050:a04f:2::130
lft1.pietcdn.de.	300	IN	A	37.58.53.130
```

Beim Verbindungsaufbau zur genannten IPv6-Adresse gibt es einen Timeout, getestet sowohl von einem Deutsche-Glasfaser-Internetanschluss als auch aus einem Hetzner-Rechenzentrum. Die IPv4-Adresse funktioniert in beiden Fällen problemlos. 

Ebenfalls hat anscheinend die Domain `pietcdn.de` selbst (die vom Browser aufgerufen wird und dann zu lft1.pietcdn.de weiterleitet) noch nicht mal einen AAAA-Record, vielleicht könntet ihr den ja auch noch hinzufügen damit die Webseite (wieder?) vollständig über IPv6 funktioniert.

### Reproduktion

1. Öffne ein Video auf pietsmiet.de, als Beispiel das heutige "[Frag PietSmiet](https://www.pietsmiet.de/videos/74654-fragpietsmiet2863)", von einem IPv6-fähigen Internetanschluss 
2. Stelle fest, dass die Verbindung(en) zu den Videoservern `pietcdn.de` und `lft1.pietcdn.de` über IPv4 und nicht über IPv6 stattfinden.

Oder auf einer Linux-Konsole:
`wget -4 lft1.pietcdn.de` gibt wie erwartet "404 Not found" zurück. 
`wget -6 lft1.pietcdn.de` hingegen nur "Verbindungsaufbau zu lft1.pietcdn.de ...", und dann nach einiger Zeit "Verbindungsaufbau fehlgeschlagen: Die Wartezeit für die Verbindung ist abgelaufen"

`dig pietcdn.de -tAAAA` liefert erst gar keinen AAAA-Record mit IPv6-Adresse zurück.

### Erwartetes Verhalten

Ich würde erwarten dass der Server `pietcdn.de` einen (funktionierenden) AAAA-Eintrag im DNS erhält, und dass der bestehende AAAA-Eintrag für den Server `lft1.pietcdn.de` auch erfolgreich erreichbar ist; damit die PietSmiet-Webseite auch an einem reinen IPv6-Internetanschluss ohne IPv4 funktioniert.

Für den Fall, dass die IPv6-inkompatibilität aktuell gewollt ist und z. B. aus technischen Gründen aktuell noch nicht umgesetzt werden kann, sollte zumindest der defekte AAAA-Eintrag aus dem DNS von `lft1.pietcdn.de` entfernt werden damit die Browser nicht versuchen, eine unerreichbare IP zu erreichen. Die ideale Lösung wäre allerdings vollständig funktionierendes IPv6.

EDIT: Eventuell kann so eine Fehlkonfiguration auch für andere Bugs wie #486 verantwortlich sein.

### Website Version

PietSmiet Portal 2.4.12 by PietSmiet

**Comment by dominovox** [comment]
IPv6 ist fixed.

**Comment by Leseratte10** [comment]
Wow, das ging schnell, danke. 
Könntet ihr der Domain `pietcdn.de` selbst (ohne Subdomain) auch noch eine IPv6-Adresse verpassen oder geht das technisch aus irgendwelchen Gründen noch nicht? 
Im aktuellen Zustand laufen die Videos jetzt wieder über IPv6, aber an einem reinen IPv6-Anschluss ohne IPv4 funktioniert die Seite nicht.

**Comment by Leseratte10** [comment]
Ping, @dominovox ist die Frage untergegangen weil der Bugreport schon geschlossen ist?
Die Videostreams an sich laufen jetzt zwar über IPv6, aber die Seite benötigt (wegen diesem fehlenden Eintrag) immer noch IPv4 um zu funktionieren.
