### ISSUE TITLE
Impressum, Datenschutz,... ohne Inhalt

### ISSUE THREAD

**Issue by Stefan-MyBB** [PietSmietde/Bugs#497]
### Fehlerbeschreibung

Auf folgenden Seiten werden nur die Überschriften angezeigt, die eigentlichen Inhalte fehlen:
https://www.pietsmiet.de/impressum
https://www.pietsmiet.de/teilnahmebedingungen
https://www.pietsmiet.de/datenschutz
https://www.pietsmiet.de/nutzungsbedingungen

### Reproduktion

Seite aufrufen

### Erwartetes Verhalten

Inhalte werden angezeigt

### Website Version

PietSmiet Portal 2.5.0 by PietSmiet

### Gerät

Desktop, Smartphone

### Betriebssytem

Windows 11, Android

### Browser

Vivaldi, Microsoft Edge (neu, Chromium)

**Comment by romanzipp** [comment]
Danke für die Meldung! Der Fehler wurde behoben.
