### ISSUE TITLE
Feature: Dark-Mode sowie Verbesserungen am Design

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#5]
**Beschreibe das Feature**
Ein Dark-Mode, welches entweder durch den Nutzer oder anhand einer spezifischen Uhrzeit aktiviert wird, wäre für Pietsmiet.de wohl eines der besten Features. Daher habe ich mal ein Konzept erstellt, wie so etwas aussehen könnte.<br>
**Fakten über das _Redesign_**
- Die Suchleiste ist nun breiter um dem Nutzer bei längeren Eingaben mehr Details anzuzeigen.
- Die Buttons sind nun runder, da dies von dem Menschlichen Gehirn als Harmonischer erkannt wird.
https://www.sciencefocus.com/science/why-do-we-find-circles-so-beautiful/
- Farbe des Footers ist nun schwarz bzw. die gleiche Farbe wie die Navbar und hat keinen Blaustich mehr.
<br>

Fertige Scripts, für so etwas gibt es bereits: https://codepen.io/HarlemSquirrel/pen/NdMebZ<br>
![dark-mode](https://user-images.githubusercontent.com/18743976/52526163-f5bc3b00-2cb4-11e9-8362-d931aa5b0df7.png)

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
<br>
Aufgrund der hellen Farben ohne einen Dark-Mode, werden die Augen der Nutzer mehr angestrengt. Die Folgen hieraus sind:
- Trockene Augen aufgrund der hellen Farben:
https://www.ncbi.nlm.nih.gov/pubmed/29797453
- Juckende Augen
- Kopfschmerzen
- Schlechter Schlaf aufgrund von exposition zu einer exzessivem Menge an Blaulicht.
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5473809/

**Weitere Verbesserungen, die Angebracht wären:**
- Hervorheben des "Registrieren" Button für die daraus resultierende größere Menge an registrierten Mitglieder.
- Einheitliches Design bei den Thumbnails für "Upload-Plan" sowie "News".
- Margin des Dropdowns an die Höhe der Navbar anpassen.
- Verbesserung des Layouts der Frontpage.

**Comment by YoKoGFX** [comment]
Re layout:
Ich habe mich noch mal an ein besseres Layout gesetzt. Hierbei habe ich mich etwas an: https://www.reddit.com/r/PietSmiet/comments/5yr5ew/pietsmiet_redesign/ orientiert, aber aktuelle Trends mitbedacht.
<br>
Es hat weniger Videos, da aktuell nicht mehr wie 6 Videos pro Tag hochgeladen werden. Dadurch werden immer aktuelle Videos angezeigt. Dies könnte dann über den "Mehr anzeigen" Button erweitert werden.

**Screenshot:**<br>
![redesign3](https://user-images.githubusercontent.com/18743976/52535733-374ef380-2d52-11e9-96c7-585504d380cc.jpg)

**Comment by romanzipp** [comment]
Das letzte Redesign sieht sehr schick aus. Es ist bereits ein Darkmode zu Teilen vorhanden, der mit invertieren von Farben arbeitet, dieser ist allerdings nicht so weit, dass wir ihn veröffentlichen wollen.

Mit dem Komplettrework des Frontends wird voraussichtlich auch ein kompatibler Darkmode kommen.
Beim Layout sind wir natürlich an die Page Container-Grenzen gebunden, aber ich denke man kann designtechnisch noch einiges rausholen.

Ich würde diesen Issue mal schließen und nach dem Rework ggf. als Re zum Feedback nutzen. Jetzt noch große Designänderungen am aktuellen System zu machen halte ich für redundant.

**Comment by florian262000** [comment]
Gibt es bereits einen zeitlichen Plan für das Rework?

**Comment by romanzipp** [comment]
Wir haben schon einen zufriedenstellenden Stand, müssen aber noch auf ein paar Sachen Externer warten. Auf ein genaues Datum würde ich mich noch nicht festlegen, aber wir arbeiten daran, das Rework so schnell wie möglich zu releasen.

Damit wird auch eine Ankündigungsnews mit allen Neuerungen & Verbesserungen erscheinen.
