### ISSUE TITLE
PietCast spielt nicht ab

### ISSUE THREAD

**Issue by Irahs** [PietSmietde/Bugs#501]
### Fehlerbeschreibung

Ich kann leider seit nun mehreren Wochen keine Folge PietCast mehr hören. Manchmal steht auf Höhe der Wiedergabeleiste „An audio error has occurred“, manchmal steht dort gar nichts. In den Kommentaren einer neuen Folge habe ich mal gesehen, dass ich damit nicht alleine bin. Leider gibt es die für mich nächste Folge auch nicht YouTube.

### Reproduktion

Gehe auf die Seite einer beliebigen PietCast-Folge.

### Erwartetes Verhalten

Der Podcast sollte abspielen / abspielen, nachdem man „Play“ drückt.

### Website Version

2.5.1

### Gerät

Desktop

### Betriebssytem

Windows 10

### Browser

Google Chrome

**Comment by romanzipp** [comment]
Fehler wurde behoben. Danke für den Hinweis!
