### ISSUE TITLE
Aktualisierung 

### ISSUE THREAD

**Issue by Slin1988** [PietSmietde/Bugs#504]
### Art des Vorschlags

anderes

### Beschreibe das Feature

Könntet ihr einstellen das wenn man wenn man auf der Frontpage ist und erneut auf Home Butten klickt sich die Seite neu läde? Ich hab mich bei einigen Seiten so daran gewöhnt und bei euch wäre es auch sehr schön.

**Comment by romanzipp** [comment]
Das ist momentan nicht sauber umsetzbar. In den kommenden Wochen veröfentlichen wir eine überarbeitete version.

Duplicate of https://github.com/PietSmietde/Bugs/issues/186

**Comment by romanzipp** [comment]
Duplicate of #186
