### ISSUE TITLE
Feature: Eigener Bugtracker auf der Website

### ISSUE THREAD

**Issue by moritzruth** [PietSmietde/Bugs#51]
**Beschreibe das Feature**
Statt GitHub als Bugtracker zu verwenden, soll ein Bugtracker in die Website integriert werden. Dies hätte den Vorteil, dass man zum Einreichen eines Bugs keinen GitHub Account besitzen muss.

**Comment by romanzipp** [comment]
Momentan ist es die einfachste Lösung, auch da wir die Issues in unserem Projekt auf GitHub referenzieren können.
