### ISSUE TITLE
Bug: Rechtschreibfehler Nutzungsbedingungen

### ISSUE THREAD

**Issue by Gameniti** [PietSmietde/Bugs#54]
**Beschreibe den Fehler**
In der E-Mail mit den Nutzungsbedingungen sind Rechtschreibfehler.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Je nachdem wie man die E-Mail mit den Bedingungen bekommt.

**Erwartetes Verhalten**
Statt "Nutzungsbeidngungen" "Nutzungsbedingungen" und statt "unser" "unserer"

**Screenshots**
Gerade zu Faul dafür..

**Comment by Vulturemox** [comment]
Es gibt noch weitere Fehler:
Nutzungsbedingungen:
"beinträchtigen" -> "b**ee**inträchtigen" (Abschnitt Faire Nutzung)
"nachhaltig icherzustellen" -> "nachhaltig **s**icherzustellen" (Abschnitt Redaktionelle Unabhängigkeit)
"Merchendise" -> "Merch**a**ndise" (Abschnitt Beteiligte Unternehmen)

Datenschutzerklärung:
"Rechtgrundlage" -> "Recht**s**grundlage" (in mehreren Abschnitten)
