### ISSUE TITLE
Bug: Footer Background SVG falsche Farbe

### ISSUE THREAD

**Issue by YoKoGFX** [PietSmietde/Bugs#55]
**Beschreibe den Fehler**
Das SVG vom Footer (url(/storage/images/static/footer-background.svg) hat eine falsche Farbe, im vergleich zum Footer.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de
2. Scrolle zum  Footer

**Erwartetes Verhalten**
Farbe sollte gleich sein.

**Comment by romanzipp** [comment]
Bei mir sieht alles korrekt aus. Mit und ohne Darkmode

![2019-08-17_13-29-34](https://user-images.githubusercontent.com/11266773/63211105-1b5a4f00-c0f3-11e9-825b-ebc07883ce2c.png)
![2019-08-17_13-29-44](https://user-images.githubusercontent.com/11266773/63211106-1bf2e580-c0f3-11e9-98d6-aee69b7e9090.png)
