### ISSUE TITLE
Bug: Avatar von den Team-Mitgliedern

### ISSUE THREAD

**Issue by YoKoGFX** [PietSmietde/Bugs#56]
**Beschreibe den Fehler**
Meiner Meinung nach sollte man die Bilder der Personen unter: "ALLES CHECKER" richtig skalieren. Ich habe mal einen Screen mit einem korrekten Bild erstellt. Auch sollten vielleicht von den Personen, die kein Bild haben Illustrationen erstellt werden, dass es nicht so buggy aussieht. Wäre vielleicht sogar ne Video Idee :D "Wir suchen auf Fiverr Leute, die unsere dritte Reihe zeichnet".

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de
2. Scrolle zu "ALLES CHECKER"

**Erwartetes Verhalten**
Alle Köpfe sollten komplett zu sehen sein.

**Screenshots**
<img width="1440" alt="Bildschirmfoto 2019-08-16 um 08 46 23" src="https://user-images.githubusercontent.com/18743976/63148790-8d9f3680-c002-11e9-9ca3-c04b78cf12bf.png">

**Comment by manuel-st** [comment]
Die Position der Bilder von Sep und Domi sollten eventuell auch vertauscht werden.
