### ISSUE TITLE
Feature: Taste "F" beendet Vollbild bei Videos wieder

### ISSUE THREAD

**Issue by manuel-st** [PietSmietde/Bugs#59]
**Beschreibe das Feature**
Ich weiß nicht, ob ihr das beim Player einstellen könnt, es wäre aber schön, wenn es funktioniert: Ein Druck auf die Taste **F** beendet den Vollbildmodus wieder, wenn das Video im Vollbild läuft, so wie es auch bei YouTube der Fall ist.

**Gibt es Alternativen?**
Die **ESC**-Taste beendet auch den Vollbild-Modus. "Mute/Unmute" und den "Cinema-Modus" kann man allerdings auch mit nur einer Taste hin und her wechseln.

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Nein.

**Comment by romanzipp** [comment]
Habe auf die Schnelle keine gute Lösung dafür gefunden. Ich denke nicht, dass es ein breaking Bug ist.
