### ISSUE TITLE
Feature: HSTS und TLS 1.3

### ISSUE THREAD

**Issue by YoKoGFX** [PietSmietde/Bugs#6]
**Beschreibe das Feature**
Aufgrund der relativ großen Menge an Nutzern, die Pietsmiet.de aufrufen und dort einen Account haben, wäre es sinnvoll mehr Maßnahmen zu ergreifen um den Diebstahl von Daten zu vermeiden.

**Es gibt hierfür einige, wohl bereits implementierte, Schutzmaßnahmen um dies zu verhindern:**
- WAP (Web Application Firewall) durch CloudFlare
- Sanitation von Input-Feldern in PHP
- HTTPS

**SSL-Stripping:**
SSL-Stripping ist möglich wenn ein Nutzer z.B. die Website über einen Hotspot oder Öffentlich nicht verschlüsselten WLAN Zugang besucht. Es ist aber ebenso möglich, wenn das bestehende Netz kompromittiert ist. Das Prinzip ist relativ einfach, bei einem SSL-Stripping Angriff wird die bestehende `https://` zu einer `http://` umgewandelt und die Daten in Klartext versendet.<br>
Zu diesem Thema gibt es ein gutes Video, aber auch sehr viel Dokumentation:
https://www.youtube.com/watch?v=MFol6IMbZ7Y
https://www.owasp.org/index.php/HTTP_Strict_Transport_Security_Cheat_Sheet

Das Prinzip von `HSTS` probiert nun dieses bestehende Problem zu "beheben". Der Client akzeptiert bei aktivem `HSTS` nur noch Verbindungen, die über `https://` laufen. Dadurch ist die Datenübertragung nur noch Verschlüsselt.
<br><br>

Es besteht aber noch immer ein Problem, bei dem Erstaufruf der Website. Hierfür kann man die Website in https://hstspreload.org/ eintragen und dadurch wird ist es nur noch möglich über `https://` aufzurufen. Selbst bei einem abgelaufenen SSL-Zertifikat!

**Gibt es Alternativen?**
Alternativen gibt es keine, aber sinnvolle Ergänzungen zu `HSTS`!
Hierzu zählen:
- `X-Content-Type-Options`
- `X-Frame-Options` (Verhinderung von iFrame Einbindung von pietsmiet.de auf anderen Websites)
- `X-XSS-Protection`
- Aktivierung von `TLS 1.3` bei CloudFlare, da es die Website schneller und sicherer macht

Infos über TLS. 1.3:
https://www.cloudflare.com/learning-resources/tls-1-3/

**Comment by AlexanderLangguth** [comment]
Man könnte auch Security Policy Reporting aktivieren um auf Angriffsversuche aufmerksam gemacht zu werden.
Cloudflare hat ja schon die `report-uri` für `expect-ct` gesetzt, aber für `Content-Security-Policy` (vermutlich erstmal report-only) und `HTTP Public Key Pinning` kann man es auch aktivieren.
