### ISSUE TITLE
Bug: Pietsmiet.de Merch

### ISSUE THREAD

**Issue by Oraniuk** [PietSmietde/Bugs#60]
Die Merch Seite auf der Pietsmiet.de seite wird nicht angezeigt

Oben Rechts unter "Shop" auf "Merch" klicken.

Normalerweise sollte hier die Seite mit dem Pietsmiet Merch angezeigt werden

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10
 - Browser: Chrome
 - Browser-Version: 76.0.3809.100

**Comment by manuel-st** [comment]
Mit Firefox 68 geht es

**Comment by romanzipp** [comment]
Wahrscheinlich wird der Shop durch eine Extension geblockt. Ich habe einen Text am Ende der Seite hinzugefügt, der sichtbar ist, wenn der iframe des Shops blockiert ist.
