### ISSUE TITLE
Bug: 2-Faktor Auth issuer & label collisions

### ISSUE THREAD

**Issue by TebosBrime** [PietSmietde/Bugs#68]
**Beschreibe das Feature**
Wenn man 2 Faktor Auth über den QR Code hinzufügt, wird die Webseite in die eigene App aufgenommen. Nur ist das Problem, dass dieser nur nach der eigenen Mail Adresse benannt wurde. So erkennt man den Account nicht wieder, sollte man ihn nicht umbenennen. Andere Webseiten schreiben noch den eigenen Namen davor. Bitte tut dies auch.

**Gibt es Alternativen?**
-/-

**Geht der Vorschlag aus einem bestehenden Problem hervor?**
Bei gewissen Apps können andere 2 Wege Codes überschrieben werden.

**Weitere Informationen**
-/-

**Comment by romanzipp** [comment]
Ist behoben. Der issuer wird jetzt auch im QR label mit `:` Prefix angehangen, wie in der [Spec](https://github.com/google/google-authenticator/wiki/Key-Uri-Format#label) beschrieben
