### ISSUE TITLE
Bug: Großschreibung von Fehlern bei Registrierung und Login

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#7]
**Beschreibe den Fehler**
Die Grammatik sowie die Großschreibung bei Fehlermeldungen ist nicht korrekt.<br>

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/register
2. Klicke auf `Registrieren`

**Erwartetes Verhalten**
Die Rechtschreibung sollte korrekt sein.

**Screenshots**
<img width="480" alt="bildschirmfoto 2019-02-10 um 09 26 21" src="https://user-images.githubusercontent.com/18743976/52531456-1c5e8e00-2d16-11e9-9f42-ceb620a86714.png">

**Desktop (bitte die Informationen vervollständigen):**
* Betriebssystem: MacOS 10.14.3 (18D109)
* Browser: Safari
* Browser-Version: Version 12.0.3 (14606.4.5)

**Weitere Informationen**
Wenn möglich wäre es wahrscheinlich sinnvoll den Benutzernamen vor dem Absenden per Javascript zu Validieren, da dies bereits beim Passwort-Feld implementiert ist und bei einer falschen Eingabe eine   Server-Abfrage spart.

**Comment by romanzipp** [comment]
Die eingegebenen Daten werden, wie du richtig erkannt hast, serverseitig validiert. Es ist bereits eine komplett neue Version des Frontends in Arbeit, in welcher Vue.js für die Clientseite eingesetzt wird und clientseitige Validierung bereits eingebaut ist. Die "Rechtschreibfehler" resultieren daraus, dass der Validator mit den Namen der Inputfelder arbeitet, dies würde ich erstmal nicht als wichtig sehen, die Eingabefehler sind ja allemal erkennbar.
Die Formulare der Registrierung und des Logins werde ich nachträglich mit ein wenig Clientvalidierung austatten, für den Rest muss auf den Frontendrework gewartet werden.

**Comment by YoKoGFX** [comment]
Anscheinend ist nun die Serverseitige Validierung verschwunden bzw. kaputt. Denn wenn man jetzt irgendwas in die Felder eingibt, bekommt man beim Absenden einen 500er Fehler.

**Comment by romanzipp** [comment]
Kann ich so nicht reproduzieren. Auf welcher Seite passiert das mit welchen Eingabewerten?

**Comment by YoKoGFX** [comment]
https://www.pietsmiet.de/register einfach überall "s" eingeben. Dadurch umgeht man anscheinend das Validieren. (Auch bei der email)
