### ISSUE TITLE
Bug: Schlechte Auflösung Thumbnail(s)

### ISSUE THREAD

**Issue by Sandrotto** [PietSmietde/Bugs#70]
**Beschreibe den Fehler**
Die Thumbnails auf der Startseite scheinen in schlechter Auflösung angezeigt zu werden. Es handelt sich hierbei um das neueste (?) Video und die News. Es ist sehr wahrscheinlich ein browserspezifisches Problem, da Firefox und Edge **nicht** davon betroffen sind. Trotzdem sollte man es sich mal anschauen. Wenn man schon auf der Seite ist (z.B auf dem Reiter Videos) und den "Home" Button oben klickt werden die Thumbnails wie gewohnt in guter Qualität angezeigt. Es scheint also nur der Fall zu sein wenn man von außen auf die PS.de Startseite navigiert

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere per Browserzeile zu [www.pietsmiet.de](url)

**Erwartetes Verhalten**
Thumbnails sind in guter Qualität. 

**Screenshots**

Hier die Problemfälle:

![chrome_2019-08-16_23-35-17](https://user-images.githubusercontent.com/47162093/63199865-76eaf500-c07f-11e9-9840-b0acd597fc6d.png)

Hier geht die Auflösung meiner Meinung nach vollkommen klar:

![2019-08-16_23-35-30](https://user-images.githubusercontent.com/47162093/63199864-76525e80-c07f-11e9-80d6-f8372aa4f48d.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10
 - Browser: Chrome
 - Browser-Version: 76.0.3809.100 (Offizieller Build) (64-Bit)

**Weitere Informationen**
Auflösung d. Bildschirms: FullHD
Zoomstufe: 100% (Normal)

**Comment by Vulturemox** [comment]
Fällt vor allem auf wenn man sich einen Artikel ansieht:
![Screenshot_20190817_095220](https://user-images.githubusercontent.com/31129858/63208479-c60f4500-c0d4-11e9-8d0c-bc69a9f8b91d.png)

**Comment by romanzipp** [comment]
Die fehlerhafte Auflösung in einem Artikel ist in allen Browsern vorhanden.
Die zu kleinen Thumbnailgrößen auf der Startseite konnte ich aber nur auf Google Chrome reproduzieren (Sonst fine in Firefox, Opera). Kannst du das bestätigen?
