### ISSUE TITLE
Bug: Wenn ein Neuer Tab geöffnet wird ist man nicht mehr eingeloggt

### ISSUE THREAD

**Issue by moppi-iron** [PietSmietde/Bugs#71]
**Beschreibe den Fehler**
Wenn man einen Neuen Tab öffnet ist dieser nicht mehr eingelogt
Der Alte bleibt im eingeloggten zustand bestehen

**Reproduktion**
1. Einloggen
2. Auf einen beliebigen link mit dem Mausrad drücken bzw. rechte Maustaste und in neuem Tab/Fenster öffnen

**Desktop (bitte die Informationen vervollständigen):**
 -  Windows 10 64-BIt
 - Firefox 68.0.1

**Comment by lukri100** [comment]
Kann ich nicht reproduzieren (Win10 1809, Firefox 68.0.2).

**Comment by romanzipp** [comment]
Höchstwahrscheinlich hast du deinen Browser so eingestellt, dass alle Websitedaten beim Schließen des Tabs gelöscht werden. Kann den Fehler nicht reproduzieren.
