### ISSUE TITLE
Bug: Message Box wird doppelt angezeigt

### ISSUE THREAD

**Issue by BronaldDumb** [PietSmietde/Bugs#74]
In der ersten Seite der "PietSmiet React" Playlist ist unter der Werbung eine (ich glaube man nennt das so) Message Box bzw. so ein mini Fenster mit dem Text "Hast du Fehler auf der Seite entdeckt? Hilf uns weiter, indem du uns diese mitteilst!" aufgetaucht. Aber nicht einmal, sondern zwei mal und zwar direkt untereinander, mit einer leeren, etwas rausgehobenen Box in der Mitte.

Leider kann ich den Fehler nicht genau reproduzieren, da ich auf eine der boxen geklickt habe um den Fehler zu melden und die seit dem gar nicht mehr erscheint. Aber ich glaube es war so:
1. Ein Video der Playlist gucken (in meinem Fall: https://www.pietsmiet.de/videos/55510-react-monoton-unfahig-6?playlist=617-pietsmiet-react)
2. Rechts beim Video auf die zugehörige Playlist drücken

Vielleicht guckt ihr euch das mal an. Ist nicht gravierend, aber halt ne Kleinigkeit die bei den drei verschiedenen Fenstern dieser Art wenn man in einer Playlist ist schon viel Übersichtlichkeit zurück bringen würde, wäre es nur eine Mittelung und nicht zwei+eine leere.

https://pietsmiet.zurlino.eu
(Weiterleitung zu Imgur)

 - Betriebssystem: MacOS Mojave 10.14.6
 - Browser: Safari
 - Browser-Version: 12

**Comment by romanzipp** [comment]
Danke für die Meldung. Konnte den Fehler leider auch nicht reproduzieren. Issue kann gerne wieder geöffnet werden, wenn er reproduzierbar ist.
