### ISSUE TITLE
Bug: Mauszeiger verschwindet nicht während des Abspielens von Videos

### ISSUE THREAD

**Issue by lxender** [PietSmietde/Bugs#75]
**Beschreibe den Fehler**
Der Mauszeiger/Cursor  verschwindet nicht, wenn man ein Video abspielt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu einem Video, zB. [Adventure Maps](https://www.pietsmiet.de/videos/55579-minecraft-adventuremap-1-uncut)
1a. Falls du Werbung siehst, warte sie ab
2. Starte das Video, aktiviere den Vollbildmodus (egal ob durch den F-Shortcut, Vollbildmodus-Button, oder Doppelklick auf das Video)
3. Warte, dass die Playback-Controls verschwinden

**Erwartetes Verhalten**
Der Mauszeiger sollte im 3. Schritt auch verschwinden.

**Tatsächliches Verhalten**
Der Mauszeiger verschwindet im 3. Schritt nicht.

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Chrome
 - Browser-Version: 76.0.3809.100

**Comment by lxender** [comment]
Ich hab gerade bemerkt, dass Twitch das gleiche Problem hat. Vielleicht liegt es an Chrome

**Comment by TebosBrime** [comment]
Identisch bei Edge

**Comment by romanzipp** [comment]
Das ist leider keine Funktion, die wir beeinflussen können.
