### ISSUE TITLE
Feature: Twitch Subscriber

### ISSUE THREAD

**Issue by BronaldDumb** [PietSmietde/Bugs#77]
Aktuell ist es bereits möglich seinen Account mit Twitch zu verbinden, jedoch glaube ich nicht, dass es dadurch irgendwelche Features gibt. Es wäre nice wenn man vielleicht ein kleines PS Logo hinter dem Namen anzeigen lässt wenn der entsprechende User Subscriber ist. 

Ich fürchte es gibt keine Alternativen.

Probleme werden damit nicht behoben, aber das gucken von Streams und das Abonnieren werden gefördert und weiter belohnt

**Comment by Patti2101** [comment]
Eventuell könnte man Twitch Subscribern ja auch keine Werbung mehr auf Pietsmiet.de anzeigen, da es leider bis jetzt noch keine Möglichkeit von der Pietsmiet.de selbst gibt ein kostenpflichtiges Abo abzuschließen um keine Werbung zu erhalten.

**Comment by BronaldDumb** [comment]
Ist halt die Frage was die 2 Werbebanner und die ganzen Werbe Clips so bringen. Aber man könnte ja sonst Stufe 2 und/oder 3 Abos die Möglichkeit geben werbefrei zu sein, wenn sich das rechnet. Dann hätten die endlich mal ein ordentliches Feature und zumindest ich würde echt drüber nachdenken das zu holen

**Comment by BronaldDumb** [comment]
> Eventuell könnte man Twitch Subscribern ja auch keine Werbung mehr auf Pietsmiet.de anzeigen, da es leider bis jetzt noch keine Möglichkeit von der Pietsmiet.de selbst gibt ein kostenpflichtiges Abo abzuschließen um keine Werbung zu erhalten.

Ist halt die Frage was die 2 Werbebanner und die ganzen Werbe Clips so bringen. Aber man könnte ja sonst Stufe 2 und/oder 3 Abos die Möglichkeit geben werbefrei zu sein, wenn sich das rechnet. Dann hätten die endlich mal ein ordentliches Feature und zumindest ich würde echt drüber nachdenken das zu holen 
@Patti2101

**Comment by romanzipp** [comment]
Wir haben bereits andere Pläne für das Thema. Die Markierung von Twitch Subs in den Kommentaren haben wir bereits auf der Liste!
