### ISSUE TITLE
Bug: Seltsame Textbox Position beim Antworten auf Kommentare

### ISSUE THREAD

**Issue by dippa-1** [PietSmietde/Bugs#79]
**Beschreibe den Fehler**
Beim Antworten auf einen Kommentar erscheint die Textbox wieder ganz oben und man muss erst hochscrollen.

**Reproduktion**
Auf Kommentar antworten, der weiter unten ist.

**Erwartetes Verhalten**
So wie bei YouTube, dass die Textbox unter dem Kommentar erscheint, auf den man antworten will.

**Comment by romanzipp** [comment]
Normalerweise sollte der Browser automatisch hochscrollen. Welchen Browser verwendest du?

**Comment by dippa-1** [comment]
> Normalerweise sollte der Browser automatisch hochscrollen. Welchen Browser verwendest du?

Microsoft Edge Chromium Beta.
Mir ist aber eben aufgefallen, dass er doch hochscrollt, aber die Textbox von dem gruenen Pietsmiet Banner verdeckt wird.

**Comment by Tanielll** [comment]
> Normalerweise sollte der Browser automatisch hochscrollen. Welchen Browser verwendest du?

Es wird zwar automatisch hochgescrollt bei mir, aber es wäre dennoch schöner, wenn die Textbox zum Antworten unter dem Kommentar erscheint, dem man antwortet. So war es vor dem Update ja auch. Wäre einfach etwas angenehmer zu nutzen, aber ist auch kein großes Problem.
