### ISSUE TITLE
Bug: Falsche Icons bei Seiten (pagination)

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#8]
**Beschreibe den Fehler**
Auf allen Seiten mit einer Pagination werden falsche Icons angezeigt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/news/allgemein?page=1
2. Navigiere zu https://www.pietsmiet.de/news/allgemein?page=2

**Erwartetes Verhalten**
Alle Icons sollten gleich sein und es sollte wie auf dem dritten Bild aussehen.

**Screenshots**
<img width="315" alt="bildschirmfoto 2019-02-10 um 09 55 47" src="https://user-images.githubusercontent.com/18743976/52531734-37330180-2d1a-11e9-8108-4e36cce9befa.png">
<img width="339" alt="bildschirmfoto 2019-02-10 um 09 55 56" src="https://user-images.githubusercontent.com/18743976/52531733-37330180-2d1a-11e9-924a-0ff7cb39baba.png">
<img width="310" alt="bildschirmfoto 2019-02-10 um 09 56 04" src="https://user-images.githubusercontent.com/18743976/52531732-369a6b00-2d1a-11e9-9244-0eaf03adaee9.png">

**Desktop (bitte die Informationen vervollständigen):**
* Betriebssystem: MacOS 10.14.3 (18D109)
* Browser: Safari
* Browser-Version: Version 12.0.3 (14606.4.5)

**Comment by romanzipp** [comment]
Ist gefixt

**Comment by YoKoGFX** [comment]
@romanzipp Icons sind nun Falschrum:
https://www.pietsmiet.de/news/allgemein?page=2

<img width="334" alt="bildschirmfoto 2019-02-13 um 10 31 52" src="https://user-images.githubusercontent.com/18743976/52701481-9a22d380-2f7a-11e9-8367-41e8b54fc298.png">

**Comment by romanzipp** [comment]
Ist gefixt (erneut :D)

**Comment by YoKoGFX** [comment]
:D
