### ISSUE TITLE
Bug: 1000 Schnittchen (die Punkte) werden nur als 1 Punkt im Tag angezeigt

### ISSUE THREAD

**Issue by BronaldDumb** [PietSmietde/Bugs#81]
Gestern habe ich (sirbruno) die 1000 Schnittchen Marke überschritten. Statt aber in Kommentaren meine fast 1100 stehen zu haben, steht da einfach eine 1. Hovert man auf die 1 steht da jedoch meine echte Schnittchen Zahl

1. Gehe auf das Video https://www.pietsmiet.de/videos/55510-react-monoton-unfahig-6?playlist=617-pietsmiet-react 
2. Guck in die Kommentare um meine Account zu Finden. Name = SirBruno.
3. hover über die 1 die meine Schnittchen Zahl anzeigt
(zudem könnten man auf mein Profil gehen, da sieht man genau den Fehler 14 Seiten lang)

Ich erhoffe, dass meine echte Schnitchenzahl angezeigt wird

https://imgur.com/TRCLi5m

 - Betriebssystem: MacOS Ojave
 - Browser: Safar
 - Browser-Version: 12

**Comment by BronaldDumb** [comment]
Ich sehe gerade, dass der Fehler bereits in https://github.com/PietSmietde/Bugs/issues/80 angegangen wurde. Diese Meldung hier kann man also denke ich schließen

**Comment by romanzipp** [comment]
duplicate of #80
