### ISSUE TITLE
Bug: Tooltip im Darkmode nicht lesbar

### ISSUE THREAD

**Issue by HerrDepence** [PietSmietde/Bugs#82]
**Beschreibe den Fehler**
Tooltips-Schrift im Darkmode nicht sichtbar.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Darkmode aktivieren

**Erwartetes Verhalten**
Tooltip-Schirft in sollte schwarz sein und damit lesbar im Darkmode.

**Screenshots**
![20190818120850-HCQnJD](https://user-images.githubusercontent.com/7407580/63223216-83bc3580-c1b2-11e9-8d59-7253d5ccca0a.png)
![20190818121000-lyfWbq](https://user-images.githubusercontent.com/7407580/63223222-95054200-c1b2-11e9-9529-a7923873e392.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Chrome, Edge
 - Browser-Version: 76, Edge keine Ahnung

**Comment by manuel-st** [comment]
Ist der gleiche Fehler wie #72

**Comment by romanzipp** [comment]
Duplicate of #72
