### ISSUE TITLE
Bug: Social Verbindung mit Twitter lässt sich nicht einrichten

### ISSUE THREAD

**Issue by Patti2101** [PietSmietde/Bugs#85]
**Beschreibe den Fehler**
Wenn man seine Social Verbindung mit Twitter herstellen will erhält man die Fehlermeldung: "Invalid data received from Twitter".

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 Home (10.01.18362 Build 18362
 - Browser: Google Chrome
 - Browser-Version: Version 76.0.3809.100 (Offizieller Build) (64-Bit)

**Comment by pickbreaker** [comment]
Gleicher Fehler bei mir auf Win 10 Home Build 18362.356 mit Firefox 69.0.1. And also in my Ubuntu 18.04 LTS VM with Kernel 5.3 and the same Firefox.
