### ISSUE TITLE
Bug: Beim Login wird Darkmode nicht aktiviert

### ISSUE THREAD

**Issue by manuel-st** [PietSmietde/Bugs#86]
**Beschreibe den Fehler**
Ich habe in den Einstellungen den Darkmode aktviert. Wenn ich den Browser schließe - wobei bei mir automatisch der Cache gelöscht wird - und ich pietsmiet.de dann erneut aufrufe, wird mir die Seite im hellen Modus angezeigt (das ist noch kein Bug). Melde ich mich dann aber an, bleibt die Seite im hellen Modus und der Darkmode wird in den Einstellungen deaktiviert.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Darkmode in den Einstellungen aktivieren
2. Abmelden
3. Tab mit pietsmiet.de schließen
4. Cache löschen
5. pietsmiet.de aufrufen. Die Seite ist nun im hellen Modus
6. Anmelden
7. Die Seite bleibt im hellen Modus, der 

**Erwartetes Verhalten**
Beim Anmelden wird automatisch der Darkmode aktiviert, wenn man das in den Einstellungen angegeben hat.

**Desktop**
 - Betriebssystem: Ubuntu
 - Browser: Firefox
 - Browser-Version: 68.0.2

**Comment by romanzipp** [comment]
Momentan werden die Einstellungen unter "Erscheinungsbild" im Browser selbst gespeichert und somit auch beim Schließen geleert. Wir haben vorerst andere Prioritäten, aber es ist geplant, dass die Einstellungen übergreifend im Account gespeichert werden.
