### ISSUE TITLE
Bug: neben dem Uploadplan wird der gleiche als "Vorschlag" angezeigt

### ISSUE THREAD

**Issue by LionHenry** [PietSmietde/Bugs#88]
**Beschreibe den Fehler**
https://www.pietsmiet.de/news/6865-upload-plan-am-19082019
neben dem Uploadplan vom 19.08.19 wird der gleiche nochmal vorgeschlagen. hinzufügen könnte man auch noch, dass generell uploadpläne vorgschlagen werden. eigentlich gibt es ja nicht wirklich einen grund einen alten uploadplan lesen zu wollen

**Reproduktion**
https://www.pietsmiet.de/news/6865-upload-plan-am-19082019 
auf den link clicken. funktionierte bei mir am desktop mehrfach hintereinander, sowohl eingeloggt als auch im privaten tab

**Erwartetes Verhalten**
das nicht vorschlagen, oder sogar generell keine uploadpläne von vor mehreren tagen vorschlagen

**Screenshots**
Wenn nötig, Screenshot anfügen, welche das Problem veranschaulichen.

**Desktop (bitte die Informationen vervollständigen):**
-Windows 7 Pro
-Firefox
-68.0.1 64-Bit

**Comment by romanzipp** [comment]
Wir haben bereits ein Konzept für die Überarbeitung der Uploadpläne. Vorerst werden wir das System so lassen.
