### ISSUE TITLE
Bug: nicht funktionierendes streamen über Chromecast 

### ISSUE THREAD

**Issue by MultiPetef** [PietSmietde/Bugs#89]
**Beschreibe den Fehler**
Ich möchte das Video über Chromecast streamen. Bevor ich das Video über die Website starte erscheint ein Button "Play on TV". Danach gibt es ein endlosen Ladekreis und nach refreshen mit f5 ist er verbunden, aber das Video startet nicht

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. starte ein Video
2. klicke auf "Play on TV" 
3. Verbinde den Chromecast

**Erwartetes Verhalten**
kurze Verbindung und automatischer Start des Videos auf dem Chromecast

**Screenshots**
![Ladekreis](https://user-images.githubusercontent.com/54269744/63258365-2ee4f180-c27c-11e9-9c6d-d04b9623db74.png)
![verbunden](https://user-images.githubusercontent.com/54269744/63258366-2ee4f180-c27c-11e9-82df-110049335f2a.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 Pro 1903 18362.295
 - Browser: Chrome 
 - Browser-Version: 76.0.3809.100

**Smartphone (bitte die Informationen vervollständigen):**
 - Gerät: Samsung Galaxy S10
 - Betriebssystem: Android 9
 - Browser: Google Chrome
 - Browser-Version: 76.0.3809.111

**Weitere Informationen**
Chromecast Firmware 1.40.156414

**Comment by CaptTaifun** [comment]
Keine Ahnung ob das mittlerweile gefixt wurde, allerdings steht [auf dieser Seite](https://www.pietsmiet.de/news/6550-website-reboot) ganz unten folgendes:

Chromecast-Support: Ja, da einige bereits gefragt haben: wir werden die Chromecast-Unterstützung in einigen Wochen nach weiteren, größeren Tests freischalten. Gebt uns da bitte noch ein bisschen Zeit.

Daher denke ich mal wird das kein Bug sein, sondern wurde lediglich noch nicht vollständig implementiert/freigeschalten. Sollte von den Leuten auf Twitter oder sonst wo was aktuelleres dazu zu finden sein, dann ist dem so. Aber dachte ich lasse dich das mal wissen ^^

**Comment by MultiPetef** [comment]
Das habe ich gar nicht richtig gelesen. Habe mich beim ersten anschauen eines Videos gewundert warum es Chromecast Unterstützung bietet. 

Na wenn das noch nicht richtig funktioniert dann warte ich halt. :(

**Comment by CaptTaifun** [comment]
Wie gesagt, kann natürlich sein, dass es mittlerweile funktioniert bzw. funktionieren sollte, wollte jetzt also keine falschen Hoffnungen machen. Das ist zumindest der Stand, denn ich hab. Sollten die auf Twitter/Facebook oder so (was ich nicht verwende) mittlerweile was anderes geschrieben haben, dann weiß ich davon eben nichts ^^. Aber dachte ich sag dir mal bescheid für den Fall, dass du es eben nicht gesehen hast ^^.

**Comment by romanzipp** [comment]
Ich habe mich gestern nochmal darum bemüht, allerdings scheint die Angelegenheit komplexer zu sein als gedacht. Die Funktion hat definitiv Priorität für uns.
