### ISSUE TITLE
Bug: Video-Player falsche Breite und Höhe beim laden

### ISSUE THREAD

**Issue by YoKoGFX** [pietsmietde/Bugs#9]
**Beschreibe den Fehler**
Beim Laden der Website bzw. aller Seiten mit einem Video-Player, besteht eine kurze Zeit, beidem der Player nicht die komplette Größe besitzt.

**Fix für das Problem:**
`aspect` hat ein `padding-top: 56.25%;`, dies muss entfernt werden (wird nach dem Laden eh auf `display:none` gesetzt) und folgendes muss zum CSS ergänzt werden:
<br>
```
.video-js{
width: 100%;
height: 100%
}
```

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere zu https://www.pietsmiet.de/videos/frag-pietsmiet/51400-fps-1417
2. Auf den Video-Player schauen.

**Erwartetes Verhalten**
Der Video-Player, bzw. der Container sollte die volle Höhe und Breite einnehmen.

**Screenshots**
Bilder des Problems mit und ohne Bugfix<br>
**Ohne Fix:**<br>
<img width="825" alt="bildschirmfoto 2019-02-10 um 10 22 53" src="https://user-images.githubusercontent.com/18743976/52532001-5d5aa080-2d1e-11e9-8a88-8afb58e8c911.png">

**Mit Fix:**<br>
<img width="1052" alt="bildschirmfoto 2019-02-10 um 10 30 22" src="https://user-images.githubusercontent.com/18743976/52532067-48cad800-2d1f-11e9-87f2-4ca84b06bf7b.png">

**Desktop (bitte die Informationen vervollständigen):**
* Betriebssystem: MacOS 10.14.3 (18D109)
* Browser: Safari
* Browser-Version: Version 12.0.3 (14606.4.5)

**Comment by romanzipp** [comment]
Danke für die Meldung. Es ist bereits ein Fix für die visuellen Fehler bei der Playererstellung in der Pipeline. Dieser ist momentan noch im Review, sollte also in den kommenden Tagen behoben sein.

**Comment by YoKoGFX** [comment]
@romanzipp Kein Problem, schön zu hören, dass Ihr daran arbeitet. :)
