### ISSUE TITLE
Bug: Neue Registrierung versagt beim Laden des ReCaptchas

### ISSUE THREAD

**Issue by CaptTaifun** [PietSmietde/Bugs#90]
**Beschreibe den Fehler**
Bei der Registrierung wird das Durchführen eines ReCaptchas erwartet, welcher allerdings nicht geladen/angezeigt wird. Erst nach mehrmaligen Klicken auf Registrieren erscheint weiter unten die TextBox zur Eingabe des ReCaptchas, welcher zwar, laut DOM, vorhanden ist, aber dennoch nicht angezeigt wird. [Dies](https://www.google.com/recaptcha/api/fallback?k=6LeRenMUAAAAAJmF7sVSHWjzx_5rpRc_CXkqflq9&hl=de&v=v1563777128698&t=40169) ist der Link, welcher vom IFrame eingebettet wird. Öffnet man diesen, erhält man folgende Meldung: "Ein Fehler ist aufgetreten. Bitte aktualisiere die Seite." Habe den ReCaptcha auch nur zufällig gesehen, weil die Fehlermeldung von der Register-Seite ne Fehlermeldung warf, von wegen fehlender ReCaptcha.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Auf https://www.pietsmiet.de/register alle Felder (Benutzername, E-Mail Adresse, Passwort, Passwort wiederholen, Nutzungsbedingungen/Datenschutzerklärung) ausfüllen.
2. Auf Registrieren klicken und sehen, dass nichts passiert.
3. Noch 1-2 Mal auf Registrieren klicken und kurz warten, irgendwann erscheint die TextBox für den ReCaptcha, aber eben nicht der ReCaptcha selbst.

**Erwartetes Verhalten**
Dass der ReCaptcha geladen wird und die Registrierung dadurch abgeschlossen werden kann.

**Screenshots**
![image](https://user-images.githubusercontent.com/30515484/63266802-05829080-c291-11e9-826b-e42ce87d7469.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows 10 1903 (18362.295)
 - Browser: Google Chrome 64-bit
 - Browser-Version: v76.0.3809.100

**Smartphone (bitte die Informationen vervollständigen):**
(Nicht getestet, zumal ich ein Windows Phone habe, worauf ihr vermutlich nicht mehr achten werdet, da der Support am 31.12. endet ^^).

**Comment by romanzipp** [comment]
Ich habe vor ca. 10 Minuten ein neues Update veröffentlicht. Konnte den Fehler nicht reproduzieren. Hast du eventuell Erweiterungen aktiv?

**Comment by CaptTaifun** [comment]
Hab ich, allerdings jetzt nichts, was das Verhalten beeinflussen sollte. Hab die Seite jetzt mal in einem privaten Fenster aufgemacht, dort wird der ReCaptcha tatsächlich angezeigt. Hab nun alle Erweiterungen mal deaktiviert und den Cache gecleared, aber nada. Im normalen Chrome-Fenster wird es mir nach wie vor nicht gezeigt, nur im privaten.

Ich mein, wenn ich der einzige mit dem Problem bin, ist es ja nicht so schlimm, immerhin hat es jetzt im privaten Fenster funktioniert und einloggen geht auch wunderbar. Also wenn ich der einzige mit dem Problem bin, dann hat sich das ja erledigt ^^.

Falls es aber relevant sein sollte, was für Erweiterungen ich aktiviert hatte:
ColorZilla, Grid Ruler, Steam Inventory Helper, Stylus (aber ohne Styles, quasi Standardeinstellung) und svg-grabber.
