### ISSUE TITLE
Bug: Profilseite wird in Edge nicht dargestellt

### ISSUE THREAD

**Issue by AlexanderLangguth** [PietSmietde/Bugs#92]
**Beschreibe den Fehler**
Während ich die Browserkompatibilität für https://github.com/PietSmietde/Bugs/issues/91 testen wollte fiel mir auf das in MS-Edge die Profilseite nicht geladen werden konnte.
Es werden lediglich die leeren Templates angezeigt.

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere mit MS-Edge zu 'https://www.pietsmiet.de/profile/2'

**Erwartetes Verhalten**
Die Profilseite wird angezeigt.

**Screenshots**
![image](https://user-images.githubusercontent.com/3857921/63292826-dc7cf280-c2c6-11e9-98fd-dad31e91cd91.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Win
 - Browser: MS-Edge
 - Browser-Version: Microsoft Edge 42.17134.1.0

**Comment by romanzipp** [comment]
Kann ich nicht reproduzieren. Werden Fehler in der Dev Console geloggt?

**Comment by AlexanderLangguth** [comment]
Jop:
```
{  
   description:"Object doesn't support property or method 'finally'",
   message:"Object doesn't support property or method 'finally'",
   number:-2146827850,
   stack:"TypeError: Object doesn't support property or method 'finally' at fetchUser (https://www.pietsmiet.de/js/app.routes.js?id=9518d58da0fe42b6eaad:1:4223) at o.mounted (https://www.pietsmiet.de/js/app.routes.js?id=9518d58da0fe42b6eaad:1:3855) at Ht (https://www.pietsmiet.de/js/app.js?id=580ef5268ce2739d6e3a:1:97927) at en (https://www.pietsmiet.de/js/app.js?id=580ef5268ce2739d6e3a:1:111798) at Re.insert (https://www.pietsmiet.de/js/app.js?id=580ef5268ce2739d6e3a:1:106812) at Ht (https://www.pietsmiet.de/js/app.js?id=580ef5268ce2739d6e3a:1:97927) at n (https://www.pietsmiet.de/js/app.js?id=580ef5268ce2739d6e3a:1:99744) at S (https://www.pietsmiet.de/js/app.js?id=580ef5268ce2739d6e3a:1:146524) at Anonymous function (https://www.pietsmiet.de/js/app.js?id=580ef5268ce2739d6e3a:1:147892) at t.prototype._update (https://www.pietsmiet.de/js/app.js?id=580ef5268ce2739d6e3a:1:120223)"
}
```
Sieht so aus als würde ein Polyfill für Promise.finally fehlen.
Seltsam. Obwohl laut [caniuse](https://caniuse.com/#feat=promise-finally) finally schon unterstützt werden sollte. Allerdings scheint dort schon die Chromium Version referenziert zu sein.
Aber tatsächlich führt sowas wie `Promise.resolve().finally(_ => console.log("finally executed"))` nur zu Fehlermeldungen.
