### ISSUE TITLE
Bug: Seite nicht mit IE kompatibel

### ISSUE THREAD

**Issue by AlexanderLangguth** [PietSmietde/Bugs#93]
**Beschreibe den Fehler**
Ich weiß nicht was eure targeted Browser sind, aber IE wird nicht unterstützt, da kein Polyfill für Promises geladen wird.

Fehlermeldung in der Konsole: `"Promise" ist undefiniert`

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Navigiere mit IE zu 'https://www.pietsmiet.de/'
2. Leere Seite

**Erwartetes Verhalten**
Die Seite wird angezeigt.

**Screenshots**
![image](https://user-images.githubusercontent.com/3857921/63293260-f5d26e80-c2c7-11e9-807e-9536a05c9ab8.png)

![image](https://user-images.githubusercontent.com/3857921/63293249-e94e1600-c2c7-11e9-8d34-e81f1198c5d4.png)

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Win
 - Browser: IE
 - Browser-Version: 11.950.17134.0

**Weitere Informationen**
Wenn ihr IE nicht unterstützen wollt dann schließt das Ticket einfach.
Wenn ihr wissen wollt wie viele eurer Nutzer das Problem haben benutzt einfach https://caniuse.com/#feat=promises und importiert eure Analytics Daten.

**Comment by romanzipp** [comment]
Wir haben keine Pläne, IE11 oder niedriger zu unterstützen.

**Comment by AlexanderLangguth** [comment]
Dachte ich mir schon, aber ich dachte ich melde es einfach mal.
