### ISSUE TITLE
Bug: Kein Vollbild beim IPad 

### ISSUE THREAD

**Issue by Bohlinio** [PietSmietde/Bugs#96]
beim iPad und iPhone gibt es keine vollen Vollbild Modus mehr.
Die BILD und Bild funktion ist nicht gegeben.

**Comment by romanzipp** [comment]
Bitte aktualisiere die Seite. Besteht der Fehler immernoch?

**Comment by Bohlinio** [comment]
Moin,
Geht wider alles 👌

Von meinem iPhone gesendet
