### ISSUE TITLE
Bug: Falsche Fehlermeldung bei Tags

### ISSUE THREAD

**Issue by Kalmer1** [PietSmietde/Bugs#97]
**Beschreibe den Fehler**
Wenn man unangemeldet auf Tags klickt (auf das X+) steht da nur "Du musst dafür angemeldet" ohne das nötige "sein"

**Reproduktion**
Schritte um den Fehler zu reproduzieren:
1. Nicht angemeldet sein
2. Bei einem Video auf das X+ bei einem Tag klicken

**Erwartetes Verhalten**
"Du musst dafür angemeldet sein" sollte erscheinen 

**Screenshots**
<img width="543" alt="2019-08-20_18h36_42" src="https://user-images.githubusercontent.com/54325828/63366200-7bfabd80-c379-11e9-9d66-6864b6d04a5c.png">

**Desktop (bitte die Informationen vervollständigen):**
 - Betriebssystem: Windows
 - Browser: Firefox
 - Browser-Version: 68.0.2 (64-Bit)

**Comment by romanzipp** [comment]
Ist behoben
